package com.liberty.health.comms.model.vo;

import com.core.model.vo.classes.CoreViewObjectImpl;

import com.liberty.health.comms.model.vo.common.CompanyCountryVO;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 18 13:15:47 CAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CompanyCountryVOImpl extends CoreViewObjectImpl implements CompanyCountryVO {
    /**
     * This is the default constructor (do not remove).
     */
    public CompanyCountryVOImpl() {
    }


    /**
     * Returns the variable value for pCountryCode.
     * @return variable value for pCountryCode
     */
    public String getpCountryCode() {
        return (String) ensureVariableManager().getVariableValue("pCountryCode");
    }

    /**
     * Sets <code>value</code> for variable pCountryCode.
     * @param value value to bind as pCountryCode
     */
    public void setpCountryCode(String value) {
        ensureVariableManager().setVariableValue("pCountryCode", value);
    }

    /**
     * Returns the variable value for pCompanyIdNo.
     * @return variable value for pCompanyIdNo
     */
    public Integer getpCompanyIdNo() {
        return (Integer) ensureVariableManager().getVariableValue("pCompanyIdNo");
    }

    /**
     * Sets <code>value</code> for variable pCompanyIdNo.
     * @param value value to bind as pCompanyIdNo
     */
    public void setpCompanyIdNo(Integer value) {
        ensureVariableManager().setVariableValue("pCompanyIdNo", value);
        this.executeQuery();
    }


    /**
     *Method sets required bind variables and executes query
     * @param companyIdNo
     * @param countryCode
     */
    public void setByPkViewCriteria(Integer companyIdNo, String countryCode) {
        this.setpCompanyIdNo(companyIdNo);
        this.setpCountryCode(countryCode);
        this.executeQuery();
    }


}

