package com.liberty.health.comms.model.comms.services.common;

import java.sql.Date;

import oracle.jbo.ApplicationModule;
import oracle.jbo.domain.BlobDomain;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 09 11:54:23 CAT 2018
// ---------------------------------------------------------------------
public interface CommsRunAM extends ApplicationModule {

    String executeCommissionRun(Integer companyIdNo, String countryCode, String groupCode, String product_code,
                                String username, String parentgroupCode);


    void executeScheduledJob(String jobName);


    BlobDomain getFile(String fileName);

    void executeApproveDMRun(String StageNo, String countryCode, String userName);

    void submitFusionPayablesImport();

    void executeDmJob(String stage, String preLoad, Date commRunDate, String countryCode, String scheme, String group,
                      String username, String approve);

    String approveCommissionRun(Integer companyIdNo, String countryCode, String consultantUsername, String groupCode,
                                String product_code, String username, String parentgroupCode);
}

