package com.liberty.health.comms.model.eo;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 13 13:08:29 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ApprovalsEOImpl extends EntityImpl {
    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        CompanyIdNo,
        CompanyTableIdNo,
        CompanyTableTypeIdNo,
        ValueToApprove,
        ApprovalUser,
        RejectUser,
        LastUpdateDatetime,
        CreatedBy,
        Responded;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int COMPANYIDNO = AttributesEnum.CompanyIdNo.index();
    public static final int COMPANYTABLEIDNO = AttributesEnum.CompanyTableIdNo.index();
    public static final int COMPANYTABLETYPEIDNO = AttributesEnum.CompanyTableTypeIdNo.index();
    public static final int VALUETOAPPROVE = AttributesEnum.ValueToApprove.index();
    public static final int APPROVALUSER = AttributesEnum.ApprovalUser.index();
    public static final int REJECTUSER = AttributesEnum.RejectUser.index();
    public static final int LASTUPDATEDATETIME = AttributesEnum.LastUpdateDatetime.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int RESPONDED = AttributesEnum.Responded.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ApprovalsEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.liberty.health.comms.model.eo.ApprovalsEO");
    }


    /**
     * Gets the attribute value for CompanyIdNo, using the alias name CompanyIdNo.
     * @return the value of CompanyIdNo
     */
    public Number getCompanyIdNo() {
        return (Number) getAttributeInternal(COMPANYIDNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompanyIdNo.
     * @param value value to set the CompanyIdNo
     */
    public void setCompanyIdNo(Number value) {
        setAttributeInternal(COMPANYIDNO, value);
    }

    /**
     * Gets the attribute value for CompanyTableIdNo, using the alias name CompanyTableIdNo.
     * @return the value of CompanyTableIdNo
     */
    public Number getCompanyTableIdNo() {
        return (Number) getAttributeInternal(COMPANYTABLEIDNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompanyTableIdNo.
     * @param value value to set the CompanyTableIdNo
     */
    public void setCompanyTableIdNo(Number value) {
        setAttributeInternal(COMPANYTABLEIDNO, value);
    }

    /**
     * Gets the attribute value for CompanyTableTypeIdNo, using the alias name CompanyTableTypeIdNo.
     * @return the value of CompanyTableTypeIdNo
     */
    public Number getCompanyTableTypeIdNo() {
        return (Number) getAttributeInternal(COMPANYTABLETYPEIDNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompanyTableTypeIdNo.
     * @param value value to set the CompanyTableTypeIdNo
     */
    public void setCompanyTableTypeIdNo(Number value) {
        setAttributeInternal(COMPANYTABLETYPEIDNO, value);
    }

    /**
     * Gets the attribute value for ValueToApprove, using the alias name ValueToApprove.
     * @return the value of ValueToApprove
     */
    public String getValueToApprove() {
        return (String) getAttributeInternal(VALUETOAPPROVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ValueToApprove.
     * @param value value to set the ValueToApprove
     */
    public void setValueToApprove(String value) {
        setAttributeInternal(VALUETOAPPROVE, value);
    }

    /**
     * Gets the attribute value for ApprovalUser, using the alias name ApprovalUser.
     * @return the value of ApprovalUser
     */
    public String getApprovalUser() {
        return (String) getAttributeInternal(APPROVALUSER);
    }

    /**
     * Sets <code>value</code> as the attribute value for ApprovalUser.
     * @param value value to set the ApprovalUser
     */
    public void setApprovalUser(String value) {
        setAttributeInternal(APPROVALUSER, value);
    }

    /**
     * Gets the attribute value for RejectUser, using the alias name RejectUser.
     * @return the value of RejectUser
     */
    public String getRejectUser() {
        return (String) getAttributeInternal(REJECTUSER);
    }

    /**
     * Sets <code>value</code> as the attribute value for RejectUser.
     * @param value value to set the RejectUser
     */
    public void setRejectUser(String value) {
        setAttributeInternal(REJECTUSER, value);
    }

    /**
     * Gets the attribute value for LastUpdateDatetime, using the alias name LastUpdateDatetime.
     * @return the value of LastUpdateDatetime
     */
    public Date getLastUpdateDatetime() {
        return (Date) getAttributeInternal(LASTUPDATEDATETIME);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for Responded, using the alias name Responded.
     * @return the value of Responded
     */
    public String getResponded() {
        return (String) getAttributeInternal(RESPONDED);
    }

    /**
     * Sets <code>value</code> as the attribute value for Responded.
     * @param value value to set the Responded
     */
    public void setResponded(String value) {
        setAttributeInternal(RESPONDED, value);
    }

    /**
     * @param companyIdNo key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number companyIdNo) {
        return new Key(new Object[] { companyIdNo });
    }


}

