package com.liberty.health.comms.model.eo;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 07 10:57:32 CAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BrokerFunctionEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        BrokerIdNo,
        BrokerTableIdNo,
        EffectiveStartDate,
        EffectiveEndDate,
        BrokerTableTypeIdNo,
        LastUpdateDatetime,
        Username,
        Broker,
        BrokerTableType,
        BrokerTable;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BROKERIDNO = AttributesEnum.BrokerIdNo.index();
    public static final int BROKERTABLEIDNO = AttributesEnum.BrokerTableIdNo.index();
    public static final int EFFECTIVESTARTDATE = AttributesEnum.EffectiveStartDate.index();
    public static final int EFFECTIVEENDDATE = AttributesEnum.EffectiveEndDate.index();
    public static final int BROKERTABLETYPEIDNO = AttributesEnum.BrokerTableTypeIdNo.index();
    public static final int LASTUPDATEDATETIME = AttributesEnum.LastUpdateDatetime.index();
    public static final int USERNAME = AttributesEnum.Username.index();
    public static final int BROKER = AttributesEnum.Broker.index();
    public static final int BROKERTABLETYPE = AttributesEnum.BrokerTableType.index();
    public static final int BROKERTABLE = AttributesEnum.BrokerTable.index();

    /**
     * This is the default constructor (do not remove).
     */
    public BrokerFunctionEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.liberty.health.comms.model.eo.BrokerFunctionEO");
    }


    /**
     * Gets the attribute value for BrokerIdNo, using the alias name BrokerIdNo.
     * @return the value of BrokerIdNo
     */
    public Integer getBrokerIdNo() {
        return (Integer) getAttributeInternal(BROKERIDNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for BrokerIdNo.
     * @param value value to set the BrokerIdNo
     */
    public void setBrokerIdNo(Integer value) {
        setAttributeInternal(BROKERIDNO, value);
    }

    /**
     * Gets the attribute value for BrokerTableIdNo, using the alias name BrokerTableIdNo.
     * @return the value of BrokerTableIdNo
     */
    public Integer getBrokerTableIdNo() {
        return (Integer) getAttributeInternal(BROKERTABLEIDNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for BrokerTableIdNo.
     * @param value value to set the BrokerTableIdNo
     */
    public void setBrokerTableIdNo(Integer value) {
        setAttributeInternal(BROKERTABLEIDNO, value);
    }

    /**
     * Gets the attribute value for EffectiveStartDate, using the alias name EffectiveStartDate.
     * @return the value of EffectiveStartDate
     */
    public Date getEffectiveStartDate() {
        return (Date) getAttributeInternal(EFFECTIVESTARTDATE);
    }


    /**
     * Gets the attribute value for EffectiveEndDate, using the alias name EffectiveEndDate.
     * @return the value of EffectiveEndDate
     */
    public Date getEffectiveEndDate() {
        return (Date) getAttributeInternal(EFFECTIVEENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EffectiveEndDate.
     * @param value value to set the EffectiveEndDate
     */
    public void setEffectiveEndDate(Date value) {
        setAttributeInternal(EFFECTIVEENDDATE, value);
    }

    /**
     * Gets the attribute value for BrokerTableTypeIdNo, using the alias name BrokerTableTypeIdNo.
     * @return the value of BrokerTableTypeIdNo
     */
    public Integer getBrokerTableTypeIdNo() {
        return (Integer) getAttributeInternal(BROKERTABLETYPEIDNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for BrokerTableTypeIdNo.
     * @param value value to set the BrokerTableTypeIdNo
     */
    public void setBrokerTableTypeIdNo(Integer value) {
        setAttributeInternal(BROKERTABLETYPEIDNO, value);
    }

    /**
     * Gets the attribute value for LastUpdateDatetime, using the alias name LastUpdateDatetime.
     * @return the value of LastUpdateDatetime
     */
    public Timestamp getLastUpdateDatetime() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATETIME);
    }

    /**
     * Gets the attribute value for Username, using the alias name Username.
     * @return the value of Username
     */
    public String getUsername() {
        return (String) getAttributeInternal(USERNAME);
    }


    /**
     * @return the associated entity BrokerEOImpl.
     */
    public BrokerEOImpl getBroker() {
        return (BrokerEOImpl) getAttributeInternal(BROKER);
    }

    /**
     * Sets <code>value</code> as the associated entity BrokerEOImpl.
     */
    public void setBroker(BrokerEOImpl value) {
        setAttributeInternal(BROKER, value);
    }


    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getBrokerTableType() {
        return (EntityImpl) getAttributeInternal(BROKERTABLETYPE);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setBrokerTableType(EntityImpl value) {
        setAttributeInternal(BROKERTABLETYPE, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getBrokerTable() {
        return (RowIterator) getAttributeInternal(BROKERTABLE);
    }


    /**
     * @param brokerIdNo key constituent
     * @param brokerTableIdNo key constituent
     * @param effectiveStartDate key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer brokerIdNo, Integer brokerTableIdNo, Date effectiveStartDate) {
        return new Key(new Object[] { brokerIdNo, brokerTableIdNo, effectiveStartDate });
    }

    /**
     * Validation method for BrokerFunctionEO.
     */
    public boolean validateBrokerStartDate() {
        try {
            Date brokerStartDate = this.getBroker().getEffectiveStartDate();
            java.sql.Date brokerDate = brokerStartDate.dateValue();
            java.sql.Date accredDate = this.getEffectiveStartDate().dateValue();

            if (brokerDate.after(accredDate)) {
                return false;
            }
        } catch (NullPointerException e) {
            return false;
        }
        return true;
    }


}

