package com.liberty.health.comms.model.eo;

import com.core.model.eo.classes.CoreEntityImpl;

import java.math.BigInteger;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 17 14:09:13 CAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BrokerEOImpl extends CoreEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        BrokerIdNo,
        PersonTitleCode,
        Initials,
        BrokerName,
        BrokerLastName,
        PassportCode,
        LanguageCode,
        IdNo,
        MultinationalInd,
        InternalBrokerInd,
        SmsNotificationInd,
        EmailNotificationInd,
        LastUpdateDatetime,
        Username,
        ParentBrokerIdNo,
        KamBrokerIdNo,
        BusinessDevMgrName,
        CompanyIdNo,
        WebPassword,
        EffectiveStartDate,
        EffectiveEndDate,
        CellphoneNo,
        EmailAddress,
        WorkTelephoneNo,
        HomeTelephoneNo,
        BrokerComments,
        Company,
        CommsCalcSnapshot,
        BrokerAccreditation,
        BrokerFunction,
        CompanyConsultant,
        BrokerKAM,
        KamBroker;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BROKERIDNO = AttributesEnum.BrokerIdNo.index();
    public static final int PERSONTITLECODE = AttributesEnum.PersonTitleCode.index();
    public static final int INITIALS = AttributesEnum.Initials.index();
    public static final int BROKERNAME = AttributesEnum.BrokerName.index();
    public static final int BROKERLASTNAME = AttributesEnum.BrokerLastName.index();
    public static final int PASSPORTCODE = AttributesEnum.PassportCode.index();
    public static final int LANGUAGECODE = AttributesEnum.LanguageCode.index();
    public static final int IDNO = AttributesEnum.IdNo.index();
    public static final int MULTINATIONALIND = AttributesEnum.MultinationalInd.index();
    public static final int INTERNALBROKERIND = AttributesEnum.InternalBrokerInd.index();
    public static final int SMSNOTIFICATIONIND = AttributesEnum.SmsNotificationInd.index();
    public static final int EMAILNOTIFICATIONIND = AttributesEnum.EmailNotificationInd.index();
    public static final int LASTUPDATEDATETIME = AttributesEnum.LastUpdateDatetime.index();
    public static final int USERNAME = AttributesEnum.Username.index();
    public static final int PARENTBROKERIDNO = AttributesEnum.ParentBrokerIdNo.index();
    public static final int KAMBROKERIDNO = AttributesEnum.KamBrokerIdNo.index();
    public static final int BUSINESSDEVMGRNAME = AttributesEnum.BusinessDevMgrName.index();
    public static final int COMPANYIDNO = AttributesEnum.CompanyIdNo.index();
    public static final int WEBPASSWORD = AttributesEnum.WebPassword.index();
    public static final int EFFECTIVESTARTDATE = AttributesEnum.EffectiveStartDate.index();
    public static final int EFFECTIVEENDDATE = AttributesEnum.EffectiveEndDate.index();
    public static final int CELLPHONENO = AttributesEnum.CellphoneNo.index();
    public static final int EMAILADDRESS = AttributesEnum.EmailAddress.index();
    public static final int WORKTELEPHONENO = AttributesEnum.WorkTelephoneNo.index();
    public static final int HOMETELEPHONENO = AttributesEnum.HomeTelephoneNo.index();
    public static final int BROKERCOMMENTS = AttributesEnum.BrokerComments.index();
    public static final int COMPANY = AttributesEnum.Company.index();
    public static final int COMMSCALCSNAPSHOT = AttributesEnum.CommsCalcSnapshot.index();
    public static final int BROKERACCREDITATION = AttributesEnum.BrokerAccreditation.index();
    public static final int BROKERFUNCTION = AttributesEnum.BrokerFunction.index();
    public static final int COMPANYCONSULTANT = AttributesEnum.CompanyConsultant.index();
    public static final int BROKERKAM = AttributesEnum.BrokerKAM.index();
    public static final int KAMBROKER = AttributesEnum.KamBroker.index();

    /**
     * This is the default constructor (do not remove).
     */
    public BrokerEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.liberty.health.comms.model.eo.BrokerEO");
    }


    /**
     * Gets the attribute value for BrokerIdNo, using the alias name BrokerIdNo.
     * @return the value of BrokerIdNo
     */
    public Integer getBrokerIdNo() {
        return (Integer) getAttributeInternal(BROKERIDNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for BrokerIdNo.
     * @param value value to set the BrokerIdNo
     */
    public void setBrokerIdNo(Integer value) {
        setAttributeInternal(BROKERIDNO, value);
    }

    /**
     * Gets the attribute value for PersonTitleCode, using the alias name PersonTitleCode.
     * @return the value of PersonTitleCode
     */
    public String getPersonTitleCode() {
        return (String) getAttributeInternal(PERSONTITLECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PersonTitleCode.
     * @param value value to set the PersonTitleCode
     */
    public void setPersonTitleCode(String value) {
        setAttributeInternal(PERSONTITLECODE, value);
    }

    /**
     * Gets the attribute value for Initials, using the alias name Initials.
     * @return the value of Initials
     */
    public String getInitials() {
        return (String) getAttributeInternal(INITIALS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Initials.
     * @param value value to set the Initials
     */
    public void setInitials(String value) {
        setAttributeInternal(INITIALS, value);
    }

    /**
     * Gets the attribute value for BrokerName, using the alias name BrokerName.
     * @return the value of BrokerName
     */
    public String getBrokerName() {
        return (String) getAttributeInternal(BROKERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for BrokerName.
     * @param value value to set the BrokerName
     */
    public void setBrokerName(String value) {
        setAttributeInternal(BROKERNAME, value);
    }

    /**
     * Gets the attribute value for BrokerLastName, using the alias name BrokerLastName.
     * @return the value of BrokerLastName
     */
    public String getBrokerLastName() {
        return (String) getAttributeInternal(BROKERLASTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for BrokerLastName.
     * @param value value to set the BrokerLastName
     */
    public void setBrokerLastName(String value) {
        setAttributeInternal(BROKERLASTNAME, value);
    }

    /**
     * Gets the attribute value for PassportCode, using the alias name PassportCode.
     * @return the value of PassportCode
     */
    public String getPassportCode() {
        return (String) getAttributeInternal(PASSPORTCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PassportCode.
     * @param value value to set the PassportCode
     */
    public void setPassportCode(String value) {
        setAttributeInternal(PASSPORTCODE, value);
    }

    /**
     * Gets the attribute value for LanguageCode, using the alias name LanguageCode.
     * @return the value of LanguageCode
     */
    public String getLanguageCode() {
        return (String) getAttributeInternal(LANGUAGECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LanguageCode.
     * @param value value to set the LanguageCode
     */
    public void setLanguageCode(String value) {
        setAttributeInternal(LANGUAGECODE, value);
    }

    /**
     * Gets the attribute value for IdNo, using the alias name IdNo.
     * @return the value of IdNo
     */
    public BigInteger getIdNo() {
        return (BigInteger) getAttributeInternal(IDNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for IdNo.
     * @param value value to set the IdNo
     */
    public void setIdNo(BigInteger value) {
        setAttributeInternal(IDNO, value);
    }

    /**
     * Gets the attribute value for MultinationalInd, using the alias name MultinationalInd.
     * @return the value of MultinationalInd
     */
    public String getMultinationalInd() {
        return (String) getAttributeInternal(MULTINATIONALIND);
    }

    /**
     * Sets <code>value</code> as the attribute value for MultinationalInd.
     * @param value value to set the MultinationalInd
     */
    public void setMultinationalInd(String value) {
        setAttributeInternal(MULTINATIONALIND, value);
    }

    /**
     * Gets the attribute value for InternalBrokerInd, using the alias name InternalBrokerInd.
     * @return the value of InternalBrokerInd
     */
    public String getInternalBrokerInd() {
        return (String) getAttributeInternal(INTERNALBROKERIND);
    }

    /**
     * Sets <code>value</code> as the attribute value for InternalBrokerInd.
     * @param value value to set the InternalBrokerInd
     */
    public void setInternalBrokerInd(String value) {
        setAttributeInternal(INTERNALBROKERIND, value);
    }

    /**
     * Gets the attribute value for SmsNotificationInd, using the alias name SmsNotificationInd.
     * @return the value of SmsNotificationInd
     */
    public String getSmsNotificationInd() {
        return (String) getAttributeInternal(SMSNOTIFICATIONIND);
    }

    /**
     * Sets <code>value</code> as the attribute value for SmsNotificationInd.
     * @param value value to set the SmsNotificationInd
     */
    public void setSmsNotificationInd(String value) {
        setAttributeInternal(SMSNOTIFICATIONIND, value);
    }

    /**
     * Gets the attribute value for EmailNotificationInd, using the alias name EmailNotificationInd.
     * @return the value of EmailNotificationInd
     */
    public String getEmailNotificationInd() {
        return (String) getAttributeInternal(EMAILNOTIFICATIONIND);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmailNotificationInd.
     * @param value value to set the EmailNotificationInd
     */
    public void setEmailNotificationInd(String value) {
        setAttributeInternal(EMAILNOTIFICATIONIND, value);
    }

    /**
     * Gets the attribute value for LastUpdateDatetime, using the alias name LastUpdateDatetime.
     * @return the value of LastUpdateDatetime
     */
    public Timestamp getLastUpdateDatetime() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATETIME);
    }

    /**
     * Gets the attribute value for Username, using the alias name Username.
     * @return the value of Username
     */
    public String getUsername() {
        return (String) getAttributeInternal(USERNAME);
    }

    /**
     * Gets the attribute value for ParentBrokerIdNo, using the alias name ParentBrokerIdNo.
     * @return the value of ParentBrokerIdNo
     */
    public Integer getParentBrokerIdNo() {
        return (Integer) getAttributeInternal(PARENTBROKERIDNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParentBrokerIdNo.
     * @param value value to set the ParentBrokerIdNo
     */
    public void setParentBrokerIdNo(Integer value) {
        setAttributeInternal(PARENTBROKERIDNO, value);
    }

    /**
     * Gets the attribute value for KamBrokerIdNo, using the alias name KamBrokerIdNo.
     * @return the value of KamBrokerIdNo
     */
    public Integer getKamBrokerIdNo() {
        return (Integer) getAttributeInternal(KAMBROKERIDNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for KamBrokerIdNo.
     * @param value value to set the KamBrokerIdNo
     */
    public void setKamBrokerIdNo(Integer value) {
        setAttributeInternal(KAMBROKERIDNO, value);
    }

    /**
     * Gets the attribute value for BusinessDevMgrName, using the alias name BusinessDevMgrName.
     * @return the value of BusinessDevMgrName
     */
    public String getBusinessDevMgrName() {
        return (String) getAttributeInternal(BUSINESSDEVMGRNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for BusinessDevMgrName.
     * @param value value to set the BusinessDevMgrName
     */
    public void setBusinessDevMgrName(String value) {
        setAttributeInternal(BUSINESSDEVMGRNAME, value);
    }

    /**
     * Gets the attribute value for CompanyIdNo, using the alias name CompanyIdNo.
     * @return the value of CompanyIdNo
     */
    public Integer getCompanyIdNo() {
        return (Integer) getAttributeInternal(COMPANYIDNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompanyIdNo.
     * @param value value to set the CompanyIdNo
     */
    public void setCompanyIdNo(Integer value) {
        setAttributeInternal(COMPANYIDNO, value);
    }

    /**
     * Gets the attribute value for WebPassword, using the alias name WebPassword.
     * @return the value of WebPassword
     */
    public String getWebPassword() {
        return (String) getAttributeInternal(WEBPASSWORD);
    }

    /**
     * Sets <code>value</code> as the attribute value for WebPassword.
     * @param value value to set the WebPassword
     */
    public void setWebPassword(String value) {
        setAttributeInternal(WEBPASSWORD, value);
    }

    /**
     * Gets the attribute value for EffectiveStartDate, using the alias name EffectiveStartDate.
     * @return the value of EffectiveStartDate
     */
    public Date getEffectiveStartDate() {
        return (Date) getAttributeInternal(EFFECTIVESTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EffectiveStartDate.
     * @param value value to set the EffectiveStartDate
     */
    public void setEffectiveStartDate(Date value) {
        setAttributeInternal(EFFECTIVESTARTDATE, value);
    }

    /**
     * Gets the attribute value for EffectiveEndDate, using the alias name EffectiveEndDate.
     * @return the value of EffectiveEndDate
     */
    public Date getEffectiveEndDate() {
        return (Date) getAttributeInternal(EFFECTIVEENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EffectiveEndDate.
     * @param value value to set the EffectiveEndDate
     */
    public void setEffectiveEndDate(Date value) {
        setAttributeInternal(EFFECTIVEENDDATE, value);
    }

    /**
     * Gets the attribute value for CellphoneNo, using the alias name CellphoneNo.
     * @return the value of CellphoneNo
     */
    public String getCellphoneNo() {
        return (String) getAttributeInternal(CELLPHONENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for CellphoneNo.
     * @param value value to set the CellphoneNo
     */
    public void setCellphoneNo(String value) {
        setAttributeInternal(CELLPHONENO, value);
    }

    /**
     * Gets the attribute value for EmailAddress, using the alias name EmailAddress.
     * @return the value of EmailAddress
     */
    public String getEmailAddress() {
        return (String) getAttributeInternal(EMAILADDRESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmailAddress.
     * @param value value to set the EmailAddress
     */
    public void setEmailAddress(String value) {
        setAttributeInternal(EMAILADDRESS, value);
    }

    /**
     * Gets the attribute value for WorkTelephoneNo, using the alias name WorkTelephoneNo.
     * @return the value of WorkTelephoneNo
     */
    public String getWorkTelephoneNo() {
        return (String) getAttributeInternal(WORKTELEPHONENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for WorkTelephoneNo.
     * @param value value to set the WorkTelephoneNo
     */
    public void setWorkTelephoneNo(String value) {
        setAttributeInternal(WORKTELEPHONENO, value);
    }

    /**
     * Gets the attribute value for HomeTelephoneNo, using the alias name HomeTelephoneNo.
     * @return the value of HomeTelephoneNo
     */
    public String getHomeTelephoneNo() {
        return (String) getAttributeInternal(HOMETELEPHONENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for HomeTelephoneNo.
     * @param value value to set the HomeTelephoneNo
     */
    public void setHomeTelephoneNo(String value) {
        setAttributeInternal(HOMETELEPHONENO, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getBrokerComments() {
        return (RowIterator) getAttributeInternal(BROKERCOMMENTS);
    }


    /**
     * @return the associated entity com.core.model.eo.classes.CoreEntityImpl.
     */
    public CompanyEOImpl getCompany() {
        return (CompanyEOImpl) getAttributeInternal(COMPANY);
    }

    /**
     * Sets <code>value</code> as the associated entity com.core.model.eo.classes.CoreEntityImpl.
     */
    public void setCompany(CompanyEOImpl value) {
        setAttributeInternal(COMPANY, value);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getCommsCalcSnapshot() {
        return (RowIterator) getAttributeInternal(COMMSCALCSNAPSHOT);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getBrokerAccreditation() {
        return (RowIterator) getAttributeInternal(BROKERACCREDITATION);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getBrokerFunction() {
        return (RowIterator) getAttributeInternal(BROKERFUNCTION);
    }


    /**
     * @return the associated entity CompanyEOImpl.
     */
    public CompanyEOImpl getCompanyConsultant() {
        return (CompanyEOImpl) getAttributeInternal(COMPANYCONSULTANT);
    }

    /**
     * Sets <code>value</code> as the associated entity CompanyEOImpl.
     */
    public void setCompanyConsultant(CompanyEOImpl value) {
        setAttributeInternal(COMPANYCONSULTANT, value);
    }


    /**
     * @return the associated entity BrokerEOImpl.
     */
    public BrokerEOImpl getBrokerKAM() {
        return (BrokerEOImpl) getAttributeInternal(BROKERKAM);
    }

    /**
     * Sets <code>value</code> as the associated entity BrokerEOImpl.
     */
    public void setBrokerKAM(BrokerEOImpl value) {
        setAttributeInternal(BROKERKAM, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getKamBroker() {
        return (RowIterator) getAttributeInternal(KAMBROKER);
    }

    /**
     * @param brokerIdNo key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer brokerIdNo) {
        return new Key(new Object[] { brokerIdNo });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {

        super.create(attributeList);
        SequenceImpl seq = new SequenceImpl("BROKER_ID_NO_SEQ", getDBTransaction());
        Integer seqNo = seq.getSequenceNumber().intValue();
        setBrokerIdNo(seqNo);
    }
}

