package com.liberty.health.comms.model.eo;

import com.core.utils.DateUtils;

import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 07 10:19:22 CAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BrokerAccreditationEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        BrokerIdNo,
        EffectiveStartDate,
        EffectiveEndDate,
        BrokerAccredNo,
        BrokerAccredStartDate,
        BrokerAccredEndDate,
        LastUpdateDatetime,
        Username,
        AccreditationTypeIdNo,
        AccreditationType,
        Broker;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BROKERIDNO = AttributesEnum.BrokerIdNo.index();
    public static final int EFFECTIVESTARTDATE = AttributesEnum.EffectiveStartDate.index();
    public static final int EFFECTIVEENDDATE = AttributesEnum.EffectiveEndDate.index();
    public static final int BROKERACCREDNO = AttributesEnum.BrokerAccredNo.index();
    public static final int BROKERACCREDSTARTDATE = AttributesEnum.BrokerAccredStartDate.index();
    public static final int BROKERACCREDENDDATE = AttributesEnum.BrokerAccredEndDate.index();
    public static final int LASTUPDATEDATETIME = AttributesEnum.LastUpdateDatetime.index();
    public static final int USERNAME = AttributesEnum.Username.index();
    public static final int ACCREDITATIONTYPEIDNO = AttributesEnum.AccreditationTypeIdNo.index();
    public static final int ACCREDITATIONTYPE = AttributesEnum.AccreditationType.index();
    public static final int BROKER = AttributesEnum.Broker.index();

    /**
     * This is the default constructor (do not remove).
     */
    public BrokerAccreditationEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.liberty.health.comms.model.eo.BrokerAccreditationEO");
    }


    public boolean isAttributeUpdateable(int i) {
        Date currentDate = DateUtils.currentDateTruncated();
        if (this.getEffectiveStartDate().equals(currentDate) || i == AttributesEnum.EffectiveEndDate.index()) {
            return true;
        } else {
            return false;
        }
    }


    /**
     * Gets the attribute value for BrokerIdNo, using the alias name BrokerIdNo.
     * @return the value of BrokerIdNo
     */
    public Integer getBrokerIdNo() {
        return (Integer) getAttributeInternal(BROKERIDNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for BrokerIdNo.
     * @param value value to set the BrokerIdNo
     */
    public void setBrokerIdNo(Integer value) {
        setAttributeInternal(BROKERIDNO, value);
    }

    /**
     * Gets the attribute value for EffectiveStartDate, using the alias name EffectiveStartDate.
     * @return the value of EffectiveStartDate
     */
    public Date getEffectiveStartDate() {
        return (Date) getAttributeInternal(EFFECTIVESTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EffectiveStartDate.
     * @param value value to set the EffectiveStartDate
     */
    public void setEffectiveStartDate(Date value) {
        setAttributeInternal(EFFECTIVESTARTDATE, value);
    }

    /**
     * Gets the attribute value for EffectiveEndDate, using the alias name EffectiveEndDate.
     * @return the value of EffectiveEndDate
     */
    public Date getEffectiveEndDate() {
        return (Date) getAttributeInternal(EFFECTIVEENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EffectiveEndDate.
     * @param value value to set the EffectiveEndDate
     */
    public void setEffectiveEndDate(Date value) {
        setAttributeInternal(EFFECTIVEENDDATE, value);
    }

    /**
     * Gets the attribute value for BrokerAccredNo, using the alias name BrokerAccredNo.
     * @return the value of BrokerAccredNo
     */
    public Number getBrokerAccredNo() {
        return (Number) getAttributeInternal(BROKERACCREDNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for BrokerAccredNo.
     * @param value value to set the BrokerAccredNo
     */
    public void setBrokerAccredNo(Number value) {
        setAttributeInternal(BROKERACCREDNO, value);
    }

    /**
     * Gets the attribute value for BrokerAccredStartDate, using the alias name BrokerAccredStartDate.
     * @return the value of BrokerAccredStartDate
     */
    public Date getBrokerAccredStartDate() {
        return (Date) getAttributeInternal(BROKERACCREDSTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BrokerAccredStartDate.
     * @param value value to set the BrokerAccredStartDate
     */
    public void setBrokerAccredStartDate(Date value) {
        setAttributeInternal(BROKERACCREDSTARTDATE, value);
    }

    /**
     * Gets the attribute value for BrokerAccredEndDate, using the alias name BrokerAccredEndDate.
     * @return the value of BrokerAccredEndDate
     */
    public Date getBrokerAccredEndDate() {
        return (Date) getAttributeInternal(BROKERACCREDENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BrokerAccredEndDate.
     * @param value value to set the BrokerAccredEndDate
     */
    public void setBrokerAccredEndDate(Date value) {
        setAttributeInternal(BROKERACCREDENDDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdateDatetime, using the alias name LastUpdateDatetime.
     * @return the value of LastUpdateDatetime
     */
    public Date getLastUpdateDatetime() {
        return (Date) getAttributeInternal(LASTUPDATEDATETIME);
    }

    /**
     * Gets the attribute value for Username, using the alias name Username.
     * @return the value of Username
     */
    public String getUsername() {
        return (String) getAttributeInternal(USERNAME);
    }

    /**
     * Gets the attribute value for AccreditationTypeIdNo, using the alias name AccreditationTypeIdNo.
     * @return the value of AccreditationTypeIdNo
     */
    public Integer getAccreditationTypeIdNo() {
        return (Integer) getAttributeInternal(ACCREDITATIONTYPEIDNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for AccreditationTypeIdNo.
     * @param value value to set the AccreditationTypeIdNo
     */
    public void setAccreditationTypeIdNo(Integer value) {
        setAttributeInternal(ACCREDITATIONTYPEIDNO, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getAccreditationType() {
        return (EntityImpl) getAttributeInternal(ACCREDITATIONTYPE);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setAccreditationType(EntityImpl value) {
        setAttributeInternal(ACCREDITATIONTYPE, value);
    }

    /**
     * @return the associated entity BrokerEOImpl.
     */
    public BrokerEOImpl getBroker() {
        return (BrokerEOImpl) getAttributeInternal(BROKER);
    }

    /**
     * Sets <code>value</code> as the associated entity BrokerEOImpl.
     */
    public void setBroker(BrokerEOImpl value) {
        setAttributeInternal(BROKER, value);
    }


    /**
     * @param brokerIdNo key constituent
     * @param effectiveStartDate key constituent
     * @param accreditationTypeIdNo key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer brokerIdNo, Date effectiveStartDate, Integer accreditationTypeIdNo) {
        return new Key(new Object[] { brokerIdNo, effectiveStartDate, accreditationTypeIdNo });
    }

    /**
     * Validation method for BrokerAccreditationEO.
     */
    public boolean validateBrokerEffectiveStartDate() {
        try {
            Date brokerStartDate = this.getBroker().getEffectiveStartDate();
            java.sql.Date brokerDate = brokerStartDate.dateValue();
            java.sql.Date accredDate = this.getEffectiveStartDate().dateValue();

            if (brokerDate.after(accredDate)) {
                return false;
            }
        } catch (NullPointerException e) {
            return false;
        }
        return true;
    }


}

