package com.liberty.health.comms.model.eo;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 16 08:54:16 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CommissionAccuralsEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        CommsAccrualPk,
        Bu,
        GroupCode,
        FinanceInvoiceDate,
        FinanceInvoiceNumber,
        FinanceInvoiceType,
        CurrencyCode,
        Optionval,
        ContributionDate,
        FinanceInvoiceAmt,
        CompanyIdNo,
        CommsPerc,
        CalculatedCommsAmt,
        GeneratedInFusion,
        FusionApInvoice,
        CreationDate,
        LastUpdateDate,
        LastUpdatedBy;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int COMMSACCRUALPK = AttributesEnum.CommsAccrualPk.index();
    public static final int BU = AttributesEnum.Bu.index();
    public static final int GROUPCODE = AttributesEnum.GroupCode.index();
    public static final int FINANCEINVOICEDATE = AttributesEnum.FinanceInvoiceDate.index();
    public static final int FINANCEINVOICENUMBER = AttributesEnum.FinanceInvoiceNumber.index();
    public static final int FINANCEINVOICETYPE = AttributesEnum.FinanceInvoiceType.index();
    public static final int CURRENCYCODE = AttributesEnum.CurrencyCode.index();
    public static final int OPTIONVAL = AttributesEnum.Optionval.index();
    public static final int CONTRIBUTIONDATE = AttributesEnum.ContributionDate.index();
    public static final int FINANCEINVOICEAMT = AttributesEnum.FinanceInvoiceAmt.index();
    public static final int COMPANYIDNO = AttributesEnum.CompanyIdNo.index();
    public static final int COMMSPERC = AttributesEnum.CommsPerc.index();
    public static final int CALCULATEDCOMMSAMT = AttributesEnum.CalculatedCommsAmt.index();
    public static final int GENERATEDINFUSION = AttributesEnum.GeneratedInFusion.index();
    public static final int FUSIONAPINVOICE = AttributesEnum.FusionApInvoice.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CommissionAccuralsEOImpl() {
    }

    /**
     * Gets the attribute value for CommsAccrualPk, using the alias name CommsAccrualPk.
     * @return the value of CommsAccrualPk
     */
    public Number getCommsAccrualPk() {
        return (Number) getAttributeInternal(COMMSACCRUALPK);
    }

    /**
     * Sets <code>value</code> as the attribute value for CommsAccrualPk.
     * @param value value to set the CommsAccrualPk
     */
    public void setCommsAccrualPk(Number value) {
        setAttributeInternal(COMMSACCRUALPK, value);
    }

    /**
     * Gets the attribute value for Bu, using the alias name Bu.
     * @return the value of Bu
     */
    public String getBu() {
        return (String) getAttributeInternal(BU);
    }

    /**
     * Sets <code>value</code> as the attribute value for Bu.
     * @param value value to set the Bu
     */
    public void setBu(String value) {
        setAttributeInternal(BU, value);
    }

    /**
     * Gets the attribute value for GroupCode, using the alias name GroupCode.
     * @return the value of GroupCode
     */
    public String getGroupCode() {
        return (String) getAttributeInternal(GROUPCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for GroupCode.
     * @param value value to set the GroupCode
     */
    public void setGroupCode(String value) {
        setAttributeInternal(GROUPCODE, value);
    }

    /**
     * Gets the attribute value for FinanceInvoiceDate, using the alias name FinanceInvoiceDate.
     * @return the value of FinanceInvoiceDate
     */
    public Date getFinanceInvoiceDate() {
        return (Date) getAttributeInternal(FINANCEINVOICEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FinanceInvoiceDate.
     * @param value value to set the FinanceInvoiceDate
     */
    public void setFinanceInvoiceDate(Date value) {
        setAttributeInternal(FINANCEINVOICEDATE, value);
    }

    /**
     * Gets the attribute value for FinanceInvoiceNumber, using the alias name FinanceInvoiceNumber.
     * @return the value of FinanceInvoiceNumber
     */
    public String getFinanceInvoiceNumber() {
        return (String) getAttributeInternal(FINANCEINVOICENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for FinanceInvoiceNumber.
     * @param value value to set the FinanceInvoiceNumber
     */
    public void setFinanceInvoiceNumber(String value) {
        setAttributeInternal(FINANCEINVOICENUMBER, value);
    }

    /**
     * Gets the attribute value for FinanceInvoiceType, using the alias name FinanceInvoiceType.
     * @return the value of FinanceInvoiceType
     */
    public String getFinanceInvoiceType() {
        return (String) getAttributeInternal(FINANCEINVOICETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FinanceInvoiceType.
     * @param value value to set the FinanceInvoiceType
     */
    public void setFinanceInvoiceType(String value) {
        setAttributeInternal(FINANCEINVOICETYPE, value);
    }

    /**
     * Gets the attribute value for CurrencyCode, using the alias name CurrencyCode.
     * @return the value of CurrencyCode
     */
    public String getCurrencyCode() {
        return (String) getAttributeInternal(CURRENCYCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CurrencyCode.
     * @param value value to set the CurrencyCode
     */
    public void setCurrencyCode(String value) {
        setAttributeInternal(CURRENCYCODE, value);
    }

    /**
     * Gets the attribute value for Optionval, using the alias name Optionval.
     * @return the value of Optionval
     */
    public String getOptionval() {
        return (String) getAttributeInternal(OPTIONVAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Optionval.
     * @param value value to set the Optionval
     */
    public void setOptionval(String value) {
        setAttributeInternal(OPTIONVAL, value);
    }

    /**
     * Gets the attribute value for ContributionDate, using the alias name ContributionDate.
     * @return the value of ContributionDate
     */
    public Date getContributionDate() {
        return (Date) getAttributeInternal(CONTRIBUTIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContributionDate.
     * @param value value to set the ContributionDate
     */
    public void setContributionDate(Date value) {
        setAttributeInternal(CONTRIBUTIONDATE, value);
    }

    /**
     * Gets the attribute value for FinanceInvoiceAmt, using the alias name FinanceInvoiceAmt.
     * @return the value of FinanceInvoiceAmt
     */
    public Number getFinanceInvoiceAmt() {
        return (Number) getAttributeInternal(FINANCEINVOICEAMT);
    }

    /**
     * Sets <code>value</code> as the attribute value for FinanceInvoiceAmt.
     * @param value value to set the FinanceInvoiceAmt
     */
    public void setFinanceInvoiceAmt(Number value) {
        setAttributeInternal(FINANCEINVOICEAMT, value);
    }

    /**
     * Gets the attribute value for CompanyIdNo, using the alias name CompanyIdNo.
     * @return the value of CompanyIdNo
     */
    public String getCompanyIdNo() {
        return (String) getAttributeInternal(COMPANYIDNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompanyIdNo.
     * @param value value to set the CompanyIdNo
     */
    public void setCompanyIdNo(String value) {
        setAttributeInternal(COMPANYIDNO, value);
    }

    /**
     * Gets the attribute value for CommsPerc, using the alias name CommsPerc.
     * @return the value of CommsPerc
     */
    public Number getCommsPerc() {
        return (Number) getAttributeInternal(COMMSPERC);
    }

    /**
     * Sets <code>value</code> as the attribute value for CommsPerc.
     * @param value value to set the CommsPerc
     */
    public void setCommsPerc(Number value) {
        setAttributeInternal(COMMSPERC, value);
    }

    /**
     * Gets the attribute value for CalculatedCommsAmt, using the alias name CalculatedCommsAmt.
     * @return the value of CalculatedCommsAmt
     */
    public Number getCalculatedCommsAmt() {
        return (Number) getAttributeInternal(CALCULATEDCOMMSAMT);
    }

    /**
     * Sets <code>value</code> as the attribute value for CalculatedCommsAmt.
     * @param value value to set the CalculatedCommsAmt
     */
    public void setCalculatedCommsAmt(Number value) {
        setAttributeInternal(CALCULATEDCOMMSAMT, value);
    }

    /**
     * Gets the attribute value for GeneratedInFusion, using the alias name GeneratedInFusion.
     * @return the value of GeneratedInFusion
     */
    public String getGeneratedInFusion() {
        return (String) getAttributeInternal(GENERATEDINFUSION);
    }

    /**
     * Sets <code>value</code> as the attribute value for GeneratedInFusion.
     * @param value value to set the GeneratedInFusion
     */
    public void setGeneratedInFusion(String value) {
        setAttributeInternal(GENERATEDINFUSION, value);
    }

    /**
     * Gets the attribute value for FusionApInvoice, using the alias name FusionApInvoice.
     * @return the value of FusionApInvoice
     */
    public String getFusionApInvoice() {
        return (String) getAttributeInternal(FUSIONAPINVOICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FusionApInvoice.
     * @param value value to set the FusionApInvoice
     */
    public void setFusionApInvoice(String value) {
        setAttributeInternal(FUSIONAPINVOICE, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the value of LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * @param commsAccrualPk key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number commsAccrualPk) {
        return new Key(new Object[] { commsAccrualPk });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.liberty.health.comms.model.eo.CommissionAccuralsEO");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}

