package com.liberty.health.comms.model.eo;

import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 09 12:48:13 CAT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvoiceDetailDmEODefImpl extends EntityDefImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public InvoiceDetailDmEODefImpl() {
    }
}

