package com.liberty.health.comms.model.eo;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 09 12:53:30 CAT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvoiceDmEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        InvoiceNo,
        InvoiceDate,
        PaymentReceiveDate,
        CountryCode,
        CompanyIdNo,
        InvoiceTypeIdNo,
        ReleaseDate,
        ReleaseHoldReason,
        PaymentDate,
        PaymentRejectDate,
        PaymentRejectDesc,
        PaymentAmt,
        PaymentExchRate,
        CurrencyCode,
        LastUpdateDatetime,
        Username,
        InvoiceTaxCodes,
        InvoiceDetailDm;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int INVOICENO = AttributesEnum.InvoiceNo.index();
    public static final int INVOICEDATE = AttributesEnum.InvoiceDate.index();
    public static final int PAYMENTRECEIVEDATE = AttributesEnum.PaymentReceiveDate.index();
    public static final int COUNTRYCODE = AttributesEnum.CountryCode.index();
    public static final int COMPANYIDNO = AttributesEnum.CompanyIdNo.index();
    public static final int INVOICETYPEIDNO = AttributesEnum.InvoiceTypeIdNo.index();
    public static final int RELEASEDATE = AttributesEnum.ReleaseDate.index();
    public static final int RELEASEHOLDREASON = AttributesEnum.ReleaseHoldReason.index();
    public static final int PAYMENTDATE = AttributesEnum.PaymentDate.index();
    public static final int PAYMENTREJECTDATE = AttributesEnum.PaymentRejectDate.index();
    public static final int PAYMENTREJECTDESC = AttributesEnum.PaymentRejectDesc.index();
    public static final int PAYMENTAMT = AttributesEnum.PaymentAmt.index();
    public static final int PAYMENTEXCHRATE = AttributesEnum.PaymentExchRate.index();
    public static final int CURRENCYCODE = AttributesEnum.CurrencyCode.index();
    public static final int LASTUPDATEDATETIME = AttributesEnum.LastUpdateDatetime.index();
    public static final int USERNAME = AttributesEnum.Username.index();
    public static final int INVOICETAXCODES = AttributesEnum.InvoiceTaxCodes.index();
    public static final int INVOICEDETAILDM = AttributesEnum.InvoiceDetailDm.index();

    /**
     * This is the default constructor (do not remove).
     */
    public InvoiceDmEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.liberty.health.comms.model.eo.InvoiceDmEO");
    }

    /**
     * Gets the attribute value for InvoiceNo, using the alias name InvoiceNo.
     * @return the value of InvoiceNo
     */
    public Number getInvoiceNo() {
        return (Number) getAttributeInternal(INVOICENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvoiceNo.
     * @param value value to set the InvoiceNo
     */
    public void setInvoiceNo(Number value) {
        setAttributeInternal(INVOICENO, value);
    }

    /**
     * Gets the attribute value for InvoiceDate, using the alias name InvoiceDate.
     * @return the value of InvoiceDate
     */
    public Date getInvoiceDate() {
        return (Date) getAttributeInternal(INVOICEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvoiceDate.
     * @param value value to set the InvoiceDate
     */
    public void setInvoiceDate(Date value) {
        setAttributeInternal(INVOICEDATE, value);
    }

    /**
     * Gets the attribute value for PaymentReceiveDate, using the alias name PaymentReceiveDate.
     * @return the value of PaymentReceiveDate
     */
    public Date getPaymentReceiveDate() {
        return (Date) getAttributeInternal(PAYMENTRECEIVEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PaymentReceiveDate.
     * @param value value to set the PaymentReceiveDate
     */
    public void setPaymentReceiveDate(Date value) {
        setAttributeInternal(PAYMENTRECEIVEDATE, value);
    }

    /**
     * Gets the attribute value for CountryCode, using the alias name CountryCode.
     * @return the value of CountryCode
     */
    public String getCountryCode() {
        return (String) getAttributeInternal(COUNTRYCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CountryCode.
     * @param value value to set the CountryCode
     */
    public void setCountryCode(String value) {
        setAttributeInternal(COUNTRYCODE, value);
    }

    /**
     * Gets the attribute value for CompanyIdNo, using the alias name CompanyIdNo.
     * @return the value of CompanyIdNo
     */
    public Number getCompanyIdNo() {
        return (Number) getAttributeInternal(COMPANYIDNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompanyIdNo.
     * @param value value to set the CompanyIdNo
     */
    public void setCompanyIdNo(Number value) {
        setAttributeInternal(COMPANYIDNO, value);
    }

    /**
     * Gets the attribute value for InvoiceTypeIdNo, using the alias name InvoiceTypeIdNo.
     * @return the value of InvoiceTypeIdNo
     */
    public Number getInvoiceTypeIdNo() {
        return (Number) getAttributeInternal(INVOICETYPEIDNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvoiceTypeIdNo.
     * @param value value to set the InvoiceTypeIdNo
     */
    public void setInvoiceTypeIdNo(Number value) {
        setAttributeInternal(INVOICETYPEIDNO, value);
    }

    /**
     * Gets the attribute value for ReleaseDate, using the alias name ReleaseDate.
     * @return the value of ReleaseDate
     */
    public Date getReleaseDate() {
        return (Date) getAttributeInternal(RELEASEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReleaseDate.
     * @param value value to set the ReleaseDate
     */
    public void setReleaseDate(Date value) {
        setAttributeInternal(RELEASEDATE, value);
    }

    /**
     * Gets the attribute value for ReleaseHoldReason, using the alias name ReleaseHoldReason.
     * @return the value of ReleaseHoldReason
     */
    public String getReleaseHoldReason() {
        return (String) getAttributeInternal(RELEASEHOLDREASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReleaseHoldReason.
     * @param value value to set the ReleaseHoldReason
     */
    public void setReleaseHoldReason(String value) {
        setAttributeInternal(RELEASEHOLDREASON, value);
    }

    /**
     * Gets the attribute value for PaymentDate, using the alias name PaymentDate.
     * @return the value of PaymentDate
     */
    public Date getPaymentDate() {
        return (Date) getAttributeInternal(PAYMENTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PaymentDate.
     * @param value value to set the PaymentDate
     */
    public void setPaymentDate(Date value) {
        setAttributeInternal(PAYMENTDATE, value);
    }

    /**
     * Gets the attribute value for PaymentRejectDate, using the alias name PaymentRejectDate.
     * @return the value of PaymentRejectDate
     */
    public Date getPaymentRejectDate() {
        return (Date) getAttributeInternal(PAYMENTREJECTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PaymentRejectDate.
     * @param value value to set the PaymentRejectDate
     */
    public void setPaymentRejectDate(Date value) {
        setAttributeInternal(PAYMENTREJECTDATE, value);
    }

    /**
     * Gets the attribute value for PaymentRejectDesc, using the alias name PaymentRejectDesc.
     * @return the value of PaymentRejectDesc
     */
    public String getPaymentRejectDesc() {
        return (String) getAttributeInternal(PAYMENTREJECTDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for PaymentRejectDesc.
     * @param value value to set the PaymentRejectDesc
     */
    public void setPaymentRejectDesc(String value) {
        setAttributeInternal(PAYMENTREJECTDESC, value);
    }

    /**
     * Gets the attribute value for PaymentAmt, using the alias name PaymentAmt.
     * @return the value of PaymentAmt
     */
    public Number getPaymentAmt() {
        return (Number) getAttributeInternal(PAYMENTAMT);
    }

    /**
     * Sets <code>value</code> as the attribute value for PaymentAmt.
     * @param value value to set the PaymentAmt
     */
    public void setPaymentAmt(Number value) {
        setAttributeInternal(PAYMENTAMT, value);
    }

    /**
     * Gets the attribute value for PaymentExchRate, using the alias name PaymentExchRate.
     * @return the value of PaymentExchRate
     */
    public Number getPaymentExchRate() {
        return (Number) getAttributeInternal(PAYMENTEXCHRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PaymentExchRate.
     * @param value value to set the PaymentExchRate
     */
    public void setPaymentExchRate(Number value) {
        setAttributeInternal(PAYMENTEXCHRATE, value);
    }

    /**
     * Gets the attribute value for CurrencyCode, using the alias name CurrencyCode.
     * @return the value of CurrencyCode
     */
    public String getCurrencyCode() {
        return (String) getAttributeInternal(CURRENCYCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CurrencyCode.
     * @param value value to set the CurrencyCode
     */
    public void setCurrencyCode(String value) {
        setAttributeInternal(CURRENCYCODE, value);
    }

    /**
     * Gets the attribute value for LastUpdateDatetime, using the alias name LastUpdateDatetime.
     * @return the value of LastUpdateDatetime
     */
    public Date getLastUpdateDatetime() {
        return (Date) getAttributeInternal(LASTUPDATEDATETIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDatetime.
     * @param value value to set the LastUpdateDatetime
     */
    public void setLastUpdateDatetime(Date value) {
        setAttributeInternal(LASTUPDATEDATETIME, value);
    }

    /**
     * Gets the attribute value for Username, using the alias name Username.
     * @return the value of Username
     */
    public String getUsername() {
        return (String) getAttributeInternal(USERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for Username.
     * @param value value to set the Username
     */
    public void setUsername(String value) {
        setAttributeInternal(USERNAME, value);
    }

    /**
     * Gets the attribute value for InvoiceTaxCodes, using the alias name InvoiceTaxCodes.
     * @return the value of InvoiceTaxCodes
     */
    public String getInvoiceTaxCodes() {
        return (String) getAttributeInternal(INVOICETAXCODES);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvoiceTaxCodes.
     * @param value value to set the InvoiceTaxCodes
     */
    public void setInvoiceTaxCodes(String value) {
        setAttributeInternal(INVOICETAXCODES, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getInvoiceDetailDm() {
        return (RowIterator) getAttributeInternal(INVOICEDETAILDM);
    }


    /**
     * @param invoiceNo key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number invoiceNo) {
        return new Key(new Object[] { invoiceNo });
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}

