package com.liberty.health.comms.model.eo;

import oracle.jbo.server.EntityCache;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 09 12:54:00 CAT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvoiceDmEOCollImpl extends EntityCache {
    /**
     * This is the default constructor (do not remove).
     */
    public InvoiceDmEOCollImpl() {
    }
}

