package com.liberty.health.comms.model.lookup.vo;

import com.core.model.vo.classes.CoreViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 19 16:50:32 CAT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CountryTaxesAuditVORowImpl extends CoreViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        TransactionDatetime,
        TransactionDesc,
        TransactionUsername,
        CountryCode,
        AccreditationTypeIdNo,
        EffectiveStartDate,
        EffectiveEndDate,
        AccredLocal,
        AccredMulti,
        NoAccrLocal,
        NoAccrMulti;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int TRANSACTIONDATETIME = AttributesEnum.TransactionDatetime.index();
    public static final int TRANSACTIONDESC = AttributesEnum.TransactionDesc.index();
    public static final int TRANSACTIONUSERNAME = AttributesEnum.TransactionUsername.index();
    public static final int COUNTRYCODE = AttributesEnum.CountryCode.index();
    public static final int ACCREDITATIONTYPEIDNO = AttributesEnum.AccreditationTypeIdNo.index();
    public static final int EFFECTIVESTARTDATE = AttributesEnum.EffectiveStartDate.index();
    public static final int EFFECTIVEENDDATE = AttributesEnum.EffectiveEndDate.index();
    public static final int ACCREDLOCAL = AttributesEnum.AccredLocal.index();
    public static final int ACCREDMULTI = AttributesEnum.AccredMulti.index();
    public static final int NOACCRLOCAL = AttributesEnum.NoAccrLocal.index();
    public static final int NOACCRMULTI = AttributesEnum.NoAccrMulti.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CountryTaxesAuditVORowImpl() {
    }
}

