package com.liberty.health.comms.model.lookup.vo;

import com.core.model.vo.classes.CoreViewObjectImpl;

import com.liberty.health.comms.model.lookup.vo.common.ExchangeRatesRoView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 16 12:42:08 CAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ExchangeRatesRoViewImpl extends CoreViewObjectImpl implements ExchangeRatesRoView {
    /**
     * This is the default constructor (do not remove).
     */
    public ExchangeRatesRoViewImpl() {
    }

    /**
     * Returns the variable value for pToCurrencyCode.
     * @return variable value for pToCurrencyCode
     */
    public String getpToCurrencyCode() {
        return (String) ensureVariableManager().getVariableValue("pToCurrencyCode");
    }
    
    
    public void setByCurrencyCodeViewCriteria(String fromCode, String toCode) {
        this.setpFromCurrencyCode(fromCode);
        this.setpToCurrencyCode(toCode);
        this.executeQuery();
    }

    /**
     * Sets <code>value</code> for variable pToCurrencyCode.
     * @param value value to bind as pToCurrencyCode
     */
    public void setpToCurrencyCode(String value) {
        ensureVariableManager().setVariableValue("pToCurrencyCode", value);
    }

    /**
     * Returns the variable value for pFromCurrencyCode.
     * @return variable value for pFromCurrencyCode
     */
    public String getpFromCurrencyCode() {
        return (String) ensureVariableManager().getVariableValue("pFromCurrencyCode");
    }

    /**
     * Sets <code>value</code> for variable pFromCurrencyCode.
     * @param value value to bind as pFromCurrencyCode
     */
    public void setpFromCurrencyCode(String value) {
        ensureVariableManager().setVariableValue("pFromCurrencyCode", value);
    }
}

