package com.liberty.health.comms.model.broker.vo;

import com.core.model.vo.classes.CoreViewRowImpl;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 16 11:43:50 CAT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BrokerStatementsSubmitRoViewRowImpl extends CoreViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Day,
        BrokerIdNo,
        CompanyIdNo,
        StatementStartDate,
        LanguageCode,
        TemplateCode,
        StatementEndDate,
        CountryCode,
        BrokerLovView1,
        CompanyLovView1,
        LanguageLovView1,
        CommHubTemplateTypeLovView1,
        CompanyCountryLovView1,
        CountryLovView1,
        CountryLovView_N1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DAY = AttributesEnum.Day.index();
    public static final int BROKERIDNO = AttributesEnum.BrokerIdNo.index();
    public static final int COMPANYIDNO = AttributesEnum.CompanyIdNo.index();
    public static final int STATEMENTSTARTDATE = AttributesEnum.StatementStartDate.index();
    public static final int LANGUAGECODE = AttributesEnum.LanguageCode.index();
    public static final int TEMPLATECODE = AttributesEnum.TemplateCode.index();
    public static final int STATEMENTENDDATE = AttributesEnum.StatementEndDate.index();
    public static final int COUNTRYCODE = AttributesEnum.CountryCode.index();
    public static final int BROKERLOVVIEW1 = AttributesEnum.BrokerLovView1.index();
    public static final int COMPANYLOVVIEW1 = AttributesEnum.CompanyLovView1.index();
    public static final int LANGUAGELOVVIEW1 = AttributesEnum.LanguageLovView1.index();
    public static final int COMMHUBTEMPLATETYPELOVVIEW1 = AttributesEnum.CommHubTemplateTypeLovView1.index();
    public static final int COMPANYCOUNTRYLOVVIEW1 = AttributesEnum.CompanyCountryLovView1.index();
    public static final int COUNTRYLOVVIEW1 = AttributesEnum.CountryLovView1.index();
    public static final int COUNTRYLOVVIEW_N1 = AttributesEnum.CountryLovView_N1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public BrokerStatementsSubmitRoViewRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute Day.
     * @return the Day
     */
    public Date getDay() {
        return (Date) getAttributeInternal(DAY);
    }

    /**
     * Gets the attribute value for the calculated attribute BrokerIdNo.
     * @return the BrokerIdNo
     */
    public Number getBrokerIdNo() {
        return (Number) getAttributeInternal(BROKERIDNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BrokerIdNo.
     * @param value value to set the  BrokerIdNo
     */
    public void setBrokerIdNo(Number value) {
        setAttributeInternal(BROKERIDNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CompanyIdNo.
     * @return the CompanyIdNo
     */
    public Number getCompanyIdNo() {
        return (Number) getAttributeInternal(COMPANYIDNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CompanyIdNo.
     * @param value value to set the  CompanyIdNo
     */
    public void setCompanyIdNo(Number value) {
        setAttributeInternal(COMPANYIDNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StatementStartDate.
     * @return the StatementStartDate
     */
    public Date getStatementStartDate() {
        return (Date) getAttributeInternal(STATEMENTSTARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StatementStartDate.
     * @param value value to set the  StatementStartDate
     */
    public void setStatementStartDate(Date value) {
        if (this.getStatementEndDate() == null) {
            this.setStatementEndDate(value);
        }
        setAttributeInternal(STATEMENTSTARTDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LanguageCode.
     * @return the LanguageCode
     */
    public String getLanguageCode() {
        return (String) getAttributeInternal(LANGUAGECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LanguageCode.
     * @param value value to set the  LanguageCode
     */
    public void setLanguageCode(String value) {
        setAttributeInternal(LANGUAGECODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TemplateCode.
     * @return the TemplateCode
     */
    public String getTemplateCode() {
        return (String) getAttributeInternal(TEMPLATECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TemplateCode.
     * @param value value to set the  TemplateCode
     */
    public void setTemplateCode(String value) {
        setAttributeInternal(TEMPLATECODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StatementEndDate.
     * @return the StatementEndDate
     */
    public Date getStatementEndDate() {
        return (Date) getAttributeInternal(STATEMENTENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StatementEndDate.
     * @param value value to set the  StatementEndDate
     */
    public void setStatementEndDate(Date value) {
        setAttributeInternal(STATEMENTENDDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CountryCode.
     * @return the CountryCode
     */
    public String getCountryCode() {
        return (String) getAttributeInternal(COUNTRYCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CountryCode.
     * @param value value to set the  CountryCode
     */
    public void setCountryCode(String value) {
        setAttributeInternal(COUNTRYCODE, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BrokerLovView1.
     */
    public RowSet getBrokerLovView1() {
        return (RowSet) getAttributeInternal(BROKERLOVVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CompanyLovView1.
     */
    public RowSet getCompanyLovView1() {
        return (RowSet) getAttributeInternal(COMPANYLOVVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LanguageLovView1.
     */
    public RowSet getLanguageLovView1() {
        return (RowSet) getAttributeInternal(LANGUAGELOVVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CommHubTemplateTypeLovView1.
     */
    public RowSet getCommHubTemplateTypeLovView1() {
        return (RowSet) getAttributeInternal(COMMHUBTEMPLATETYPELOVVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CompanyCountryLovView1.
     */
    public RowSet getCompanyCountryLovView1() {
        return (RowSet) getAttributeInternal(COMPANYCOUNTRYLOVVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CountryLovView1.
     */
    public RowSet getCountryLovView1() {
        return (RowSet) getAttributeInternal(COUNTRYLOVVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CountryLovView_N1.
     */
    public RowSet getCountryLovView_N1() {
        return (RowSet) getAttributeInternal(COUNTRYLOVVIEW_N1);
    }
}

