package com.liberty.health.comms.model.broker.vo;

import com.core.model.vo.classes.CoreViewRowImpl;

import com.liberty.health.comms.model.eo.CompanyContactEOImpl;

import java.sql.Timestamp;

import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 24 14:58:49 CAT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CompanyContactCorrVORowImpl extends CoreViewRowImpl {
    public static final int ENTITY_COMPANYCONTACTEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        CompanyContactTypeIdNo,
        CompanyIdNo,
        ContactCellphoneNo,
        ContactDesc,
        ContactEmail,
        ContactFaxNo,
        ContactName,
        ContactTelephoneNo,
        CountryCode,
        EffectiveEndDate,
        EffectiveStartDate,
        LastUpdateDatetime,
        Username;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int COMPANYCONTACTTYPEIDNO = AttributesEnum.CompanyContactTypeIdNo.index();
    public static final int COMPANYIDNO = AttributesEnum.CompanyIdNo.index();
    public static final int CONTACTCELLPHONENO = AttributesEnum.ContactCellphoneNo.index();
    public static final int CONTACTDESC = AttributesEnum.ContactDesc.index();
    public static final int CONTACTEMAIL = AttributesEnum.ContactEmail.index();
    public static final int CONTACTFAXNO = AttributesEnum.ContactFaxNo.index();
    public static final int CONTACTNAME = AttributesEnum.ContactName.index();
    public static final int CONTACTTELEPHONENO = AttributesEnum.ContactTelephoneNo.index();
    public static final int COUNTRYCODE = AttributesEnum.CountryCode.index();
    public static final int EFFECTIVEENDDATE = AttributesEnum.EffectiveEndDate.index();
    public static final int EFFECTIVESTARTDATE = AttributesEnum.EffectiveStartDate.index();
    public static final int LASTUPDATEDATETIME = AttributesEnum.LastUpdateDatetime.index();
    public static final int USERNAME = AttributesEnum.Username.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CompanyContactCorrVORowImpl() {
    }

    /**
     * Gets CompanyContactEO entity object.
     * @return the CompanyContactEO
     */
    public CompanyContactEOImpl getCompanyContactEO() {
        return (CompanyContactEOImpl) getEntity(ENTITY_COMPANYCONTACTEO);
    }
    
   /* @Override
       public boolean isAttributeUpdateable(int index) {
           boolean isUpdateable = super.isAttributeUpdateable(index);
           
           // do not allow updating first and last name
           if (index == CONTACTNAME  || index == CONTACTCELLPHONENO 
                                     || index == CONTACTDESC
                                     || index == CONTACTEMAIL
                                     || index == CONTACTFAXNO
                                     || index == CONTACTNAME
                                     || index == CONTACTTELEPHONENO) {
               isUpdateable = true;
           }
           
           return isUpdateable;
       }*/

    /**
     * Gets the attribute value for COMPANY_CONTACT_TYPE_ID_NO using the alias name CompanyContactTypeIdNo.
     * @return the COMPANY_CONTACT_TYPE_ID_NO
     */
    public Integer getCompanyContactTypeIdNo() {
        return (Integer) getAttributeInternal(COMPANYCONTACTTYPEIDNO);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_CONTACT_TYPE_ID_NO using the alias name CompanyContactTypeIdNo.
     * @param value value to set the COMPANY_CONTACT_TYPE_ID_NO
     */
    public void setCompanyContactTypeIdNo(Integer value) {
        setAttributeInternal(COMPANYCONTACTTYPEIDNO, value);
    }

    /**
     * Gets the attribute value for COMPANY_ID_NO using the alias name CompanyIdNo.
     * @return the COMPANY_ID_NO
     */
    public Integer getCompanyIdNo() {
        return (Integer) getAttributeInternal(COMPANYIDNO);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_ID_NO using the alias name CompanyIdNo.
     * @param value value to set the COMPANY_ID_NO
     */
    public void setCompanyIdNo(Integer value) {
        setAttributeInternal(COMPANYIDNO, value);
    }

    /**
     * Gets the attribute value for CONTACT_CELLPHONE_NO using the alias name ContactCellphoneNo.
     * @return the CONTACT_CELLPHONE_NO
     */
    public String getContactCellphoneNo() {
        return (String) getAttributeInternal(CONTACTCELLPHONENO);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTACT_CELLPHONE_NO using the alias name ContactCellphoneNo.
     * @param value value to set the CONTACT_CELLPHONE_NO
     */
    public void setContactCellphoneNo(String value) {
        setAttributeInternal(CONTACTCELLPHONENO, value);
    }

    /**
     * Gets the attribute value for CONTACT_DESC using the alias name ContactDesc.
     * @return the CONTACT_DESC
     */
    public String getContactDesc() {
        return (String) getAttributeInternal(CONTACTDESC);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTACT_DESC using the alias name ContactDesc.
     * @param value value to set the CONTACT_DESC
     */
    public void setContactDesc(String value) {
        setAttributeInternal(CONTACTDESC, value);
    }

    /**
     * Gets the attribute value for CONTACT_EMAIL using the alias name ContactEmail.
     * @return the CONTACT_EMAIL
     */
    public String getContactEmail() {
        return (String) getAttributeInternal(CONTACTEMAIL);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTACT_EMAIL using the alias name ContactEmail.
     * @param value value to set the CONTACT_EMAIL
     */
    public void setContactEmail(String value) {
        setAttributeInternal(CONTACTEMAIL, value);
    }

    /**
     * Gets the attribute value for CONTACT_FAX_NO using the alias name ContactFaxNo.
     * @return the CONTACT_FAX_NO
     */
    public String getContactFaxNo() {
        return (String) getAttributeInternal(CONTACTFAXNO);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTACT_FAX_NO using the alias name ContactFaxNo.
     * @param value value to set the CONTACT_FAX_NO
     */
    public void setContactFaxNo(String value) {
        setAttributeInternal(CONTACTFAXNO, value);
    }

    /**
     * Gets the attribute value for CONTACT_NAME using the alias name ContactName.
     * @return the CONTACT_NAME
     */
    public String getContactName() {
        return (String) getAttributeInternal(CONTACTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTACT_NAME using the alias name ContactName.
     * @param value value to set the CONTACT_NAME
     */
    public void setContactName(String value) {
        setAttributeInternal(CONTACTNAME, value);
    }

    /**
     * Gets the attribute value for CONTACT_TELEPHONE_NO using the alias name ContactTelephoneNo.
     * @return the CONTACT_TELEPHONE_NO
     */
    public String getContactTelephoneNo() {
        return (String) getAttributeInternal(CONTACTTELEPHONENO);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTACT_TELEPHONE_NO using the alias name ContactTelephoneNo.
     * @param value value to set the CONTACT_TELEPHONE_NO
     */
    public void setContactTelephoneNo(String value) {
        setAttributeInternal(CONTACTTELEPHONENO, value);
    }

    /**
     * Gets the attribute value for COUNTRY_CODE using the alias name CountryCode.
     * @return the COUNTRY_CODE
     */
    public String getCountryCode() {
        return (String) getAttributeInternal(COUNTRYCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for COUNTRY_CODE using the alias name CountryCode.
     * @param value value to set the COUNTRY_CODE
     */
    public void setCountryCode(String value) {
        setAttributeInternal(COUNTRYCODE, value);
    }

    /**
     * Gets the attribute value for EFFECTIVE_END_DATE using the alias name EffectiveEndDate.
     * @return the EFFECTIVE_END_DATE
     */
    public Date getEffectiveEndDate() {
        return (Date) getAttributeInternal(EFFECTIVEENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EFFECTIVE_END_DATE using the alias name EffectiveEndDate.
     * @param value value to set the EFFECTIVE_END_DATE
     */
    public void setEffectiveEndDate(Date value) {
        setAttributeInternal(EFFECTIVEENDDATE, value);
    }

    /**
     * Gets the attribute value for EFFECTIVE_START_DATE using the alias name EffectiveStartDate.
     * @return the EFFECTIVE_START_DATE
     */
    public Date getEffectiveStartDate() {
        return (Date) getAttributeInternal(EFFECTIVESTARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EFFECTIVE_START_DATE using the alias name EffectiveStartDate.
     * @param value value to set the EFFECTIVE_START_DATE
     */
    public void setEffectiveStartDate(Date value) {
        setAttributeInternal(EFFECTIVESTARTDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATETIME using the alias name LastUpdateDatetime.
     * @return the LAST_UPDATE_DATETIME
     */
    public Timestamp getLastUpdateDatetime() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATETIME);
    }

    /**
     * Gets the attribute value for USERNAME using the alias name Username.
     * @return the USERNAME
     */
    public String getUsername() {
        return (String) getAttributeInternal(USERNAME);
    }
}

