@../../../../plsql/triggers/lhhcom/ACCREDITATION_TYPE_AUD_BEF_TRG.sql;
@../../../../plsql/triggers/lhhcom/ADDRESS_TYPE_AUDIT_BEFORE_TRG.sql; 
@../../../../plsql/triggers/lhhcom/BROKER_ACCREDITAT_AUD_BEF_TRG.sql;
@../../../../plsql/triggers/lhhcom/BROKER_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/BROKER_FUNCTION_AUDIT_BEF_TRG.sql;
@../../../../plsql/triggers/lhhcom/BROKER_TABLE_AUDIT_TRG.sql; 
@../../../../plsql/triggers/lhhcom/BROKER_TABLE_TYPE_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/COMPANY_ACCREDITAT_AUD_BEF_TRG.sql;
@../../../../plsql/triggers/lhhcom/COMPANY_ADDRESS_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/COMPANY_CONTACT_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/COMPANY_CONTACT_BEFORE_TRG.sql;
@../../../../plsql/triggers/lhhcom/COMPANY_COUNTRY_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/COMPANY_FEE_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/COMPANY_FEE_TYPE_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/COMPANY_FUNCTION_AUDIT_BEF_TRG.sql;
@../../../../plsql/triggers/lhhcom/COMPANY_REG_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/COMPANY_TABLE_AUDIT_TRG.sql; 
@../../../../plsql/triggers/lhhcom/COMPANY_TABLE_TYPE_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/INVOICE_AUDIT_BEF_TRG.sql;
@../../../../plsql/triggers/lhhcom/INVOICE_DETAIL_AUDIT_BEF_TRG.sql;
@../../../../plsql/triggers/lhhcom/OHI_COMM_PERC_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/OHI_ENRLMNT_PRDCTS_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/OHI_GROUPS_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/OHI_HOLD_IND_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/OHI_INSURED_ENTITIES_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/OHI_POLICIES_AUDIT_TRG.sql; 
@../../../../plsql/triggers/lhhcom/OHI_POLICYHOLDERS_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/OHI_POLICY_BROKERS_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/OHI_POLICY_GROUPS_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/OHI_POL_ENRLMNTS_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/OHI_PRODUCTS_AUDIT_TRG.sql;

alter table ACCREDITATION_TYPE_AUDIT modify TRANSACTION_DESC VARCHAR2(550);
alter table ADDRESS_TYPE_AUDIT modify TRANSACTION_DESC VARCHAR2(550);
alter table BROKER_ACCREDITATION_AUDIT modify TRANSACTION_DESC VARCHAR2(550);
alter table BROKER_AUDIT modify TRANSACTION_DESC VARCHAR2(550);
alter table BROKER_FUNCTION_AUDIT modify TRANSACTION_DESC VARCHAR2(550);
alter table BROKER_TABLE_AUDIT modify TRANSACTION_DESC VARCHAR2(550);
alter table BROKER_TABLE_TYPE_AUDIT modify TRANSACTION_DESC VARCHAR2(550);
alter table COMPANY_ACCREDITATION_AUDIT modify TRANSACTION_DESC VARCHAR2(550);
alter table COMPANY_ADDRESS_AUDIT modify TRANSACTION_DESC VARCHAR2(550);
alter table COMPANY_AUDIT modify TRANSACTION_DESC VARCHAR2(550);
alter table COMPANY_CONTACT_AUDIT modify TRANSACTION_DESC VARCHAR2(550);
alter table COMPANY_CONTACT_TYPE_AUDIT modify TRANSACTION_DESC VARCHAR2(550);
alter table COMPANY_COUNTRY_AUDIT modify TRANSACTION_DESC VARCHAR2(550);
alter table COMPANY_FEE_AUDIT modify TRANSACTION_DESC VARCHAR2(550);
alter table COMPANY_FEE_TYPE_AUDIT modify TRANSACTION_DESC VARCHAR2(550);
alter table COMPANY_FUNCTION_AUDIT modify TRANSACTION_DESC VARCHAR2(550);
alter table COMPANY_REG_AUDIT modify TRANSACTION_DESC VARCHAR2(550);
alter table COMPANY_TABLE_AUDIT modify TRANSACTION_DESC VARCHAR2(550);
alter table COMPANY_TABLE_TYPE_AUDIT modify TRANSACTION_DESC VARCHAR2(550);
alter table INVOICE_AUDIT modify TRANSACTION_DESC VARCHAR2(550);
alter table INVOICE_DETAIL_AUDIT modify TRANSACTION_DESC VARCHAR2(550);
alter table OHI_COMM_PERC_AUDIT modify TRANSACTION_DESC VARCHAR2(550);
alter table OHI_ENROLLMENT_PRODUCTS_AUDIT modify TRANSACTION_DESC VARCHAR2(550);
alter table OHI_GROUPS_AUDIT modify TRANSACTION_DESC VARCHAR2(550);
alter table OHI_HOLD_IND_AUDIT modify TRANSACTION_DESC VARCHAR2(550);
alter table OHI_INSURED_ENTITIES_AUDIT modify TRANSACTION_DESC VARCHAR2(550);
alter table OHI_POLICIES_AUDIT modify TRANSACTION_DESC VARCHAR2(550);
alter table OHI_POLICYHOLDERS_AUDIT modify TRANSACTION_DESC VARCHAR2(550);
alter table OHI_POLICY_BROKERS_AUDIT modify TRANSACTION_DESC VARCHAR2(550);
alter table OHI_POLICY_ENROLLMENTS_AUDIT modify TRANSACTION_DESC VARCHAR2(550);
alter table OHI_POLICY_GROUPS_AUDIT modify TRANSACTION_DESC VARCHAR2(550);
alter table OHI_PRODUCTS_AUDIT modify TRANSACTION_DESC VARCHAR2(550);