package com.liberty.health.comms.model.payment.services.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 15 11:05:08 CAT 2017
// ---------------------------------------------------------------------
public interface PaymentAM extends ApplicationModule {
    String executePaymentRun(Integer invoiceNo, Integer companyIdNo, String countryCode, String username);


    void submitFusionPayablesRecon(String fromDate, String toDate);
}

