package com.liberty.health.comms.model.comms.views;

import com.core.model.vo.classes.CoreViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 27 13:47:54 CAT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CommsDMInvoiceNoUpdateVOImpl extends CoreViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CommsDMInvoiceNoUpdateVOImpl() {
    }
}

