package com.liberty.health.comms.model.comms.views;

import com.core.model.vo.classes.CoreViewRowImpl;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jan 24 07:52:35 CAT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CommsPaymentsArchivedVORowImpl extends CoreViewRowImpl {


    public static final int ENTITY_COMMSPAYMENTSRECEIVEDEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ParentgroupCode,
        ApplicationId,
        CommsCalcSnapshotNo,
        ContributionDate,
        CountryCode,
        CurrencyCode,
        ExchangeRate,
        FinanceInvoiceDate,
        FinanceInvoiceNo,
        FinanceReceiptAmt,
        FinanceReceiptDate,
        FinanceReceiptNo,
        GroupCode,
        LastUpdateDatetime,
        PaymentType,
        PersonCode,
        PolicyCode,
        ProcessedDesc,
        ProcessedInd,
        ProductCode,
        Username,
        PremiumPayRemoveArchiveLov1,
        CountryLovView_N1,
        OhiGroupLovView_P1,
        OhiProductLovView_P1,
        OhiParentGroupLovView1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return CommsPaymentsArchivedVORowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return CommsPaymentsArchivedVORowImpl.AttributesEnum.firstIndex() + CommsPaymentsArchivedVORowImpl.AttributesEnum
                                                                                                              .staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = CommsPaymentsArchivedVORowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PARENTGROUPCODE = AttributesEnum.ParentgroupCode.index();
    public static final int APPLICATIONID = AttributesEnum.ApplicationId.index();
    public static final int COMMSCALCSNAPSHOTNO = AttributesEnum.CommsCalcSnapshotNo.index();
    public static final int CONTRIBUTIONDATE = AttributesEnum.ContributionDate.index();
    public static final int COUNTRYCODE = AttributesEnum.CountryCode.index();
    public static final int CURRENCYCODE = AttributesEnum.CurrencyCode.index();
    public static final int EXCHANGERATE = AttributesEnum.ExchangeRate.index();
    public static final int FINANCEINVOICEDATE = AttributesEnum.FinanceInvoiceDate.index();
    public static final int FINANCEINVOICENO = AttributesEnum.FinanceInvoiceNo.index();
    public static final int FINANCERECEIPTAMT = AttributesEnum.FinanceReceiptAmt.index();
    public static final int FINANCERECEIPTDATE = AttributesEnum.FinanceReceiptDate.index();
    public static final int FINANCERECEIPTNO = AttributesEnum.FinanceReceiptNo.index();
    public static final int GROUPCODE = AttributesEnum.GroupCode.index();
    public static final int LASTUPDATEDATETIME = AttributesEnum.LastUpdateDatetime.index();
    public static final int PAYMENTTYPE = AttributesEnum.PaymentType.index();
    public static final int PERSONCODE = AttributesEnum.PersonCode.index();
    public static final int POLICYCODE = AttributesEnum.PolicyCode.index();
    public static final int PROCESSEDDESC = AttributesEnum.ProcessedDesc.index();
    public static final int PROCESSEDIND = AttributesEnum.ProcessedInd.index();
    public static final int PRODUCTCODE = AttributesEnum.ProductCode.index();
    public static final int USERNAME = AttributesEnum.Username.index();
    public static final int PREMIUMPAYREMOVEARCHIVELOV1 = AttributesEnum.PremiumPayRemoveArchiveLov1.index();
    public static final int COUNTRYLOVVIEW_N1 = AttributesEnum.CountryLovView_N1.index();
    public static final int OHIGROUPLOVVIEW_P1 = AttributesEnum.OhiGroupLovView_P1.index();
    public static final int OHIPRODUCTLOVVIEW_P1 = AttributesEnum.OhiProductLovView_P1.index();
    public static final int OHIPARENTGROUPLOVVIEW1 = AttributesEnum.OhiParentGroupLovView1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CommsPaymentsArchivedVORowImpl() {
    }

    /**
     * Gets CommsPaymentsReceivedEO entity object.
     * @return the CommsPaymentsReceivedEO
     */
    public EntityImpl getCommsPaymentsReceivedEO() {
        return (EntityImpl) getEntity(ENTITY_COMMSPAYMENTSRECEIVEDEO);
    }

    /**
     * Gets the attribute value for the calculated attribute ParentgroupCode.
     * @return the ParentgroupCode
     */
    public String getParentgroupCode() {
        return (String) getAttributeInternal(PARENTGROUPCODE);
    }

    /**
     * Gets the attribute value for APPLICATION_ID using the alias name ApplicationId.
     * @return the APPLICATION_ID
     */
    public Number getApplicationId() {
        return (Number) getAttributeInternal(APPLICATIONID);
    }

    /**
     * Gets the attribute value for COMMS_CALC_SNAPSHOT_NO using the alias name CommsCalcSnapshotNo.
     * @return the COMMS_CALC_SNAPSHOT_NO
     */
    public Number getCommsCalcSnapshotNo() {
        return (Number) getAttributeInternal(COMMSCALCSNAPSHOTNO);
    }

    /**
     * Gets the attribute value for CONTRIBUTION_DATE using the alias name ContributionDate.
     * @return the CONTRIBUTION_DATE
     */
    public Date getContributionDate() {
        return (Date) getAttributeInternal(CONTRIBUTIONDATE);
    }

    /**
     * Gets the attribute value for COUNTRY_CODE using the alias name CountryCode.
     * @return the COUNTRY_CODE
     */
    public String getCountryCode() {
        return (String) getAttributeInternal(COUNTRYCODE);
    }

    /**
     * Gets the attribute value for CURRENCY_CODE using the alias name CurrencyCode.
     * @return the CURRENCY_CODE
     */
    public String getCurrencyCode() {
        return (String) getAttributeInternal(CURRENCYCODE);
    }

    /**
     * Gets the attribute value for EXCHANGE_RATE using the alias name ExchangeRate.
     * @return the EXCHANGE_RATE
     */
    public Number getExchangeRate() {
        return (Number) getAttributeInternal(EXCHANGERATE);
    }

    /**
     * Gets the attribute value for FINANCE_INVOICE_DATE using the alias name FinanceInvoiceDate.
     * @return the FINANCE_INVOICE_DATE
     */
    public Date getFinanceInvoiceDate() {
        return (Date) getAttributeInternal(FINANCEINVOICEDATE);
    }

    /**
     * Gets the attribute value for FINANCE_INVOICE_NO using the alias name FinanceInvoiceNo.
     * @return the FINANCE_INVOICE_NO
     */
    public String getFinanceInvoiceNo() {
        return (String) getAttributeInternal(FINANCEINVOICENO);
    }

    /**
     * Gets the attribute value for FINANCE_RECEIPT_AMT using the alias name FinanceReceiptAmt.
     * @return the FINANCE_RECEIPT_AMT
     */
    public Number getFinanceReceiptAmt() {
        return (Number) getAttributeInternal(FINANCERECEIPTAMT);
    }

    /**
     * Gets the attribute value for FINANCE_RECEIPT_DATE using the alias name FinanceReceiptDate.
     * @return the FINANCE_RECEIPT_DATE
     */
    public Date getFinanceReceiptDate() {
        return (Date) getAttributeInternal(FINANCERECEIPTDATE);
    }

    /**
     * Gets the attribute value for FINANCE_RECEIPT_NO using the alias name FinanceReceiptNo.
     * @return the FINANCE_RECEIPT_NO
     */
    public String getFinanceReceiptNo() {
        return (String) getAttributeInternal(FINANCERECEIPTNO);
    }

    /**
     * Gets the attribute value for GROUP_CODE using the alias name GroupCode.
     * @return the GROUP_CODE
     */
    public String getGroupCode() {
        return (String) getAttributeInternal(GROUPCODE);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATETIME using the alias name LastUpdateDatetime.
     * @return the LAST_UPDATE_DATETIME
     */
    public Date getLastUpdateDatetime() {
        return (Date) getAttributeInternal(LASTUPDATEDATETIME);
    }

    /**
     * Gets the attribute value for PAYMENT_TYPE using the alias name PaymentType.
     * @return the PAYMENT_TYPE
     */
    public String getPaymentType() {
        return (String) getAttributeInternal(PAYMENTTYPE);
    }

    /**
     * Gets the attribute value for PERSON_CODE using the alias name PersonCode.
     * @return the PERSON_CODE
     */
    public String getPersonCode() {
        return (String) getAttributeInternal(PERSONCODE);
    }


    /**
     * Gets the attribute value for POLICY_CODE using the alias name PolicyCode.
     * @return the POLICY_CODE
     */
    public String getPolicyCode() {
        return (String) getAttributeInternal(POLICYCODE);
    }

    /**
     * Gets the attribute value for PROCESSED_DESC using the alias name ProcessedDesc.
     * @return the PROCESSED_DESC
     */
    public String getProcessedDesc() {
        return (String) getAttributeInternal(PROCESSEDDESC);
    }

    /**
     * Gets the attribute value for PROCESSED_IND using the alias name ProcessedInd.
     * @return the PROCESSED_IND
     */
    public String getProcessedInd() {
        return (String) getAttributeInternal(PROCESSEDIND);
    }

    /**
     * Sets <code>value</code> as attribute value for PROCESSED_IND using the alias name ProcessedInd.
     * @param value value to set the PROCESSED_IND
     */
    public void setProcessedInd(String value) {
        setAttributeInternal(PROCESSEDIND, value);
    }

    /**
     * Gets the attribute value for PRODUCT_CODE using the alias name ProductCode.
     * @return the PRODUCT_CODE
     */
    public String getProductCode() {
        return (String) getAttributeInternal(PRODUCTCODE);
    }

    /**
     * Gets the attribute value for USERNAME using the alias name Username.
     * @return the USERNAME
     */
    public String getUsername() {
        return (String) getAttributeInternal(USERNAME);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PremiumPayRemoveArchiveLov1.
     */
    public RowSet getPremiumPayRemoveArchiveLov1() {
        return (RowSet) getAttributeInternal(PREMIUMPAYREMOVEARCHIVELOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CountryLovView_N1.
     */
    public RowSet getCountryLovView_N1() {
        return (RowSet) getAttributeInternal(COUNTRYLOVVIEW_N1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> OhiGroupLovView_P1.
     */
    public RowSet getOhiGroupLovView_P1() {
        return (RowSet) getAttributeInternal(OHIGROUPLOVVIEW_P1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> OhiProductLovView_P1.
     */
    public RowSet getOhiProductLovView_P1() {
        return (RowSet) getAttributeInternal(OHIPRODUCTLOVVIEW_P1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> OhiParentGroupLovView1.
     */
    public RowSet getOhiParentGroupLovView1() {
        return (RowSet) getAttributeInternal(OHIPARENTGROUPLOVVIEW1);
    }


}

