package com.liberty.health.comms.model.comms.views;

import com.core.model.vo.classes.CoreViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 10 12:39:51 CAT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CommsDMSnapshotHistoryVORowImpl extends CoreViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        CalculationDatetime,
        CountryCode,
        CompanyIdNo,
        GroupCode,
        ProductCode,
        CommsCalcTypeCode,
        PaymentCurrency,
        PaymentReceiveAmt,
        CommsCalculatedAmt,
        ExchangeRateCurrencyCode,
        ExchangeRate,
        CommsCalculatedExchAmt,
        Bu;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CALCULATIONDATETIME = AttributesEnum.CalculationDatetime.index();
    public static final int COUNTRYCODE = AttributesEnum.CountryCode.index();
    public static final int COMPANYIDNO = AttributesEnum.CompanyIdNo.index();
    public static final int GROUPCODE = AttributesEnum.GroupCode.index();
    public static final int PRODUCTCODE = AttributesEnum.ProductCode.index();
    public static final int COMMSCALCTYPECODE = AttributesEnum.CommsCalcTypeCode.index();
    public static final int PAYMENTCURRENCY = AttributesEnum.PaymentCurrency.index();
    public static final int PAYMENTRECEIVEAMT = AttributesEnum.PaymentReceiveAmt.index();
    public static final int COMMSCALCULATEDAMT = AttributesEnum.CommsCalculatedAmt.index();
    public static final int EXCHANGERATECURRENCYCODE = AttributesEnum.ExchangeRateCurrencyCode.index();
    public static final int EXCHANGERATE = AttributesEnum.ExchangeRate.index();
    public static final int COMMSCALCULATEDEXCHAMT = AttributesEnum.CommsCalculatedExchAmt.index();
    public static final int BU = AttributesEnum.Bu.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CommsDMSnapshotHistoryVORowImpl() {
    }


    /**
     * Gets the attribute value for the calculated attribute CountryCode.
     * @return the CountryCode
     */
    public String getCountryCode() {
        return (String) getAttributeInternal(COUNTRYCODE);
    }

    /**
     * Gets the attribute value for the calculated attribute ProductCode.
     * @return the ProductCode
     */
    public String getProductCode() {
        return (String) getAttributeInternal(PRODUCTCODE);
    }


    /**
     * Gets the attribute value for the calculated attribute GroupCode.
     * @return the GroupCode
     */
    public String getGroupCode() {
        return (String) getAttributeInternal(GROUPCODE);
    }


    /**
     * Gets the attribute value for the calculated attribute CompanyIdNo.
     * @return the CompanyIdNo
     */
    public Number getCompanyIdNo() {
        return (Number) getAttributeInternal(COMPANYIDNO);
    }


    /**
     * Gets the attribute value for the calculated attribute CalculationDatetime.
     * @return the CalculationDatetime
     */
    public Date getCalculationDatetime() {
        return (Date) getAttributeInternal(CALCULATIONDATETIME);
    }

    /**
     * Gets the attribute value for the calculated attribute CommsCalcTypeCode.
     * @return the CommsCalcTypeCode
     */
    public String getCommsCalcTypeCode() {
        return (String) getAttributeInternal(COMMSCALCTYPECODE);
    }

    /**
     * Gets the attribute value for the calculated attribute PaymentReceiveAmt.
     * @return the PaymentReceiveAmt
     */
    public Number getPaymentReceiveAmt() {
        return (Number) getAttributeInternal(PAYMENTRECEIVEAMT);
    }

    /**
     * Gets the attribute value for the calculated attribute PaymentCurrency.
     * @return the PaymentCurrency
     */
    public String getPaymentCurrency() {
        return (String) getAttributeInternal(PAYMENTCURRENCY);
    }

    /**
     * Gets the attribute value for the calculated attribute CommsCalculatedAmt.
     * @return the CommsCalculatedAmt
     */
    public Number getCommsCalculatedAmt() {
        return (Number) getAttributeInternal(COMMSCALCULATEDAMT);
    }

    /**
     * Gets the attribute value for the calculated attribute ExchangeRate.
     * @return the ExchangeRate
     */
    public Number getExchangeRate() {
        return (Number) getAttributeInternal(EXCHANGERATE);
    }

    /**
     * Gets the attribute value for the calculated attribute ExchangeRateCurrencyCode.
     * @return the ExchangeRateCurrencyCode
     */
    public String getExchangeRateCurrencyCode() {
        return (String) getAttributeInternal(EXCHANGERATECURRENCYCODE);
    }

    /**
     * Gets the attribute value for the calculated attribute CommsCalculatedExchAmt.
     * @return the CommsCalculatedExchAmt
     */
    public Number getCommsCalculatedExchAmt() {
        return (Number) getAttributeInternal(COMMSCALCULATEDEXCHAMT);
    }


    /**
     * Gets the attribute value for the calculated attribute Bu.
     * @return the Bu
     */
    public String getBu() {
        return (String) getAttributeInternal(BU);
    }
}

