package com.liberty.health.comms.model.comms.views;

import com.core.model.vo.classes.CoreViewRowImpl;

import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 26 12:34:20 CAT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CommsDMJobSubmitRowImpl extends CoreViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        FromDate,
        Country,
        Scheme,
        Stage,
        MedwareSchemes1,
        CountryLovView1,
        CommDMStagesLovView1,
        CountryLovView_N1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int FROMDATE = AttributesEnum.FromDate.index();
    public static final int COUNTRY = AttributesEnum.Country.index();
    public static final int SCHEME = AttributesEnum.Scheme.index();
    public static final int STAGE = AttributesEnum.Stage.index();
    public static final int MEDWARESCHEMES1 = AttributesEnum.MedwareSchemes1.index();
    public static final int COUNTRYLOVVIEW1 = AttributesEnum.CountryLovView1.index();
    public static final int COMMDMSTAGESLOVVIEW1 = AttributesEnum.CommDMStagesLovView1.index();
    public static final int COUNTRYLOVVIEW_N1 = AttributesEnum.CountryLovView_N1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CommsDMJobSubmitRowImpl() {
    }
}

