package com.liberty.health.comms.model.comms.views;

import com.core.model.vo.classes.CoreViewRowImpl;

import com.liberty.health.comms.model.eo.CommsCalcSnapshotDmEOImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 10 06:10:48 CAT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CommsDMSnapshotVORowImpl extends CoreViewRowImpl {


    public static final int ENTITY_COMMSCALCSNAPSHOTDMEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        BrokerIdNo,
        CalculationDatetime,
        CommsCalcSnapshotNo,
        CommsCalcTypeCode,
        CommsCalculatedAmt,
        CommsCalculatedExchAmt,
        CommsPerc,
        CompanyIdNo,
        ContributionDate,
        CountryCode,
        ExchangeRate,
        ExchangeRateCurrencyCode,
        FinanceReceiptNo,
        GroupCode,
        InvoiceNo,
        LastUpdateDatetime,
        PaymentCurrency,
        PaymentReceiveAmt,
        PaymentReceiveDate,
        PersonCode,
        PoepId,
        PolicyCode,
        ProductCode,
        Username;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return com.liberty
                      .health
                      .comms
                      .model
                      .comms
                      .views
                      .CommsDMSnapshotVORowImpl
                      .AttributesEnum
                      .firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return com.liberty
                      .health
                      .comms
                      .model
                      .comms
                      .views
                      .CommsDMSnapshotVORowImpl
                      .AttributesEnum
                      .firstIndex() + com.liberty
                                         .health
                                         .comms
                                         .model
                                         .comms
                                         .views
                                         .CommsDMSnapshotVORowImpl
                                         .AttributesEnum
                                         .staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = com.liberty
                          .health
                          .comms
                          .model
                          .comms
                          .views
                          .CommsDMSnapshotVORowImpl
                          .AttributesEnum
                          .values();
            }
            return vals;
        }
    }


    public static final int BROKERIDNO = AttributesEnum.BrokerIdNo.index();
    public static final int CALCULATIONDATETIME = AttributesEnum.CalculationDatetime.index();
    public static final int COMMSCALCSNAPSHOTNO = AttributesEnum.CommsCalcSnapshotNo.index();
    public static final int COMMSCALCTYPECODE = AttributesEnum.CommsCalcTypeCode.index();
    public static final int COMMSCALCULATEDAMT = AttributesEnum.CommsCalculatedAmt.index();
    public static final int COMMSCALCULATEDEXCHAMT = AttributesEnum.CommsCalculatedExchAmt.index();
    public static final int COMMSPERC = AttributesEnum.CommsPerc.index();
    public static final int COMPANYIDNO = AttributesEnum.CompanyIdNo.index();
    public static final int CONTRIBUTIONDATE = AttributesEnum.ContributionDate.index();
    public static final int COUNTRYCODE = AttributesEnum.CountryCode.index();
    public static final int EXCHANGERATE = AttributesEnum.ExchangeRate.index();
    public static final int EXCHANGERATECURRENCYCODE = AttributesEnum.ExchangeRateCurrencyCode.index();
    public static final int FINANCERECEIPTNO = AttributesEnum.FinanceReceiptNo.index();
    public static final int GROUPCODE = AttributesEnum.GroupCode.index();
    public static final int INVOICENO = AttributesEnum.InvoiceNo.index();
    public static final int LASTUPDATEDATETIME = AttributesEnum.LastUpdateDatetime.index();
    public static final int PAYMENTCURRENCY = AttributesEnum.PaymentCurrency.index();
    public static final int PAYMENTRECEIVEAMT = AttributesEnum.PaymentReceiveAmt.index();
    public static final int PAYMENTRECEIVEDATE = AttributesEnum.PaymentReceiveDate.index();
    public static final int PERSONCODE = AttributesEnum.PersonCode.index();
    public static final int POEPID = AttributesEnum.PoepId.index();
    public static final int POLICYCODE = AttributesEnum.PolicyCode.index();
    public static final int PRODUCTCODE = AttributesEnum.ProductCode.index();
    public static final int USERNAME = AttributesEnum.Username.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CommsDMSnapshotVORowImpl() {
    }

    /**
     * Gets CommsCalcSnapshotDmEO entity object.
     * @return the CommsCalcSnapshotDmEO
     */
    public CommsCalcSnapshotDmEOImpl getCommsCalcSnapshotDmEO() {
        return (CommsCalcSnapshotDmEOImpl) getEntity(ENTITY_COMMSCALCSNAPSHOTDMEO);
    }

    /**
     * Gets the attribute value for BROKER_ID_NO using the alias name BrokerIdNo.
     * @return the BROKER_ID_NO
     */
    public Number getBrokerIdNo() {
        return (Number) getAttributeInternal(BROKERIDNO);
    }


    /**
     * Gets the attribute value for CALCULATION_DATETIME using the alias name CalculationDatetime.
     * @return the CALCULATION_DATETIME
     */
    public Date getCalculationDatetime() {
        return (Date) getAttributeInternal(CALCULATIONDATETIME);
    }


    /**
     * Gets the attribute value for COMMS_CALC_SNAPSHOT_NO using the alias name CommsCalcSnapshotNo.
     * @return the COMMS_CALC_SNAPSHOT_NO
     */
    public Number getCommsCalcSnapshotNo() {
        return (Number) getAttributeInternal(COMMSCALCSNAPSHOTNO);
    }


    /**
     * Gets the attribute value for COMMS_CALC_TYPE_CODE using the alias name CommsCalcTypeCode.
     * @return the COMMS_CALC_TYPE_CODE
     */
    public String getCommsCalcTypeCode() {
        return (String) getAttributeInternal(COMMSCALCTYPECODE);
    }


    /**
     * Gets the attribute value for COMMS_CALCULATED_AMT using the alias name CommsCalculatedAmt.
     * @return the COMMS_CALCULATED_AMT
     */
    public Number getCommsCalculatedAmt() {
        return (Number) getAttributeInternal(COMMSCALCULATEDAMT);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMS_CALCULATED_AMT using the alias name CommsCalculatedAmt.
     * @param value value to set the COMMS_CALCULATED_AMT
     */
    public void setCommsCalculatedAmt(Number value) {
        setAttributeInternal(COMMSCALCULATEDAMT, value);
    }

    /**
     * Gets the attribute value for COMMS_CALCULATED_EXCH_AMT using the alias name CommsCalculatedExchAmt.
     * @return the COMMS_CALCULATED_EXCH_AMT
     */
    public Number getCommsCalculatedExchAmt() {
        return (Number) getAttributeInternal(COMMSCALCULATEDEXCHAMT);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMS_CALCULATED_EXCH_AMT using the alias name CommsCalculatedExchAmt.
     * @param value value to set the COMMS_CALCULATED_EXCH_AMT
     */
    public void setCommsCalculatedExchAmt(Number value) {
        setAttributeInternal(COMMSCALCULATEDEXCHAMT, value);
    }

    /**
     * Gets the attribute value for COMMS_PERC using the alias name CommsPerc.
     * @return the COMMS_PERC
     */
    public Number getCommsPerc() {
        return (Number) getAttributeInternal(COMMSPERC);
    }


    /**
     * Gets the attribute value for COMPANY_ID_NO using the alias name CompanyIdNo.
     * @return the COMPANY_ID_NO
     */
    public Number getCompanyIdNo() {
        return (Number) getAttributeInternal(COMPANYIDNO);
    }


    /**
     * Gets the attribute value for CONTRIBUTION_DATE using the alias name ContributionDate.
     * @return the CONTRIBUTION_DATE
     */
    public Date getContributionDate() {
        return (Date) getAttributeInternal(CONTRIBUTIONDATE);
    }


    /**
     * Gets the attribute value for COUNTRY_CODE using the alias name CountryCode.
     * @return the COUNTRY_CODE
     */
    public String getCountryCode() {
        return (String) getAttributeInternal(COUNTRYCODE);
    }


    /**
     * Gets the attribute value for EXCHANGE_RATE using the alias name ExchangeRate.
     * @return the EXCHANGE_RATE
     */
    public Number getExchangeRate() {
        return (Number) getAttributeInternal(EXCHANGERATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EXCHANGE_RATE using the alias name ExchangeRate.
     * @param value value to set the EXCHANGE_RATE
     */
    public void setExchangeRate(Number value) {
        setAttributeInternal(EXCHANGERATE, value);
    }

    /**
     * Gets the attribute value for EXCHANGE_RATE_CURRENCY_CODE using the alias name ExchangeRateCurrencyCode.
     * @return the EXCHANGE_RATE_CURRENCY_CODE
     */
    public String getExchangeRateCurrencyCode() {
        return (String) getAttributeInternal(EXCHANGERATECURRENCYCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for EXCHANGE_RATE_CURRENCY_CODE using the alias name ExchangeRateCurrencyCode.
     * @param value value to set the EXCHANGE_RATE_CURRENCY_CODE
     */
    public void setExchangeRateCurrencyCode(String value) {
        setAttributeInternal(EXCHANGERATECURRENCYCODE, value);
    }

    /**
     * Gets the attribute value for FINANCE_RECEIPT_NO using the alias name FinanceReceiptNo.
     * @return the FINANCE_RECEIPT_NO
     */
    public String getFinanceReceiptNo() {
        return (String) getAttributeInternal(FINANCERECEIPTNO);
    }


    /**
     * Gets the attribute value for GROUP_CODE using the alias name GroupCode.
     * @return the GROUP_CODE
     */
    public String getGroupCode() {
        return (String) getAttributeInternal(GROUPCODE);
    }


    /**
     * Gets the attribute value for INVOICE_NO using the alias name InvoiceNo.
     * @return the INVOICE_NO
     */
    public Number getInvoiceNo() {
        return (Number) getAttributeInternal(INVOICENO);
    }


    /**
     * Gets the attribute value for LAST_UPDATE_DATETIME using the alias name LastUpdateDatetime.
     * @return the LAST_UPDATE_DATETIME
     */
    public Date getLastUpdateDatetime() {
        return (Date) getAttributeInternal(LASTUPDATEDATETIME);
    }


    /**
     * Gets the attribute value for PAYMENT_CURRENCY using the alias name PaymentCurrency.
     * @return the PAYMENT_CURRENCY
     */
    public String getPaymentCurrency() {
        return (String) getAttributeInternal(PAYMENTCURRENCY);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYMENT_CURRENCY using the alias name PaymentCurrency.
     * @param value value to set the PAYMENT_CURRENCY
     */
    public void setPaymentCurrency(String value) {
        setAttributeInternal(PAYMENTCURRENCY, value);
    }

    /**
     * Gets the attribute value for PAYMENT_RECEIVE_AMT using the alias name PaymentReceiveAmt.
     * @return the PAYMENT_RECEIVE_AMT
     */
    public Number getPaymentReceiveAmt() {
        return (Number) getAttributeInternal(PAYMENTRECEIVEAMT);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYMENT_RECEIVE_AMT using the alias name PaymentReceiveAmt.
     * @param value value to set the PAYMENT_RECEIVE_AMT
     */
    public void setPaymentReceiveAmt(Number value) {
        setAttributeInternal(PAYMENTRECEIVEAMT, value);
    }

    /**
     * Gets the attribute value for PAYMENT_RECEIVE_DATE using the alias name PaymentReceiveDate.
     * @return the PAYMENT_RECEIVE_DATE
     */
    public Date getPaymentReceiveDate() {
        return (Date) getAttributeInternal(PAYMENTRECEIVEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYMENT_RECEIVE_DATE using the alias name PaymentReceiveDate.
     * @param value value to set the PAYMENT_RECEIVE_DATE
     */
    public void setPaymentReceiveDate(Date value) {
        setAttributeInternal(PAYMENTRECEIVEDATE, value);
    }

    /**
     * Gets the attribute value for PERSON_CODE using the alias name PersonCode.
     * @return the PERSON_CODE
     */
    public String getPersonCode() {
        return (String) getAttributeInternal(PERSONCODE);
    }


    /**
     * Gets the attribute value for POEP_ID using the alias name PoepId.
     * @return the POEP_ID
     */
    public Number getPoepId() {
        return (Number) getAttributeInternal(POEPID);
    }


    /**
     * Gets the attribute value for POLICY_CODE using the alias name PolicyCode.
     * @return the POLICY_CODE
     */
    public String getPolicyCode() {
        return (String) getAttributeInternal(POLICYCODE);
    }


    /**
     * Gets the attribute value for PRODUCT_CODE using the alias name ProductCode.
     * @return the PRODUCT_CODE
     */
    public String getProductCode() {
        return (String) getAttributeInternal(PRODUCTCODE);
    }


    /**
     * Gets the attribute value for USERNAME using the alias name Username.
     * @return the USERNAME
     */
    public String getUsername() {
        return (String) getAttributeInternal(USERNAME);
    }

}

