package com.liberty.health.comms.model.comms.views;

import com.core.model.vo.classes.CoreViewObjectImpl;

import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 22 12:31:35 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CommsCalcSnapShotLatestRunVOImpl extends CoreViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CommsCalcSnapShotLatestRunVOImpl() {
    }


    /**
     * Returns the bind variable value for pcountrylist.
     * @return bind variable value for pcountrylist
     */
    public String getpcountrylist() {
        return (String) getNamedWhereClauseParam("pcountrylist");
    }

    /**
     * Sets <code>value</code> for bind variable pcountrylist.
     * @param value value to bind as pcountrylist
     */
    public void setpcountrylist(String value) {
        setNamedWhereClauseParam("pcountrylist", value);
    }
}

