package com.liberty.health.comms.model.comms.views;

import com.core.model.vo.classes.CoreViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 12 11:42:13 CAT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CommsCalcCompareDetailVORowImpl extends CoreViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        CalculationDatetime,
        CommsCalcTypeDesc,
        CountryCode,
        BrokerIdNo,
        BrokerName,
        CompanyIdNo,
        CompanyName,
        ParentgroupCode,
        GroupCode,
        GroupName,
        ProductCode,
        ProductName,
        PersonCode,
        ContributionDate,
        PaymentReceiveDate,
        CommsCalcTypeCode,
        CommsPerc,
        PaymentReceiveAmt,
        CommsCalculatedAmt,
        InvoiceNo,
        PreferredCurrencyCode,
        CommsCalculatedExchAmt,
        ExchangeRate;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int CALCULATIONDATETIME = AttributesEnum.CalculationDatetime.index();
    public static final int COMMSCALCTYPEDESC = AttributesEnum.CommsCalcTypeDesc.index();
    public static final int COUNTRYCODE = AttributesEnum.CountryCode.index();
    public static final int BROKERIDNO = AttributesEnum.BrokerIdNo.index();
    public static final int BROKERNAME = AttributesEnum.BrokerName.index();
    public static final int COMPANYIDNO = AttributesEnum.CompanyIdNo.index();
    public static final int COMPANYNAME = AttributesEnum.CompanyName.index();
    public static final int PARENTGROUPCODE = AttributesEnum.ParentgroupCode.index();
    public static final int GROUPCODE = AttributesEnum.GroupCode.index();
    public static final int GROUPNAME = AttributesEnum.GroupName.index();
    public static final int PRODUCTCODE = AttributesEnum.ProductCode.index();
    public static final int PRODUCTNAME = AttributesEnum.ProductName.index();
    public static final int PERSONCODE = AttributesEnum.PersonCode.index();
    public static final int CONTRIBUTIONDATE = AttributesEnum.ContributionDate.index();
    public static final int PAYMENTRECEIVEDATE = AttributesEnum.PaymentReceiveDate.index();
    public static final int COMMSCALCTYPECODE = AttributesEnum.CommsCalcTypeCode.index();
    public static final int COMMSPERC = AttributesEnum.CommsPerc.index();
    public static final int PAYMENTRECEIVEAMT = AttributesEnum.PaymentReceiveAmt.index();
    public static final int COMMSCALCULATEDAMT = AttributesEnum.CommsCalculatedAmt.index();
    public static final int INVOICENO = AttributesEnum.InvoiceNo.index();
    public static final int PREFERREDCURRENCYCODE = AttributesEnum.PreferredCurrencyCode.index();
    public static final int COMMSCALCULATEDEXCHAMT = AttributesEnum.CommsCalculatedExchAmt.index();
    public static final int EXCHANGERATE = AttributesEnum.ExchangeRate.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CommsCalcCompareDetailVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute CalculationDatetime.
     * @return the CalculationDatetime
     */
    public Date getCalculationDatetime() {
        return (Date) getAttributeInternal(CALCULATIONDATETIME);
    }

    /**
     * Gets the attribute value for the calculated attribute CommsCalcTypeDesc.
     * @return the CommsCalcTypeDesc
     */
    public String getCommsCalcTypeDesc() {
        return (String) getAttributeInternal(COMMSCALCTYPEDESC);
    }

    /**
     * Gets the attribute value for the calculated attribute CountryCode.
     * @return the CountryCode
     */
    public String getCountryCode() {
        return (String) getAttributeInternal(COUNTRYCODE);
    }

    /**
     * Gets the attribute value for the calculated attribute BrokerIdNo.
     * @return the BrokerIdNo
     */
    public Number getBrokerIdNo() {
        return (Number) getAttributeInternal(BROKERIDNO);
    }

    /**
     * Gets the attribute value for the calculated attribute BrokerName.
     * @return the BrokerName
     */
    public String getBrokerName() {
        return (String) getAttributeInternal(BROKERNAME);
    }

    /**
     * Gets the attribute value for the calculated attribute CompanyIdNo.
     * @return the CompanyIdNo
     */
    public Number getCompanyIdNo() {
        return (Number) getAttributeInternal(COMPANYIDNO);
    }

    /**
     * Gets the attribute value for the calculated attribute CompanyName.
     * @return the CompanyName
     */
    public String getCompanyName() {
        return (String) getAttributeInternal(COMPANYNAME);
    }

    /**
     * Gets the attribute value for the calculated attribute ParentgroupCode.
     * @return the ParentgroupCode
     */
    public String getParentgroupCode() {
        return (String) getAttributeInternal(PARENTGROUPCODE);
    }

    /**
     * Gets the attribute value for the calculated attribute GroupCode.
     * @return the GroupCode
     */
    public String getGroupCode() {
        return (String) getAttributeInternal(GROUPCODE);
    }

    /**
     * Gets the attribute value for the calculated attribute GroupName.
     * @return the GroupName
     */
    public String getGroupName() {
        return (String) getAttributeInternal(GROUPNAME);
    }

    /**
     * Gets the attribute value for the calculated attribute ProductCode.
     * @return the ProductCode
     */
    public String getProductCode() {
        return (String) getAttributeInternal(PRODUCTCODE);
    }

    /**
     * Gets the attribute value for the calculated attribute ProductName.
     * @return the ProductName
     */
    public String getProductName() {
        return (String) getAttributeInternal(PRODUCTNAME);
    }

    /**
     * Gets the attribute value for the calculated attribute PersonCode.
     * @return the PersonCode
     */
    public String getPersonCode() {
        return (String) getAttributeInternal(PERSONCODE);
    }

    /**
     * Gets the attribute value for the calculated attribute ContributionDate.
     * @return the ContributionDate
     */
    public Date getContributionDate() {
        return (Date) getAttributeInternal(CONTRIBUTIONDATE);
    }

    /**
     * Gets the attribute value for the calculated attribute PaymentReceiveDate.
     * @return the PaymentReceiveDate
     */
    public Date getPaymentReceiveDate() {
        return (Date) getAttributeInternal(PAYMENTRECEIVEDATE);
    }

    /**
     * Gets the attribute value for the calculated attribute CommsCalcTypeCode.
     * @return the CommsCalcTypeCode
     */
    public String getCommsCalcTypeCode() {
        return (String) getAttributeInternal(COMMSCALCTYPECODE);
    }

    /**
     * Gets the attribute value for the calculated attribute CommsPerc.
     * @return the CommsPerc
     */
    public Number getCommsPerc() {
        return (Number) getAttributeInternal(COMMSPERC);
    }

    /**
     * Gets the attribute value for the calculated attribute PaymentReceiveAmt.
     * @return the PaymentReceiveAmt
     */
    public Number getPaymentReceiveAmt() {
        return (Number) getAttributeInternal(PAYMENTRECEIVEAMT);
    }

    /**
     * Gets the attribute value for the calculated attribute CommsCalculatedAmt.
     * @return the CommsCalculatedAmt
     */
    public Number getCommsCalculatedAmt() {
        return (Number) getAttributeInternal(COMMSCALCULATEDAMT);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoiceNo.
     * @return the InvoiceNo
     */
    public Number getInvoiceNo() {
        return (Number) getAttributeInternal(INVOICENO);
    }

    /**
     * Gets the attribute value for the calculated attribute PreferredCurrencyCode.
     * @return the PreferredCurrencyCode
     */
    public String getPreferredCurrencyCode() {
        return (String) getAttributeInternal(PREFERREDCURRENCYCODE);
    }

    /**
     * Gets the attribute value for the calculated attribute CommsCalculatedExchAmt.
     * @return the CommsCalculatedExchAmt
     */
    public Number getCommsCalculatedExchAmt() {
        return (Number) getAttributeInternal(COMMSCALCULATEDEXCHAMT);
    }

    /**
     * Gets the attribute value for the calculated attribute ExchangeRate.
     * @return the ExchangeRate
     */
    public Number getExchangeRate() {
        return (Number) getAttributeInternal(EXCHANGERATE);
    }
}

