
insert into broker_comm_perc (BROKER_ID_NO,EFFECTIVE_START_DATETIME,EFFECTIVE_END_DATETIME,BROKER_COMM_PERC,BROKER_COMM_DESC,LAST_UPDATE_DATETIME,USERNAME) values (1,'01-JAN-2017','31-DEC-2017',10,'NEW',sysdate,user);
insert into broker_comm_perc (BROKER_ID_NO,EFFECTIVE_START_DATETIME,EFFECTIVE_END_DATETIME,BROKER_COMM_PERC,BROKER_COMM_DESC,LAST_UPDATE_DATETIME,USERNAME) values (1,'01-JAN-2016','31-DEC-2016',05,null,sysdate,user);
insert into broker_comm_perc (BROKER_ID_NO,EFFECTIVE_START_DATETIME,EFFECTIVE_END_DATETIME,BROKER_COMM_PERC,BROKER_COMM_DESC,LAST_UPDATE_DATETIME,USERNAME) values (2,'01-JAN-2017','31-DEC-2017',08,null,sysdate,user);
insert into broker_comm_perc (BROKER_ID_NO,EFFECTIVE_START_DATETIME,EFFECTIVE_END_DATETIME,BROKER_COMM_PERC,BROKER_COMM_DESC,LAST_UPDATE_DATETIME,USERNAME) values (2,'01-JAN-2016','31-DEC-2017',10,null,sysdate,user);
insert into broker_comm_perc (BROKER_ID_NO,EFFECTIVE_START_DATETIME,EFFECTIVE_END_DATETIME,BROKER_COMM_PERC,BROKER_COMM_DESC,LAST_UPDATE_DATETIME,USERNAME) values (3,'01-JAN-2016','31-DEC-2017',07,null,sysdate,user);


insert into broker_comments (BROKER_ID_NO,COMMENT_DATETIME,COMMENT_DESC,LAST_UPDATE_DATETIME,USERNAME)values (777000000,'21-FEB-2016','Comments for broker 777',sysdate,user);
insert into broker_comments (BROKER_ID_NO,COMMENT_DATETIME,COMMENT_DESC,LAST_UPDATE_DATETIME,USERNAME)values (777000000,'23-FEB-2016','Change Comments for broker 777',sysdate,user);
insert into broker_comments (BROKER_ID_NO,COMMENT_DATETIME,COMMENT_DESC,LAST_UPDATE_DATETIME,USERNAME)values (580000000,'21-FEB-2016','Comments for broker 580',sysdate,user);
insert into broker_comments (BROKER_ID_NO,COMMENT_DATETIME,COMMENT_DESC,LAST_UPDATE_DATETIME,USERNAME)values (580000000,'24-FEB-2016','Change Comments for broker 580',sysdate,user);


insert into company (COMPANY_ID_NO,COMPANY_NAME,COMPANY_ACCRED_START_DATE,COMPANY_ACCRED_END_DATE,INDIVID_ACCREDITATION,INDIVID_ACCRED_START_DATE,INDIVID_ACCRED_END_DATE,COUNTRY_CODE,VAT_REG_IND,IN_COUNTRY_IND,PREFERRED_IND,WHT_CERT_IND,SUPPORTING_DOCS) values (company_id_no_seq.nextval,'Best Brokers','21-JAN-2017',null,null,null,null,'ZA','N','Y','Y','N','N');
insert into company (COMPANY_ID_NO,COMPANY_NAME,COMPANY_ACCRED_START_DATE,COMPANY_ACCRED_END_DATE,INDIVID_ACCREDITATION,INDIVID_ACCRED_START_DATE,INDIVID_ACCRED_END_DATE,COUNTRY_CODE,VAT_REG_IND,IN_COUNTRY_IND,PREFERRED_IND,WHT_CERT_IND,SUPPORTING_DOCS) values (company_id_no_seq.nextval,'J and D Brokers','21-JAN-2017',null,null,null,null,'NG','Y','Y','N','N','Y');
insert into company (COMPANY_ID_NO,COMPANY_NAME,COMPANY_ACCRED_START_DATE,COMPANY_ACCRED_END_DATE,INDIVID_ACCREDITATION,INDIVID_ACCRED_START_DATE,INDIVID_ACCRED_END_DATE,COUNTRY_CODE,VAT_REG_IND,IN_COUNTRY_IND,PREFERRED_IND,WHT_CERT_IND,SUPPORTING_DOCS) values (company_id_no_seq.nextval,'Alexander Forbes','21-JAN-2017',null,null,null,null,'ZA','N','Y','Y','N','Y');

insert into company_reg (COMPANY_ID_NO,EFFECTIVE_START_DATETIME,EFFECTIVE_END_DATETIME,VAT_NO,REG_NO,FAIS_NO,EXPIRY_DATE,APPLICATION_DATE,AUTHORISE_DATE,LAST_UPDATE_DATETIME,USERNAME) values (1,'01-JAN-2016',null,1000,null,null,null,'01-JAN-2016','05-JAN-2016',sysdate,user);
insert into company_reg (COMPANY_ID_NO,EFFECTIVE_START_DATETIME,EFFECTIVE_END_DATETIME,VAT_NO,REG_NO,FAIS_NO,EXPIRY_DATE,APPLICATION_DATE,AUTHORISE_DATE,LAST_UPDATE_DATETIME,USERNAME) values (2,'01-JAN-2016','31-DEC-2017',100,null,null,null,'01-JAN-2016','05-JAN-2016',sysdate,user);
insert into company_reg (COMPANY_ID_NO,EFFECTIVE_START_DATETIME,EFFECTIVE_END_DATETIME,VAT_NO,REG_NO,FAIS_NO,EXPIRY_DATE,APPLICATION_DATE,AUTHORISE_DATE,LAST_UPDATE_DATETIME,USERNAME) values (3,'01-JUN-2016',null,700,null,null,null,null,null,sysdate,user);

insert into company_bank_details (COMPANY_ID_NO,EFFECTIVE_START_DATETIME,EFFECTIVE_END_DATE,BANK_ACC_TYPE_ID_NO,ACC_HOLDER_NAME,BANK_ACC_NAME,BANK_ACC_NO,BANK_NAME,BANK_BRANCH_CODE,BANK_BRANCH_NAME,BANK_SWIFT_CODE,IBAN_NIB_NO,CREATED_USERNAME,AUTH_USERNAME,LAST_UPDATE_DATETIME,USERNAME) values (1,'01-JAN-2016','31-DEC-2017',1,'JJ COLEMAN','Best Brokers',123899,'STANDARD',123,'SANDTON','SW123','IBAN121',user,null,sysdate,user);
insert into company_bank_details (COMPANY_ID_NO,EFFECTIVE_START_DATETIME,EFFECTIVE_END_DATE,BANK_ACC_TYPE_ID_NO,ACC_HOLDER_NAME,BANK_ACC_NAME,BANK_ACC_NO,BANK_NAME,BANK_BRANCH_CODE,BANK_BRANCH_NAME,BANK_SWIFT_CODE,IBAN_NIB_NO,CREATED_USERNAME,AUTH_USERNAME,LAST_UPDATE_DATETIME,USERNAME) values (2,'01-MAR-2016','31-DEC-2017',1,'PETER PIPER','J and D Brokers',345670,'NEDBANK',888,'CAPE TOWN','SW188',null,user,null,sysdate,user);
insert into company_bank_details (COMPANY_ID_NO,EFFECTIVE_START_DATETIME,EFFECTIVE_END_DATE,BANK_ACC_TYPE_ID_NO,ACC_HOLDER_NAME,BANK_ACC_NAME,BANK_ACC_NO,BANK_NAME,BANK_BRANCH_CODE,BANK_BRANCH_NAME,BANK_SWIFT_CODE,IBAN_NIB_NO,CREATED_USERNAME,AUTH_USERNAME,LAST_UPDATE_DATETIME,USERNAME) values (3,'01-FEB-2017','31-DEC-2017',1,'JANE EYRE','Alexander Forbes',9988776,'STANDARD',1230,'DURBAN',null,'IBAN445',user,null,sysdate,user);

