/**
* ----------------------------------------------------------------------
* Change Request: LS-2508 - Trigger Enhancements
*
* Description  : LS-2508 - Trigger Enhancements - OP-164
* Author       : Sarel Eybers
* Date         : 2019-01-07
*              : 2019-01-26 Dev Config Run
*              : 2019-01-31 UAT Config Run
* Call Syntax  : Don't Just Run (F5) this script in it's etirety
*                Backup, etc. script gets made up as we go along. See below
* Steps
*   1) Compile Triggers
*   2) Backup wrongfully added Audit Records
*   3) Remove wrongfully added Audit Records
*   4) Ad Hoc
*                                                                         */

@../../../../plsql/triggers/lhhcom/OHI_PRODUCTS_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/OHI_POLICYHOLDERS_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/OHI_POLICY_GROUPS_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/OHI_POLICY_BROKERS_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/OHI_POLICIES_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/OHI_POL_ENRLMNTS_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/OHI_INSURED_ENTITIES_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/OHI_HOLD_IND_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/OHI_GROUPS_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/OHI_ENRLMNT_PRDCTS_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/OHI_COMM_PERC_AUDIT_TRG.sql;

@../../../../plsql/triggers/lhhcom/ACCREDITATION_TYPE_AUD_BEF_TRG.sql;
@../../../../plsql/triggers/lhhcom/ADDRESS_TYPE_AUDIT_BEFORE_TRG.sql;
@../../../../plsql/triggers/lhhcom/BROKER_ACCREDITAT_AUD_BEF_TRG.sql;
@../../../../plsql/triggers/lhhcom/BROKER_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/BROKER_FUNCTION_AUD_BEF_TRG.sql;
@../../../../plsql/triggers/lhhcom/BROKER_TABLE_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/BROKER_TABLE_TYPE_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/COMPANY_ACCREDITAT_AUD_BEF_TRG.sql;
@../../../../plsql/triggers/lhhcom/COMPANY_ADDRESS_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/COMPANY_AUDIT_BEFORE_TRG.sql;
@../../../../plsql/triggers/lhhcom/COMPANY_CONTACT_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/COMPANY_CONTACT_TYPE_BEF_TRG.sql;
@../../../../plsql/triggers/lhhcom/COMPANY_COUNTRY_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/COMPANY_FEE_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/COMPANY_FEE_TYPE_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/COMPANY_FUNCTION_AUDIT_BEF_TRG.sql;
@../../../../plsql/triggers/lhhcom/COMPANY_REG_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/COMPANY_TABLE_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/COMPANY_TABLE_TYPE_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/COUNTRY_TAXES_AUDIT_TRG.sql;
@../../../../plsql/triggers/lhhcom/INVOICE_AUDIT_BEFORE_TRG.sql;
@../../../../plsql/triggers/lhhcom/INVOICE_DETAIL_AUDIT_BEF_TRG.sql;
@../../../../plsql/triggers/lhhcom/INVOICE_PAYMENTS_AUDIT_BEF_TRG.sql;

/

/* Code Used to decide what tables are affected

-- SQL to find all the Audit tables
select q'[select ']' || owner || '.' || table_name || q'[' tble, count(*) cnt from ]' || owner || '.' || table_name || q'[ where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all]' line from all_tables
 where table_name like '%AUDIT';

-- SQL generated by above code
select * from (
select 'LHHCOM.INVOICE_PAYMENTS_AUDIT' tble, count(*) cnt from LHHCOM.INVOICE_PAYMENTS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select 'LHHCOM.COUNTRY_TAXES_AUDIT' tble, count(*) cnt from LHHCOM.COUNTRY_TAXES_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select 'LHHCOM.INVOICE_AUDIT' tble, count(*) cnt from LHHCOM.INVOICE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select 'LHHCOM.TEMP_INVOICE_AUDIT' tble, count(*) cnt from LHHCOM.TEMP_INVOICE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select 'LHHCOM.COMPANY_REG_AUDIT' tble, count(*) cnt from LHHCOM.COMPANY_REG_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select 'LHHCOM.OHI_HOLD_IND_AUDIT' tble, count(*) cnt from LHHCOM.OHI_HOLD_IND_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select 'LHHCOM.OHI_COMM_PERC_AUDIT' tble, count(*) cnt from LHHCOM.OHI_COMM_PERC_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select 'LHHCOM.OHI_ENROLLMENT_PRODUCTS_AUDIT' tble, count(*) cnt from LHHCOM.OHI_ENROLLMENT_PRODUCTS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select 'LHHCOM.OHI_PRODUCTS_AUDIT' tble, count(*) cnt from LHHCOM.OHI_PRODUCTS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select 'LHHCOM.OHI_POLICY_ENROLLMENTS_AUDIT' tble, count(*) cnt from LHHCOM.OHI_POLICY_ENROLLMENTS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select 'LHHCOM.OHI_INSURED_ENTITIES_AUDIT' tble, count(*) cnt from LHHCOM.OHI_INSURED_ENTITIES_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select 'LHHCOM.OHI_POLICYHOLDERS_AUDIT' tble, count(*) cnt from LHHCOM.OHI_POLICYHOLDERS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select 'LHHCOM.OHI_POLICY_BROKERS_AUDIT' tble, count(*) cnt from LHHCOM.OHI_POLICY_BROKERS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select 'LHHCOM.OHI_POLICY_GROUPS_AUDIT' tble, count(*) cnt from LHHCOM.OHI_POLICY_GROUPS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select 'LHHCOM.OHI_POLICIES_AUDIT' tble, count(*) cnt from LHHCOM.OHI_POLICIES_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select 'LHHCOM.OHI_GROUPS_AUDIT' tble, count(*) cnt from LHHCOM.OHI_GROUPS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select 'LHHCOM.INVOICE_DETAIL_AUDIT' tble, count(*) cnt from LHHCOM.INVOICE_DETAIL_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select 'LHHCOM.BROKER_FUNCTION_AUDIT' tble, count(*) cnt from LHHCOM.BROKER_FUNCTION_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select 'LHHCOM.BROKER_TABLE_TYPE_AUDIT' tble, count(*) cnt from LHHCOM.BROKER_TABLE_TYPE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select 'LHHCOM.BROKER_TABLE_AUDIT' tble, count(*) cnt from LHHCOM.BROKER_TABLE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select 'LHHCOM.BROKER_AUDIT' tble, count(*) cnt from LHHCOM.BROKER_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select 'LHHCOM.BROKER_ACCREDITATION_AUDIT' tble, count(*) cnt from LHHCOM.BROKER_ACCREDITATION_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select 'LHHCOM.COMPANY_FUNCTION_AUDIT' tble, count(*) cnt from LHHCOM.COMPANY_FUNCTION_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select 'LHHCOM.COMPANY_TABLE_TYPE_AUDIT' tble, count(*) cnt from LHHCOM.COMPANY_TABLE_TYPE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select 'LHHCOM.COMPANY_TABLE_AUDIT' tble, count(*) cnt from LHHCOM.COMPANY_TABLE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select 'LHHCOM.COMPANY_FEE_AUDIT' tble, count(*) cnt from LHHCOM.COMPANY_FEE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select 'LHHCOM.COMPANY_FEE_TYPE_AUDIT' tble, count(*) cnt from LHHCOM.COMPANY_FEE_TYPE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select 'LHHCOM.COMPANY_CONTACT_AUDIT' tble, count(*) cnt from LHHCOM.COMPANY_CONTACT_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select 'LHHCOM.COMPANY_AUDIT' tble, count(*) cnt from LHHCOM.COMPANY_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select 'LHHCOM.COMPANY_ADDRESS_AUDIT' tble, count(*) cnt from LHHCOM.COMPANY_ADDRESS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select 'LHHCOM.COMPANY_ACCREDITATION_AUDIT' tble, count(*) cnt from LHHCOM.COMPANY_ACCREDITATION_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select 'LHHCOM.COMPANY_COUNTRY_AUDIT' tble, count(*) cnt from LHHCOM.COMPANY_COUNTRY_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select 'LHHCOM.COMPANY_CONTACT_TYPE_AUDIT' tble, count(*) cnt from LHHCOM.COMPANY_CONTACT_TYPE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select 'LHHCOM.ADDRESS_TYPE_AUDIT' tble, count(*) cnt from LHHCOM.ADDRESS_TYPE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select 'LHHCOM.ACCREDITATION_TYPE_AUDIT' tble, count(*) cnt from LHHCOM.ACCREDITATION_TYPE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select 'UTIL.SYSTEM_PARAMETER_AUDIT' tble, count(*) cnt from UTIL.SYSTEM_PARAMETER_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %'
) where cnt > 0 order by 1;

-- Dev Result
LHHCOM.BROKER_AUDIT	181
LHHCOM.COMPANY_AUDIT	172
LHHCOM.COMPANY_CONTACT_AUDIT	807
LHHCOM.COMPANY_FUNCTION_AUDIT	20
LHHCOM.COMPANY_REG_AUDIT	2
LHHCOM.INVOICE_AUDIT	232
LHHCOM.INVOICE_DETAIL_AUDIT	639
LHHCOM.OHI_COMM_PERC_AUDIT	41
LHHCOM.OHI_HOLD_IND_AUDIT	1
LHHCOM.OHI_POLICY_BROKERS_AUDIT	4816044
LHHCOM.TEMP_INVOICE_AUDIT	206

-- UAT Result
LHHCOM.BROKER_ACCREDITATION_AUDIT	1
LHHCOM.BROKER_AUDIT	181
LHHCOM.BROKER_FUNCTION_AUDIT	8
LHHCOM.COMPANY_ACCREDITATION_AUDIT	3
LHHCOM.COMPANY_AUDIT	175
LHHCOM.COMPANY_CONTACT_AUDIT	723
LHHCOM.COMPANY_FEE_AUDIT	1
LHHCOM.COMPANY_FUNCTION_AUDIT	43
LHHCOM.COMPANY_REG_AUDIT	3
LHHCOM.INVOICE_AUDIT	2492
LHHCOM.INVOICE_DETAIL_AUDIT	3657
LHHCOM.OHI_COMM_PERC_AUDIT	94
LHHCOM.OHI_HOLD_IND_AUDIT	3
LHHCOM.OHI_POLICY_BROKERS_AUDIT	3965922
LHHCOM.TEMP_INVOICE_AUDIT	206

-- Prod Result
LHHCOM.BROKER_AUDIT	185
LHHCOM.COMPANY_AUDIT	172
LHHCOM.COMPANY_CONTACT_AUDIT	867
LHHCOM.COMPANY_FEE_AUDIT	6
LHHCOM.COMPANY_FUNCTION_AUDIT	102
LHHCOM.COMPANY_REG_AUDIT	8
LHHCOM.INVOICE_AUDIT	321
LHHCOM.INVOICE_DETAIL_AUDIT	8479
LHHCOM.OHI_COMM_PERC_AUDIT	186
LHHCOM.OHI_HOLD_IND_AUDIT	4
LHHCOM.OHI_POLICY_BROKERS_AUDIT	4816044

*/

/* Code used to determine which backups must be made

-- SQL to make backup of all affected Audit tables
select q'[select q'[create table TMP_OP164_]' || substr(table_name, 1, 19) || ' AS (select * from ' || owner || '.' || table_name || 
  q'[ where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]]'
|| q'[' stmnt, count(*) cnt from ]' || owner || '.' || table_name || q'[ where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all]' line from all_tables
 where table_name like '%AUDIT';

-- SQL generated by above Code
select * from (
select q'[create table TMP_OP164_INVOICE_PAYMENTS_AU AS (select * from LHHCOM.INVOICE_PAYMENTS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from LHHCOM.INVOICE_PAYMENTS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[create table TMP_OP164_COUNTRY_TAXES_AUDIT AS (select * from LHHCOM.COUNTRY_TAXES_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from LHHCOM.COUNTRY_TAXES_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[create table TMP_OP164_INVOICE_AUDIT AS (select * from LHHCOM.INVOICE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from LHHCOM.INVOICE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[create table TMP_OP164_TEMP_INVOICE_AUDIT AS (select * from LHHCOM.TEMP_INVOICE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from LHHCOM.TEMP_INVOICE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[create table TMP_OP164_COMPANY_REG_AUDIT AS (select * from LHHCOM.COMPANY_REG_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from LHHCOM.COMPANY_REG_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[create table TMP_OP164_OHI_HOLD_IND_AUDIT AS (select * from LHHCOM.OHI_HOLD_IND_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from LHHCOM.OHI_HOLD_IND_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[create table TMP_OP164_OHI_COMM_PERC_AUDIT AS (select * from LHHCOM.OHI_COMM_PERC_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from LHHCOM.OHI_COMM_PERC_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[create table TMP_OP164_OHI_ENROLLMENT_PROD AS (select * from LHHCOM.OHI_ENROLLMENT_PRODUCTS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from LHHCOM.OHI_ENROLLMENT_PRODUCTS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[create table TMP_OP164_OHI_PRODUCTS_AUDIT AS (select * from LHHCOM.OHI_PRODUCTS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from LHHCOM.OHI_PRODUCTS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[create table TMP_OP164_OHI_POLICY_ENROLLME AS (select * from LHHCOM.OHI_POLICY_ENROLLMENTS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from LHHCOM.OHI_POLICY_ENROLLMENTS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[create table TMP_OP164_OHI_INSURED_ENTITIE AS (select * from LHHCOM.OHI_INSURED_ENTITIES_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from LHHCOM.OHI_INSURED_ENTITIES_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[create table TMP_OP164_OHI_POLICYHOLDERS_A AS (select * from LHHCOM.OHI_POLICYHOLDERS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from LHHCOM.OHI_POLICYHOLDERS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[create table TMP_OP164_OHI_POLICY_BROKERS_ AS (select * from LHHCOM.OHI_POLICY_BROKERS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from LHHCOM.OHI_POLICY_BROKERS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[create table TMP_OP164_OHI_POLICY_GROUPS_A AS (select * from LHHCOM.OHI_POLICY_GROUPS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from LHHCOM.OHI_POLICY_GROUPS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[create table TMP_OP164_OHI_POLICIES_AUDIT AS (select * from LHHCOM.OHI_POLICIES_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from LHHCOM.OHI_POLICIES_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[create table TMP_OP164_OHI_GROUPS_AUDIT AS (select * from LHHCOM.OHI_GROUPS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from LHHCOM.OHI_GROUPS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[create table TMP_OP164_INVOICE_DETAIL_AUDI AS (select * from LHHCOM.INVOICE_DETAIL_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from LHHCOM.INVOICE_DETAIL_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[create table TMP_OP164_BROKER_FUNCTION_AUD AS (select * from LHHCOM.BROKER_FUNCTION_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from LHHCOM.BROKER_FUNCTION_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[create table TMP_OP164_BROKER_TABLE_TYPE_A AS (select * from LHHCOM.BROKER_TABLE_TYPE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from LHHCOM.BROKER_TABLE_TYPE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[create table TMP_OP164_BROKER_TABLE_AUDIT AS (select * from LHHCOM.BROKER_TABLE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from LHHCOM.BROKER_TABLE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[create table TMP_OP164_BROKER_AUDIT AS (select * from LHHCOM.BROKER_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from LHHCOM.BROKER_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[create table TMP_OP164_BROKER_ACCREDITATIO AS (select * from LHHCOM.BROKER_ACCREDITATION_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from LHHCOM.BROKER_ACCREDITATION_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[create table TMP_OP164_COMPANY_FUNCTION_AU AS (select * from LHHCOM.COMPANY_FUNCTION_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from LHHCOM.COMPANY_FUNCTION_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[create table TMP_OP164_COMPANY_TABLE_TYPE_ AS (select * from LHHCOM.COMPANY_TABLE_TYPE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from LHHCOM.COMPANY_TABLE_TYPE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[create table TMP_OP164_COMPANY_TABLE_AUDIT AS (select * from LHHCOM.COMPANY_TABLE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from LHHCOM.COMPANY_TABLE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[create table TMP_OP164_COMPANY_FEE_AUDIT AS (select * from LHHCOM.COMPANY_FEE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from LHHCOM.COMPANY_FEE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[create table TMP_OP164_COMPANY_FEE_TYPE_AU AS (select * from LHHCOM.COMPANY_FEE_TYPE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from LHHCOM.COMPANY_FEE_TYPE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[create table TMP_OP164_COMPANY_CONTACT_AUD AS (select * from LHHCOM.COMPANY_CONTACT_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from LHHCOM.COMPANY_CONTACT_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[create table TMP_OP164_COMPANY_AUDIT AS (select * from LHHCOM.COMPANY_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from LHHCOM.COMPANY_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[create table TMP_OP164_COMPANY_ADDRESS_AUD AS (select * from LHHCOM.COMPANY_ADDRESS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from LHHCOM.COMPANY_ADDRESS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[create table TMP_OP164_COMPANY_ACCREDITATI AS (select * from LHHCOM.COMPANY_ACCREDITATION_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from LHHCOM.COMPANY_ACCREDITATION_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[create table TMP_OP164_COMPANY_COUNTRY_AUD AS (select * from LHHCOM.COMPANY_COUNTRY_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from LHHCOM.COMPANY_COUNTRY_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[create table TMP_OP164_COMPANY_CONTACT_TYP AS (select * from LHHCOM.COMPANY_CONTACT_TYPE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from LHHCOM.COMPANY_CONTACT_TYPE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[create table TMP_OP164_ADDRESS_TYPE_AUDIT AS (select * from LHHCOM.ADDRESS_TYPE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from LHHCOM.ADDRESS_TYPE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[create table TMP_OP164_ACCREDITATION_TYPE_ AS (select * from LHHCOM.ACCREDITATION_TYPE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from LHHCOM.ACCREDITATION_TYPE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[create table TMP_OP164_SYSTEM_PARAMETER_AU AS (select * from UTIL.SYSTEM_PARAMETER_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');]' stmnt, count(*) cnt from UTIL.SYSTEM_PARAMETER_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %'
) where cnt > 0 order by 1;

*/

-- Resultant Create table statements
/* -- This was run in Dev
create table TMP_LS2508_BROKER_AUDIT AS (select * from LHHCOM.BROKER_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
create table TMP_LS2508_COMPANY_AUDIT AS (select * from LHHCOM.COMPANY_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
create table TMP_LS2508_COMPANY_CONTACT_AUD AS (select * from LHHCOM.COMPANY_CONTACT_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
create table TMP_LS2508_COMPANY_FUNCTION_AU AS (select * from LHHCOM.COMPANY_FUNCTION_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
create table TMP_LS2508_COMPANY_REG_AUDIT AS (select * from LHHCOM.COMPANY_REG_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
create table TMP_LS2508_INVOICE_AUDIT AS (select * from LHHCOM.INVOICE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
create table TMP_LS2508_INVOICE_DETAIL_AUDI AS (select * from LHHCOM.INVOICE_DETAIL_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
create table TMP_LS2508_OHI_COMM_PERC_AUDIT AS (select * from LHHCOM.OHI_COMM_PERC_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
create table TMP_LS2508_OHI_HOLD_IND_AUDIT AS (select * from LHHCOM.OHI_HOLD_IND_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
create table TMP_LS2508_OHI_POLICY_BROKERS_ AS (select * from LHHCOM.OHI_POLICY_BROKERS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
create table TMP_LS2508_TEMP_INVOICE_AUDIT AS (select * from LHHCOM.TEMP_INVOICE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
*/
/* -- This is run for UAT
create table TMP_LS2508_BROKER_ACCREDITATIO AS (select * from LHHCOM.BROKER_ACCREDITATION_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
create table TMP_LS2508_BROKER_AUDIT AS (select * from LHHCOM.BROKER_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
create table TMP_LS2508_BROKER_FUNCTION_AUD AS (select * from LHHCOM.BROKER_FUNCTION_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
create table TMP_LS2508_COMPANY_ACCREDITATI AS (select * from LHHCOM.COMPANY_ACCREDITATION_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
create table TMP_LS2508_COMPANY_AUDIT AS (select * from LHHCOM.COMPANY_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
create table TMP_LS2508_COMPANY_CONTACT_AUD AS (select * from LHHCOM.COMPANY_CONTACT_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
create table TMP_LS2508_COMPANY_FEE_AUDIT AS (select * from LHHCOM.COMPANY_FEE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
create table TMP_LS2508_COMPANY_FUNCTION_AU AS (select * from LHHCOM.COMPANY_FUNCTION_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
create table TMP_LS2508_COMPANY_REG_AUDIT AS (select * from LHHCOM.COMPANY_REG_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
create table TMP_LS2508_INVOICE_AUDIT AS (select * from LHHCOM.INVOICE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
create table TMP_LS2508_INVOICE_DETAIL_AUDI AS (select * from LHHCOM.INVOICE_DETAIL_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
create table TMP_LS2508_OHI_COMM_PERC_AUDIT AS (select * from LHHCOM.OHI_COMM_PERC_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
create table TMP_LS2508_OHI_HOLD_IND_AUDIT AS (select * from LHHCOM.OHI_HOLD_IND_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
create table TMP_LS2508_OHI_POLICY_BROKERS_ AS (select * from LHHCOM.OHI_POLICY_BROKERS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
create table TMP_LS2508_TEMP_INVOICE_AUDIT AS (select * from LHHCOM.TEMP_INVOICE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
-- */
-- This is run for Prod
create table TMP_OP164_BROKER_AUDIT AS (select * from LHHCOM.BROKER_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
create table TMP_OP164_COMPANY_AUDIT AS (select * from LHHCOM.COMPANY_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
create table TMP_OP164_COMPANY_CONTACT_AUD AS (select * from LHHCOM.COMPANY_CONTACT_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
create table TMP_OP164_COMPANY_FEE_AUDIT AS (select * from LHHCOM.COMPANY_FEE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
create table TMP_OP164_COMPANY_FUNCTION_AU AS (select * from LHHCOM.COMPANY_FUNCTION_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
create table TMP_OP164_COMPANY_REG_AUDIT AS (select * from LHHCOM.COMPANY_REG_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
create table TMP_OP164_INVOICE_AUDIT AS (select * from LHHCOM.INVOICE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
create table TMP_OP164_INVOICE_DETAIL_AUDI AS (select * from LHHCOM.INVOICE_DETAIL_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
create table TMP_OP164_OHI_COMM_PERC_AUDIT AS (select * from LHHCOM.OHI_COMM_PERC_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
create table TMP_OP164_OHI_HOLD_IND_AUDIT AS (select * from LHHCOM.OHI_HOLD_IND_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
create table TMP_OP164_OHI_POLICY_BROKERS_ AS (select * from LHHCOM.OHI_POLICY_BROKERS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %');
-- */

/* Code used to determine what data must be deleted from which tables

-- SQL to delete data from the affected Audit tables
select q'[select q'[delete from ]' || owner || '.' || table_name || 
  q'[ where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]]'
|| q'[' stmnt, count(*) cnt from ]' || owner || '.' || table_name || q'[ where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all]' line from all_tables
 where table_name like '%AUDIT';

-- SQL generated by above Code
select * from (
select q'[delete from LHHCOM.TMP_OP164_OHI_HOLD_IND_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.TMP_OP164_OHI_HOLD_IND_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.TMP_OP164_OHI_COMM_PERC_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.TMP_OP164_OHI_COMM_PERC_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.TMP_OP164_INVOICE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.TMP_OP164_INVOICE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.TMP_OP164_COMPANY_REG_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.TMP_OP164_COMPANY_REG_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.TMP_OP164_COMPANY_FEE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.TMP_OP164_COMPANY_FEE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.TMP_OP164_BROKER_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.TMP_OP164_BROKER_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.TMP_OP164_COMPANY_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.TMP_OP164_COMPANY_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.INVOICE_PAYMENTS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.INVOICE_PAYMENTS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.COUNTRY_TAXES_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.COUNTRY_TAXES_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.INVOICE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.INVOICE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.TEMP_INVOICE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.TEMP_INVOICE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.COMPANY_REG_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.COMPANY_REG_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.OHI_HOLD_IND_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.OHI_HOLD_IND_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.OHI_COMM_PERC_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.OHI_COMM_PERC_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.OHI_ENROLLMENT_PRODUCTS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.OHI_ENROLLMENT_PRODUCTS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.OHI_PRODUCTS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.OHI_PRODUCTS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.OHI_POLICY_ENROLLMENTS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.OHI_POLICY_ENROLLMENTS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.OHI_INSURED_ENTITIES_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.OHI_INSURED_ENTITIES_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.OHI_POLICYHOLDERS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.OHI_POLICYHOLDERS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.OHI_POLICY_BROKERS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.OHI_POLICY_BROKERS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.OHI_POLICY_GROUPS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.OHI_POLICY_GROUPS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.OHI_POLICIES_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.OHI_POLICIES_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.OHI_GROUPS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.OHI_GROUPS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.INVOICE_DETAIL_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.INVOICE_DETAIL_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.BROKER_FUNCTION_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.BROKER_FUNCTION_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.BROKER_TABLE_TYPE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.BROKER_TABLE_TYPE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.BROKER_TABLE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.BROKER_TABLE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.BROKER_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.BROKER_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.BROKER_ACCREDITATION_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.BROKER_ACCREDITATION_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.COMPANY_FUNCTION_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.COMPANY_FUNCTION_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.COMPANY_TABLE_TYPE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.COMPANY_TABLE_TYPE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.COMPANY_TABLE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.COMPANY_TABLE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.COMPANY_FEE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.COMPANY_FEE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.COMPANY_FEE_TYPE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.COMPANY_FEE_TYPE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.COMPANY_CONTACT_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.COMPANY_CONTACT_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.COMPANY_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.COMPANY_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.COMPANY_ADDRESS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.COMPANY_ADDRESS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.COMPANY_ACCREDITATION_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.COMPANY_ACCREDITATION_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.COMPANY_COUNTRY_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.COMPANY_COUNTRY_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.COMPANY_CONTACT_TYPE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.COMPANY_CONTACT_TYPE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.ADDRESS_TYPE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.ADDRESS_TYPE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from LHHCOM.ACCREDITATION_TYPE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from LHHCOM.ACCREDITATION_TYPE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %' union all
select q'[delete from UTIL.SYSTEM_PARAMETER_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';]' stmnt, count(*) cnt from UTIL.SYSTEM_PARAMETER_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %'
) where cnt > 0 order by 1;

*/

/* -- This was run for Dev
-- Resultant delete from table statements
delete from LHHCOM.BROKER_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
delete from LHHCOM.COMPANY_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
delete from LHHCOM.COMPANY_CONTACT_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
delete from LHHCOM.COMPANY_FUNCTION_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
delete from LHHCOM.COMPANY_REG_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
delete from LHHCOM.INVOICE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
delete from LHHCOM.INVOICE_DETAIL_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
delete from LHHCOM.OHI_COMM_PERC_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
delete from LHHCOM.OHI_HOLD_IND_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
delete from LHHCOM.OHI_POLICY_BROKERS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
delete from LHHCOM.TEMP_INVOICE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
*/

/*-- This is for UAT
delete from LHHCOM.BROKER_ACCREDITATION_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
delete from LHHCOM.BROKER_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
delete from LHHCOM.BROKER_FUNCTION_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
delete from LHHCOM.COMPANY_ACCREDITATION_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
delete from LHHCOM.COMPANY_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
delete from LHHCOM.COMPANY_CONTACT_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
delete from LHHCOM.COMPANY_FEE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
delete from LHHCOM.COMPANY_FUNCTION_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
delete from LHHCOM.COMPANY_REG_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
delete from LHHCOM.INVOICE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
delete from LHHCOM.INVOICE_DETAIL_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
delete from LHHCOM.OHI_COMM_PERC_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
delete from LHHCOM.OHI_HOLD_IND_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
delete from LHHCOM.OHI_POLICY_BROKERS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
delete from LHHCOM.TEMP_INVOICE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
-- */

-- This is from Prod
delete from LHHCOM.BROKER_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
delete from LHHCOM.COMPANY_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
delete from LHHCOM.COMPANY_CONTACT_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
delete from LHHCOM.COMPANY_FEE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
delete from LHHCOM.COMPANY_FUNCTION_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
delete from LHHCOM.COMPANY_REG_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
delete from LHHCOM.INVOICE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
delete from LHHCOM.INVOICE_DETAIL_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
delete from LHHCOM.OHI_COMM_PERC_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
delete from LHHCOM.OHI_HOLD_IND_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
delete from LHHCOM.OHI_POLICY_BROKERS_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';
delete from LHHCOM.TEMP_INVOICE_AUDIT where transaction_desc like 'Change%' and upper(transaction_desc) NOT LIKE '% FROM %';