
  CREATE TABLE "UTIL"."INTERF_SYS_TRN_TP_SUB_TP_COL" 
   (	"INTERF_SYSTEM_ID_NO" NUMBER(9,0) NOT NULL ENABLE, 
	"TRN_TYPE_NO" NUMBER(9,0) NOT NULL ENABLE, 
	"TRN_SUB_TYPE_CODE" VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	"COLUMN_NAME" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"TRN_COLUMN_TYPE_CODE" CHAR(1 CHAR) NOT NULL ENABLE, 
	"COLUMN_LENGTH_NO" NUMBER(9,0) NOT NULL ENABLE, 
	"COLUMN_START_POS_NO" NUMBER(9,0) NOT NULL ENABLE, 
	"LAST_UPDATE_DATETIME" DATE NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "INTERF_SYS_TRN_TP_SUB_TP_C_PK" PRIMARY KEY ("INTERF_SYSTEM_ID_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "INTERF_SYS_TRN_TP_SUB_TP__FK1" FOREIGN KEY ("TRN_COLUMN_TYPE_CODE")
	  REFERENCES "UTIL"."INTERF_SYSTEM_TRN_COLUMN_TYPE" ("TRN_COLUMN_TYPE_CODE") ENABLE, 
	 CONSTRAINT "INTERF_SYS_TRN_TP_SUB_TP__FK2" FOREIGN KEY ("INTERF_SYSTEM_ID_NO", "TRN_TYPE_NO", "TRN_SUB_TYPE_CODE")
	  REFERENCES "UTIL"."INTERF_SYS_TRN_TP_SUB_TYPE" ("INTERF_SYSTEM_ID_NO", "TRN_TYPE_NO", "TRN_SUB_TYPE_CODE") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
