
  CREATE TABLE "UTIL"."SYSTEM_PARAMETER" 
   (	"SYSTEM_NAME" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"PARAMETER_SECTION" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"PARAMETER_KEY" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"PARAMETER_VALUE" VARCHAR2(200 CHAR), 
	"USER_UPDATE_IND" VARCHAR2(1 CHAR),
		"LAST_UPDATE_DATETIME" DATE NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(50 CHAR) NOT NULL ENABLE,
	 CONSTRAINT "SYSTEM_PARAMETER_PK" PRIMARY KEY ("SYSTEM_NAME", "PARAMETER_SECTION", "PARAMETER_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "SYSTEM_PARAMETER_FK1" FOREIGN KEY ("SYSTEM_NAME")
	  REFERENCES "UTIL"."SYSTEM_NAME" ("SYSTEM_NAME") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
