CREATE TABLE UTIL.SYSTEM_PARAMETER_AUDIT 
(
  TRANSACTION_DATETIME DATE, 
  TRANSACTION_DESC VARCHAR2(250 BYTE), 
  TRANSACTION_USERNAME VARCHAR2(50 BYTE),
  SYSTEM_NAME VARCHAR2(50 CHAR),
  PARAMETER_SECTION VARCHAR2(50 CHAR),
  PARAMETER_KEY VARCHAR2(100 CHAR),
  PARAMETER_VALUE VARCHAR2(200 CHAR),
  USER_UPDATE_IND VARCHAR2(1 CHAR)
   ) 
  TABLESPACE "USERS" ;
