 CREATE TABLE "UTIL"."UPLD_TRN" 
   ("UPLD_TRN_NO" NUMBER(15,0) NOT NULL ENABLE, 
	"DETAIL_SEQ_NO" NUMBER(15,0) NOT NULL ENABLE, 
    "INTERF_SYSTEM_ID_NO" NUMBER(9,0) NOT NULL ENABLE, 
	"TRN_TYPE_NO" NUMBER(9,0) NOT NULL ENABLE, 
	"TRN_SUB_TYPE_CODE" VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	"PROCESS_DATETIME" DATE NOT NULL ENABLE, 
	"TRN_DATETIME" DATE NOT NULL ENABLE, 
	"UPLD_TRN_DATE" DATE NOT NULL ENABLE, 
	"DATALINE" VARCHAR2(4000 CHAR), 
	"ERROR_DESC" VARCHAR2(500 CHAR), 
	"LAST_UPDATE_DATETIME" DATE NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "UPLD_TRN" PRIMARY KEY ("UPLD_TRN_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "UPLD_TRN_FK" FOREIGN KEY ("INTERF_SYSTEM_ID_NO", "TRN_TYPE_NO", "TRN_SUB_TYPE_CODE")
	  REFERENCES "UTIL"."INTERF_SYS_TRN_TP_SUB_TYPE" ("INTERF_SYSTEM_ID_NO", "TRN_TYPE_NO", "TRN_SUB_TYPE_CODE") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;