
  CREATE TABLE "UTIL"."WEB_APPL_OBJECT_LANG_MENU" 
   (	"WEB_APPL_OBJECT_NO" NUMBER(9,0) NOT NULL ENABLE, 
	"LOCAL_CODE" VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	"MENU_ITEM_NAME" VARCHAR2(200 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "WEB_APPL_OBJECT_LANG_MENU_PK" PRIMARY KEY ("WEB_APPL_OBJECT_NO", "LOCAL_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "WEB_APPL_OBJECT_LANG_MENU_FK1" FOREIGN KEY ("WEB_APPL_OBJECT_NO")
	  REFERENCES "UTIL"."WEB_APPL_OBJECT" ("WEB_APPL_OBJECT_NO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
