
  CREATE TABLE "UTIL"."WEB_APPL_OBJECT" 
   (	"WEB_APPL_OBJECT_NO" NUMBER(9,0) NOT NULL ENABLE, 
	"SYSTEM_NAME" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"PARENT_WEB_APPL_OBJECT_NO" NUMBER(9,0), 
	"OBJECT_TYPE_NO" NUMBER(5,0) NOT NULL ENABLE, 
	"MENU_SORT_SEQ_NO" NUMBER(5,0), 
	"URL_PATH_NAME" VARCHAR2(200 CHAR), 
	"ACTIVE_FROM_DATE" DATE, 
	"REMOVE_FROM_DATE" DATE, 
	 CONSTRAINT "WEB_APPL_OBJECT_NO_PK" PRIMARY KEY ("WEB_APPL_OBJECT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "WEB_APPL_OBJECT_NO_FK1" FOREIGN KEY ("SYSTEM_NAME")
	  REFERENCES "UTIL"."SYSTEM_NAME" ("SYSTEM_NAME") ENABLE, 
	 CONSTRAINT "WEB_APPL_OBJECT_NO_FK2" FOREIGN KEY ("OBJECT_TYPE_NO")
	  REFERENCES "UTIL"."WEB_APPL_OBJECT_TYPE" ("OBJECT_TYPE_NO") ENABLE, 
	 CONSTRAINT "WEB_APPL_OBJECT_FK1" FOREIGN KEY ("PARENT_WEB_APPL_OBJECT_NO")
	  REFERENCES "UTIL"."WEB_APPL_OBJECT" ("WEB_APPL_OBJECT_NO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
