package com.liberty.health.comms.model.payment.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 12 15:48:45 CAT 2018
// ---------------------------------------------------------------------
public interface InvoiceVO extends ViewObject {
    void setpInvoiceNo(oracle.jbo.domain.Number value);

    void setpCompanyIdNo(oracle.jbo.domain.Number value);
}

