-- Create Commisions Table Audits "LHHCOM"."ACCREDITATION_TYPE_AUDIT"

  CREATE TABLE "LHHCOM"."ACCREDITATION_TYPE_AUDIT" 
   (
  "TRANSACTION_DATETIME" DATE,
	"TRANSACTION_DESC" VARCHAR2(550 BYTE),
	"TRANSACTION_USERNAME" VARCHAR2(50 BYTE),
  "ACCREDITATION_TYPE_ID_NO"  NUMBER(2,0),
	"ACCREDITATION_TYPE_DESC" VARCHAR2(50 CHAR),
	"EFFECTIVE_START_DATE" DATE,
	"EFFECTIVE_END_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

/**
******** Check the structure of your table
*/
-- descr "LHHCOM"."ACCREDITATION_TYPE_AUDIT";

/**
******** Drop the structure of your ACCREDITATION_TYPE_AUDIT table if needed
*/
-- DROP TABLE "LHHCOM"."ACCREDITATION_TYPE_AUDIT"; 