 CREATE TABLE "LHHCOM"."ADDRESS_TYPE_AUDIT" 
   (
  "TRANSACTION_DATETIME" DATE,
  "TRANSACTION_DESC" VARCHAR2(550 BYTE),
  "TRANSACTION_USERNAME" VARCHAR2(50 BYTE),
  "ADDRESS_TYPE_CODE" CHAR(1 BYTE),
	"ADDRESS_TYPE_DESC" VARCHAR2(50 BYTE),
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE
) SEGMENT CREATION DEFERRED 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
TABLESPACE "USERS" ;

/**
******** Check the structure of your table
*/
-- descr "LHHCOM"."ADDRESS_TYPE_AUDIT";

/**
******** Drop the structure of your ADDRESS_TYPE_AUDIT table if needed
*/
-- DROP TABLE "LHHCOM"."ADDRESS_TYPE_AUDIT";
