  CREATE TABLE "LHHCOM"."BANK_ACCOUNT_TYPE_AUDIT" 
   (	
	"TRANSACTION_DATETIME" DATE, 
	"TRANSACTION_DESC" VARCHAR2(550 BYTE), 
	"TRANSACTION_USERNAME" VARCHAR2(50 BYTE),
  "BANK_ACC_TYPE_ID_NO" NUMBER(2,0), 
	"BANK_ACC_TYPE_DESC" VARCHAR2(250 BYTE), 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE
   ) 
   TABLESPACE "USERS" ;
