
  CREATE TABLE "LHHCOM"."BROKER_TABLE" 
   (	"BROKER_TABLE_ID_NO" NUMBER(9,0) NOT NULL ENABLE, 
	"BROKER_TABLE_DESC" VARCHAR2(50 CHAR), 
	"EFFECTIVE_START_DATE" DATE NOT NULL ENABLE,  
	"EFFECTIVE_END_DATE" DATE NOT NULL ENABLE,  
	"LAST_UPDATE_DATETIME" DATE DEFAULT '01-JAN-2017' NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(50 CHAR) DEFAULT 1 NOT NULL ENABLE, 
	 CONSTRAINT "BROKER_TABLE_PK" PRIMARY KEY ("BROKER_TABLE_ID_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
