  CREATE TABLE "LHHCOM"."BROKER_TABLE_TYPE_AUDIT" 
   (	
	"TRANSACTION_DATETIME" DATE, 
	"TRANSACTION_DESC" VARCHAR2(550 BYTE), 
	"TRANSACTION_USERNAME" VARCHAR2(50 BYTE),
	"BROKER_TABLE_TYPE_ID_NO" NUMBER(9,0), 
	"BROKER_TABLE_TYPE_DESC" VARCHAR2(50 BYTE), 
	"BROKER_TABLE_ID_NO" NUMBER(9,0), 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE 
   ) 
   TABLESPACE "USERS" ;
