  CREATE TABLE "LHHCOM"."BROKER_AUDIT" 
   (	
	"TRANSACTION_DATETIME" DATE, 
	"TRANSACTION_DESC" VARCHAR2(550 BYTE), 
	"TRANSACTION_USERNAME" VARCHAR2(50 BYTE),
  "BROKER_ID_NO" NUMBER(9,0), 
	"PARENT_BROKER_ID_NO" NUMBER(9,0), 
	"KAM_BROKER_ID_NO" NUMBER(9,0), 
	"COMPANY_ID_NO" NUMBER(9,0), 
	"PERSON_TITLE_CODE" VARCHAR2(12 BYTE), 
	"INITIALS" VARCHAR2(10 BYTE), 
	"BROKER_NAME" VARCHAR2(50 BYTE), 
	"BROKER_LAST_NAME" VARCHAR2(100 BYTE), 
	"PASSPORT_CODE" VARCHAR2(50 BYTE), 
	"LANGUAGE_CODE" VARCHAR2(4 BYTE), 
	"ID_NO" NUMBER(20,0), 
	"SMS_NOTIFICATION_IND" CHAR(1 BYTE), 
	"EMAIL_NOTIFICATION_IND" CHAR(1 BYTE), 
	"BUSINESS_DEV_MGR_NAME" VARCHAR2(250 BYTE), 
	"WEB_PASSWORD" VARCHAR2(50 BYTE)
   ) 
   TABLESPACE "USERS" ;
