-- Create Commisions Table Audits "LHHCOM"."BROKER_ACCREDITATION_AUDIT"

  CREATE TABLE "LHHCOM"."BROKER_ACCREDITATION_AUDIT" 
   (	
  "TRANSACTION_DATETIME" DATE,
	"TRANSACTION_DESC" VARCHAR2(550 BYTE),
	"TRANSACTION_USERNAME" VARCHAR2(50 BYTE),
  "BROKER_ID_NO" NUMBER(9,0),
	"EFFECTIVE_START_DATE" DATE,
	"EFFECTIVE_END_DATE" DATE, 
	"ACCREDITATION_TYPE_ID_NO" NUMBER(2,0),
	"BROKER_ACCRED_NO" NUMBER(9,0), 
	"BROKER_ACCRED_START_DATE" DATE,
	"BROKER_ACCRED_END_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

/**
******** Check the structure of your table
*/
-- descr "LHHCOM"."BROKER_ACCREDITATION_AUDIT";

/**
******** Drop the structure of your BROKER_ACCREDITATION_AUDIT table if needed
*/
-- DROP TABLE "LHHCOM"."BROKER_ACCREDITATION_AUDIT"; 