drop table COMMS_RECALC;

  CREATE TABLE "LHHCOM"."COMMS_RECALC" 
   (
   "POEP_ID"                 NUMBER(20,0) NOT NULL ENABLE,
   "PROCESSED_DATE"          DATE NOT NULL ENABLE,
   "DESCRIPTION"             VARCHAR2(250),
   "LAST_UPDATE_DATETIME"    DATE NOT NULL ENABLE,
   "USERNAME"                VARCHAR2(50) NOT NULL ENABLE
  );