CREATE GLOBAL TEMPORARY TABLE lhhcom.comms_fusion_billing_gt (
 KEY           VARCHAR2(500),
 INVOICE_AMT   NUMBER,
 PAYMENT_AMT   NUMBER,
 CSB_AMOUNT    NUMBER,
 ADJUSTMENTS   NUMBER,
 CREDIT_MEMO   NUMBER,
 TAX_AMOUNT    NUMBER,
 BALANCE_AMT   NUMBER
);
/