
  CREATE TABLE "LHHCOM"."COMPANY_ADDRESS_AUDIT" 
   (	
	"TRANSACTION_DATETIME" DATE, 
	"TRANSACTION_DESC" VARCHAR2(550 BYTE), 
	"TRANSACTION_USERNAME" VARCHAR2(50 BYTE),
	"COMPANY_ID_NO" NUMBER(9,0), 
	"COUNTRY_CODE" VARCHAR2(4 BYTE), 
	"ADDRESS_TYPE_CODE" CHAR(1 BYTE), 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE, 
	"ADDRESS_LINE1" VARCHAR2(250 BYTE), 
	"ADDRESS_LINE2" VARCHAR2(250 BYTE), 
	"ADDRESS_LINE3" VARCHAR2(250 BYTE), 
	"ADDRESS_COUNTRY_CODE" VARCHAR2(4 BYTE), 
	"POSTAL_CODE" VARCHAR2(15 BYTE)
   ) 
   TABLESPACE "USERS" ;
