  CREATE TABLE "LHHCOM"."COMPANY_COUNTRY_AUDIT" 
   (	
	"TRANSACTION_DATETIME" DATE, 
	"TRANSACTION_DESC" VARCHAR2(550 BYTE), 
	"TRANSACTION_USERNAME" VARCHAR2(50 BYTE),
	"COMPANY_ID_NO" NUMBER(9,0), 
	"COUNTRY_CODE" VARCHAR2(4 BYTE), 
	"MIN_PAYOUT_AMT" NUMBER(8,2), 
	"HOLD_IND" VARCHAR2(1 BYTE), 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE
   ) 
   TABLESPACE "USERS" ;
