
  CREATE TABLE "LHHCOM"."COMPANY_CONTACT" 
   (	"COMPANY_ID_NO" NUMBER(9,0) NOT NULL ENABLE, 
	"COUNTRY_CODE" VARCHAR2(4 CHAR) NOT NULL ENABLE, 
	"COMPANY_CONTACT_TYPE_ID_NO" NUMBER(2,0) NOT NULL ENABLE, 
	"EFFECTIVE_START_DATE" DATE NOT NULL ENABLE, 
	"EFFECTIVE_END_DATE" DATE NOT NULL ENABLE, 
	"CONTACT_NAME" VARCHAR2(250 CHAR), 
	"CONTACT_CELLPHONE_NO" VARCHAR2(30 CHAR), 
	"CONTACT_EMAIL" VARCHAR2(250 CHAR), 
	"CONTACT_FAX_NO" VARCHAR2(30 CHAR), 
	"CONTACT_TELEPHONE_NO" VARCHAR2(30 CHAR), 
	"CONTACT_DESC" VARCHAR2(250 CHAR), 
	"LAST_UPDATE_DATETIME" DATE NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "COMPANY_CONTACT_PK" PRIMARY KEY ("COMPANY_ID_NO", "COMPANY_CONTACT_TYPE_ID_NO", "EFFECTIVE_START_DATE", "COUNTRY_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "COMPANY_CONTACT_FK" FOREIGN KEY ("COMPANY_ID_NO", "COUNTRY_CODE")
	  REFERENCES "LHHCOM"."COMPANY_COUNTRY" ("COMPANY_ID_NO", "COUNTRY_CODE") ENABLE, 
	 CONSTRAINT "COMPANY_CONTACT_TYPE_FK" FOREIGN KEY ("COMPANY_CONTACT_TYPE_ID_NO")
	  REFERENCES "LHHCOM"."COMPANY_CONTACT_TYPE" ("COMPANY_CONTACT_TYPE_ID_NO") ENABLE,
		 CONSTRAINT "COMPANY_CONTACT_COMPANY_FK" FOREIGN KEY ("COMPANY_ID_NO")
	  REFERENCES "LHHCOM"."COMPANY" ("COMPANY_ID_NO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
