
  CREATE TABLE "LHHCOM"."COMPANY_FEE" 
   (	"COMPANY_ID_NO" NUMBER(9,0) NOT NULL ENABLE, 
	"COMPANY_FEE_TYPE_ID_NO" NUMBER(9,0) NOT NULL ENABLE, 
	"EFFECTIVE_START_DATE" DATE NOT NULL ENABLE, 
	"EFFECTIVE_END_DATE" DATE, 
	"FEE_AMT" NUMBER(9,0), 
	"FEE_PERC" NUMBER(9,0), 
	"FEE_FREQ_NO" NUMBER(5,2) NOT NULL ENABLE, 
	"FEE_COMMENT_DESC" VARCHAR2(200 CHAR), 
	"LAST_RUN_DATE" DATE,
	"LAST_UPDATE_DATETIME" DATE DEFAULT '01-JAN-2017' NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(50 CHAR) DEFAULT 1 NOT NULL ENABLE, 
	 CONSTRAINT "COMPANY_FEE_PK" PRIMARY KEY ("COMPANY_ID_NO", "EFFECTIVE_START_DATE", "COMPANY_FEE_TYPE_ID_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "COMPANY_FEE_FK" FOREIGN KEY ("COMPANY_ID_NO")
	  REFERENCES "LHHCOM"."COMPANY" ("COMPANY_ID_NO") DISABLE, 
	 CONSTRAINT "COMPANY_FEE_TYPE_FK" FOREIGN KEY ("COMPANY_FEE_TYPE_ID_NO")
	  REFERENCES "LHHCOM"."COMPANY_FEE_TYPE" ("COMPANY_FEE_TYPE_ID_NO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
