
  CREATE TABLE "LHHCOM"."COMPANY_TABLE" 
   (	"COMPANY_TABLE_ID_NO" NUMBER(9,0) NOT NULL ENABLE, 
	"COMPANY_TABLE_DESC" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"EFFECTIVE_START_DATE" DATE NOT NULL ENABLE ,
	"EFFECTIVE_END_DATE" DATE NOT NULL ENABLE,
	"LAST_UPDATE_DATETIME" DATE NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "COMPANY_TABLE_PK" PRIMARY KEY ("COMPANY_TABLE_ID_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
