
  CREATE TABLE "LHHCOM"."COMPANY_FUNCTION" 
   (	"COMPANY_ID_NO" NUMBER(9,0) NOT NULL ENABLE, 
	"COMPANY_TABLE_ID_NO" NUMBER(9,0) NOT NULL ENABLE, 
	"EFFECTIVE_START_DATE" DATE NOT NULL ENABLE, 
	"EFFECTIVE_END_DATE" DATE NOT NULL ENABLE, 
	"COMPANY_TABLE_TYPE_ID_NO" NUMBER(9,0) NOT NULL ENABLE, 
	"LAST_UPDATE_DATETIME" DATE NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "COMPANY_FUNCTION_PK" PRIMARY KEY ("COMPANY_ID_NO", "COMPANY_TABLE_ID_NO", "EFFECTIVE_START_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "COMPANY_TABLE_TYPE_FK" FOREIGN KEY ("COMPANY_TABLE_ID_NO", "COMPANY_TABLE_TYPE_ID_NO")
	  REFERENCES "LHHCOM"."COMPANY_TABLE_TYPE" ("COMPANY_TABLE_ID_NO", "COMPANY_TABLE_TYPE_ID_NO") ENABLE, 
	 CONSTRAINT "COMPANY_FUNCTION_FK" FOREIGN KEY ("COMPANY_ID_NO")
	  REFERENCES "LHHCOM"."COMPANY" ("COMPANY_ID_NO") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

 