  CREATE TABLE "LHHCOM"."COMPANY_REG_AUDIT" 
   (	
	"TRANSACTION_DATETIME" DATE, 
	"TRANSACTION_DESC" VARCHAR2(550 BYTE), 
	"TRANSACTION_USERNAME" VARCHAR2(50 BYTE),
	"COMPANY_ID_NO" NUMBER(9,0), 
	"COUNTRY_CODE" VARCHAR2(4 BYTE), 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE, 
	"VAT_NO" VARCHAR2(50),
	"REG_NO" VARCHAR2(50), 
	"FAIS_NO" VARCHAR2(50), 
	"EXPIRY_DATE" DATE, 
	"APPLICATION_DATE" DATE, 
	"AUTHORISE_DATE" DATE
   ) 
   TABLESPACE "USERS" ;
