-- Create Commisions Table Audits "LHHCOM"."COMPANY_AUDIT" 


/**
******** Create the COMPANY_AUDIT table
*/
CREATE TABLE "LHHCOM"."COMPANY_AUDIT" 
(
"TRANSACTION_DATETIME" DATE,
"TRANSACTION_DESC" VARCHAR2(550 BYTE),
"TRANSACTION_USERNAME" VARCHAR2(50 BYTE),
"COMPANY_ID_NO" NUMBER(9,0), 
"COMPANY_NAME" VARCHAR2(50 BYTE), 
"INTERNAL_BROKER_IND" CHAR(1 BYTE),
"VAT_REG_IND" VARCHAR2(1 BYTE), 
"WHT_CERT_IND" VARCHAR2(1 BYTE), 
"COMPANY_AGREEMENT_IND" VARCHAR2(1 BYTE), 
"REFERRAL_AGREEMENT_IND" VARCHAR2(1 BYTE), 
"COMPANY_REG_DOC_IND" VARCHAR2(1 BYTE), 
"BANK_DETAILS_IND" VARCHAR2(1 BYTE), 
"ID_DOC_IND" VARCHAR2(1 BYTE), 
"LETTER_OF_INTENT_IND" VARCHAR2(1 BYTE), 
"DIS_AGREEMENT_APPLICATION_IND" VARCHAR2(1 BYTE), 
"ADDRESS_IND" VARCHAR2(1 BYTE), 
"TAX_ID_NO_IND" VARCHAR2(1 BYTE), 
"PREFERRED_CURRENCY_CODE" VARCHAR2(5 BYTE), 
"CONSULTANT_ID_NO" NUMBER(9,0),
"EFFECTIVE_START_DATE" DATE, 
"EFFECTIVE_END_DATE" DATE
) SEGMENT CREATION DEFERRED 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
TABLESPACE "USERS" ;

/**
******** Check the structure of your table
*/
-- descr "LHHCOM"."COMPANY_AUDIT";

/**
******** Drop the structure of your COMPANY_AUDIT table if needed
*/
-- DROP TABLE "LHHCOM"."COMPANY_AUDIT";
