
  CREATE TABLE "LHHCOM"."COMPANY_COUNTRY" 
   (	"COMPANY_ID_NO" NUMBER(9,0) NOT NULL ENABLE, 
	"COUNTRY_CODE" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"EFFECTIVE_START_DATE" DATE NOT NULL ENABLE, 
	"EFFECTIVE_END_DATE" DATE NOT NULL ENABLE, 
	"HOLD_IND" VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE, 
	"MIN_PAYOUT_AMT" NUMBER(8,2) DEFAULT 0, 
	"LAST_UPDATE_DATETIME" DATE DEFAULT NULL NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(50 BYTE) DEFAULT NULL NOT NULL ENABLE, 
	 CONSTRAINT "COMPANY_COUNTRY_PK" PRIMARY KEY ("COMPANY_ID_NO", "COUNTRY_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "COMPANY_FK" FOREIGN KEY ("COMPANY_ID_NO")
	  REFERENCES "LHHCOM"."COMPANY" ("COMPANY_ID_NO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

