  CREATE TABLE "LHHCOM"."COMPANY_TABLE_AUDIT" 
   (	
	"TRANSACTION_DATETIME" DATE, 
	"TRANSACTION_DESC" VARCHAR2(550 BYTE), 
	"TRANSACTION_USERNAME" VARCHAR2(50 BYTE),
	"COMPANY_TABLE_ID_NO" NUMBER(9,0), 
	"COMPANY_TABLE_DESC" VARCHAR2(50 BYTE), 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE
   ) 
   TABLESPACE "USERS" ;
