 CREATE TABLE "LHHCOM"."COMPANY_CONTACT_TYPE_AUDIT" 
(
"TRANSACTION_DATETIME" DATE,
"TRANSACTION_DESC" VARCHAR2(550 BYTE),
"TRANSACTION_USERNAME" VARCHAR2(50 BYTE),
"COMPANY_CONTACT_TYPE_ID_NO" NUMBER(2,0),
"COMPANY_CONTACT_TYPE_DESC" VARCHAR2(250 BYTE),
"EFFECTIVE_START_DATE" DATE,
"EFFECTIVE_END_DATE" DATE
) SEGMENT CREATION DEFERRED 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
TABLESPACE "USERS" ;

/**
******** Check the structure of your table
*/
-- descr "LHHCOM"."COMPANY_CONTACT_TYPE_AUDIT";

/**
******** Drop the structure of your COMPANY_CONTACT_TYPE_AUDIT table if needed
*/
-- DROP TABLE "LHHCOM"."COMPANY_CONTACT_TYPE_AUDIT";

