-- Create Commisions Table Audits "LHHCOM"."COMPANY_CONTACT_AUDIT"

  CREATE TABLE "LHHCOM"."COMPANY_CONTACT_AUDIT" 
   (	
 	"TRANSACTION_DATETIME" DATE,
	"TRANSACTION_DESC" VARCHAR2(550 BYTE),
	"TRANSACTION_USERNAME" VARCHAR2(50 BYTE),
  "COMPANY_ID_NO" NUMBER(9,0),
	"COUNTRY_CODE" VARCHAR2(4 CHAR),
	"COMPANY_CONTACT_TYPE_ID_NO" NUMBER(2,0),
	"EFFECTIVE_START_DATE" DATE,
	"EFFECTIVE_END_DATE" DATE,
	"CONTACT_NAME" VARCHAR2(250 CHAR), 
	"CONTACT_CELLPHONE_NO" VARCHAR2(30 CHAR), 
	"CONTACT_EMAIL" VARCHAR2(250 CHAR), 
	"CONTACT_FAX_NO" VARCHAR2(30 CHAR), 
	"CONTACT_TELEPHONE_NO" VARCHAR2(30 CHAR), 
	"CONTACT_DESC" VARCHAR2(250 CHAR)
  ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  
/**
******** Check the structure of your table
*/
-- descr "LHHCOM"."COMPANY_CONTACT_AUDIT";

/**
******** Drop the structure of your COMPANY_AUDIT table if needed
*/
-- DROP TABLE "LHHCOM"."COMPANY_CONTACT_AUDIT";  
  
