  CREATE TABLE "LHHCOM"."COMPANY" 
   (	"COMPANY_ID_NO" NUMBER(9,0) NOT NULL ENABLE, 
	"COMPANY_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"INTERNAL_BROKER_IND" CHAR(1 BYTE) DEFAULT NULL NOT NULL ENABLE, 
	"CONSULTANT_ID_NO" NUMBER(9,0), 
	"VAT_REG_IND" VARCHAR2(1 BYTE), 
	"WHT_CERT_IND" VARCHAR2(1 BYTE), 
	"COMPANY_AGREEMENT_IND" VARCHAR2(1 BYTE), 
	"REFERRAL_AGREEMENT_IND" VARCHAR2(1 BYTE), 
	"COMPANY_REG_DOC_IND" VARCHAR2(1 BYTE), 
	"BANK_DETAILS_IND" VARCHAR2(1 BYTE), 
	"ID_DOC_IND" VARCHAR2(1 BYTE), 
	"LETTER_OF_INTENT_IND" VARCHAR2(1 BYTE), 
	"DIS_AGREEMENT_APPLICATION_IND" VARCHAR2(1 BYTE), 
	"ADDRESS_IND" VARCHAR2(1 BYTE), 
	"TAX_ID_NO_IND" VARCHAR2(1 BYTE), 
	"EFFECTIVE_START_DATE" DATE, 
	"EFFECTIVE_END_DATE" DATE, 
	"LAST_UPDATE_DATETIME" DATE DEFAULT NULL NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(50 BYTE) DEFAULT NULL NOT NULL ENABLE, 
	"PREFERRED_CURRENCY_CODE" VARCHAR2(5 BYTE), 

	 CONSTRAINT "COMPANY_PK" PRIMARY KEY ("COMPANY_ID_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;