  CREATE TABLE "LHHCOM"."COUNTRY_TAXES" 
   (
    "COUNTRY_CODE"             VARCHAR2(4 CHAR)                         NOT NULL ENABLE
   ,"ACCREDITATION_TYPE_ID_NO" NUMBER(2,0)                              NOT NULL ENABLE
   ,"EFFECTIVE_START_DATE"     DATE               DEFAULT '01-JAN-1900' NOT NULL ENABLE
   ,"EFFECTIVE_END_DATE"       DATE               DEFAULT '31-JAN-3100' NOT NULL ENABLE
   ,"ACCRED_LOCAL"             VARCHAR2(10 CHAR)
   ,"ACCRED_MULTI"             VARCHAR2(10 CHAR)
   ,"NO_ACCR_LOCAL"            VARCHAR2(10 CHAR)
   ,"NO_ACCR_MULTI"            VARCHAR2(10 CHAR)
   ,"LAST_UPDATE_DATETIME"     DATE               DEFAULT SYSDATE       NOT NULL ENABLE
   ,"USERNAME"                 VARCHAR2(50 BYTE)  DEFAULT NULL          NOT NULL ENABLE
   ,CONSTRAINT "COUNTRY_TAXES_PK"
      PRIMARY KEY ("COUNTRY_CODE", "ACCREDITATION_TYPE_ID_NO", "EFFECTIVE_START_DATE")
      ENABLE
   ,CONSTRAINT "COUNTRY_TAX_ACCREDITATION_FK"
      FOREIGN KEY ("ACCREDITATION_TYPE_ID_NO")
      REFERENCES "LHHCOM"."ACCREDITATION_TYPE" ("ACCREDITATION_TYPE_ID_NO")
      ENABLE
   );
