  CREATE TABLE "LHHCOM"."COUNTRY_TAXES_AUDIT" 
   (
    "TRANSACTION_DATETIME"     DATE 
   ,"TRANSACTION_DESC"         VARCHAR2(550 BYTE) 
   ,"TRANSACTION_USERNAME"     VARCHAR2(50 BYTE)
   ,"COUNTRY_CODE"             VARCHAR2(4 CHAR)
   ,"ACCREDITATION_TYPE_ID_NO" NUMBER(2,0)
   ,"EFFECTIVE_START_DATE"     DATE
   ,"EFFECTIVE_END_DATE"       DATE
   ,"ACCRED_LOCAL"             VARCHAR2(10 CHAR)
   ,"ACCRED_MULTI"             VARCHAR2(10 CHAR)
   ,"NO_ACCR_LOCAL"            VARCHAR2(10 CHAR)
   ,"NO_ACCR_MULTI"            VARCHAR2(10 CHAR)
   );
