create table LHHCOM.COMMS_CALC_SNAPSHOT_DM AS SELECT * FROM COMMS_CALC_SNAPSHOT WHERE country_CODE = 'BLAH';
create index LHHCOM.comms_calc_snap_dm_idx1 on comms_calc_snapshot_dm(COUNTRY_CODE,COMPANY_ID_NO);
create index LHHCOM.comms_calc_snap_dm_idx2 on comms_calc_snapshot_dm(GROUP_CODE);
create index LHHCOM.comms_calc_snap_dm_idx3 on comms_calc_snapshot_dm(CALCULATION_DATETIME);
create table LHHCOM.INVOICE_DM AS SELECT * FROM INVOICE WHERE INVOICE_NO = '999999999';
create index LHHCOM.invoice_dm_idx1 on invoice_dm(COUNTRY_CODE,COMPANY_ID_NO);
create index LHHCOM.invoice_dm_idx2 on invoice_dm(INVOICE_NO);
create index LHHCOM.invoice_dm_idx3 on invoice_dm(INVOICE_DATE);
create table LHHCOM.INVOICE_DETAIL_DM AS SELECT * FROM INVOICE_DETAIL WHERE INVOICE_NO = '99999999';
create index LHHCOM.invoice_det_dm_idx2 on invoice_detail_dm(INVOICE_NO);
CREATE TABLE LHHCOM.COMMS_SNAPSHOT_INVUPD_DM
(
 COMPANY_ID_NO          NUMBER,
 INVOICE_NO             NUMBER,
 PAYMENT_RECEIVE_DATE   DATE,
 EXCH_CURRENCY_CODE     VARCHAR2(20),
 INVOICE_CURRENCY_CODE  VARCHAR2(20),
 TOTAL_COMMS_CALC       NUMBER,
 TOTAL_INVOICE          NUMBER,
 DIFF_TOTAL             NUMBER,
 TOTAL_COMMS_EXCH       NUMBER,
 TOTAL_INV_EXCH         NUMBER,
 DIFF_EXCH_TOTAL        NUMBER,
 TOTAL_INV_PAYMENT      NUMBER,
 MIN_CALC_DATE          DATE,
 MAX_CALC_DATE          DATE,
 COMMS_CALC_SNAPSHOT_NO NUMBER
);
/
DROP TABLE LHHCOM.COMM_HUB_JOBS;
/
CREATE TABLE LHHCOM.COMM_HUB_JOBS 
(
 JOB_ID        NUMBER DEFAULT LHHCOM.COMMISSIONS_JOB_ID.NEXTVAL NOT NULL,
 JOB_NAME      VARCHAR2(40),
 JOB_DESC      VARCHAR2(200),
 JOB_EXECUTABLE VARCHAR2(100),
 JOB_TYPE      VARCHAR2(30),
 FACET_NAME VARCHAR2(20),
 FROM_DATE     DATE,
 TO_DATE       DATE,
 ENABLED VARCHAR2(1)
 );
 /