  CREATE TABLE "LHHCOM"."DNLD_COMPANY_ADDRESS" 
   (
  "INTERF_SYSTEM_ID_NO" NUMBER(9,0) DEFAULT 1 NOT NULL ENABLE,
	"COMPANY_ID_NO" NUMBER(9,0) NOT NULL ENABLE, 
	"COUNTRY_CODE" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"ADDRESS_TYPE_CODE" CHAR(1 BYTE) NOT NULL ENABLE, 
	"EFFECTIVE_START_DATE" DATE NOT NULL ENABLE, 
	"STAMP_DATETIME" DATE NOT NULL ENABLE, 
	"STAMP_IND" CHAR(1 BYTE) NOT NULL ENABLE, 
	"BATCH_NO" NUMBER(9,0), 
	"LAST_UPDATE_DATETIME" DATE NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "DNLD_COMPANY_ADDRESS_PK" PRIMARY KEY ("INTERF_SYSTEM_ID_NO", "COMPANY_ID_NO", "COUNTRY_CODE", "ADDRESS_TYPE_CODE", "STAMP_DATETIME", "EFFECTIVE_START_DATE") ENABLE
   );
