  CREATE TABLE "LHHCOM"."DNLD_TRN" 
   ("DNLD_TRN_NO" NUMBER(15,0) NOT NULL ENABLE, 
	"DETAIL_SEQ_NO" NUMBER(15,0) NOT NULL ENABLE, 
  "INTERF_SYSTEM_ID_NO" NUMBER(9,0) NOT NULL ENABLE, 
	"TRN_TYPE_NO" NUMBER(9,0) NOT NULL ENABLE, 
	"TRN_SUB_TYPE_CODE" VARCHAR2(20 CHAR), 
	"DATALINE" VARCHAR2(4000 CHAR), 
  "BATCH_NO" NUMBER(9,0), 
	"LAST_UPDATE_DATETIME" DATE NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "DNLD_TRN_NO" PRIMARY KEY ("DNLD_TRN_NO", "INTERF_SYSTEM_ID_NO", "DETAIL_SEQ_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "DNLD_TRN_FK" FOREIGN KEY ("INTERF_SYSTEM_ID_NO", "TRN_TYPE_NO", "TRN_SUB_TYPE_CODE")
	  REFERENCES "UTIL"."INTERF_SYS_TRN_TP_SUB_TYPE" ("INTERF_SYSTEM_ID_NO", "TRN_TYPE_NO", "TRN_SUB_TYPE_CODE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
