
  CREATE TABLE "LHHCOM"."DNLD_COMPANY_CONTACT" 
   (
  "INTERF_SYSTEM_ID_NO" NUMBER(9,0) DEFAULT 1 NOT NULL ENABLE,
	"COMPANY_ID_NO" NUMBER(9,0) NOT NULL ENABLE, 
	"COUNTRY_CODE" VARCHAR2(4 CHAR) NOT NULL ENABLE, 
	"COMPANY_CONTACT_TYPE_ID_NO" NUMBER(2,0) NOT NULL ENABLE, 
	"EFFECTIVE_START_DATE" TIMESTAMP NOT NULL ENABLE, 
	"STAMP_DATETIME" DATE NOT NULL ENABLE, 
	"STAMP_IND" CHAR(1 CHAR) NOT NULL ENABLE, 
	"BATCH_NO" NUMBER(9,0) DEFAULT 0, 
	"LAST_UPDATE_DATETIME" DATE NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "DNLD_COMPANY_CONTACT_PK" PRIMARY KEY ("INTERF_SYSTEM_ID_NO", "COMPANY_ID_NO", "COUNTRY_CODE", "COMPANY_CONTACT_TYPE_ID_NO", "EFFECTIVE_START_DATE", "STAMP_DATETIME") ENABLE
   );
