-- DROP TABLE EXT_COMMS_PAYMENTS_RECEIVED;

CREATE TABLE EXT_COMMS_PAYMENTS_RECEIVED 
       ("APPLICATION_ID" NUMBER(38),
        "FINANCE_RECEIPT_NO" VARCHAR2(100), 
        "GROUP_CODE" VARCHAR2(100 BYTE), 
        "COUNTRY_CODE" VARCHAR2(4 BYTE),
        "PRODUCT_CODE" VARCHAR2(100 BYTE), 
        "POLICY_CODE" VARCHAR2(100 BYTE), 
        "PERSON_CODE" VARCHAR2(100 BYTE), 
        "CONTRIBUTION_DATE" DATE , 
        "FINANCE_RECEIPT_DATE" DATE, 
        "FINANCE_INVOICE_NO" NUMBER(38), 
        "FINANCE_INVOICE_DATE" DATE, 
        "FINANCE_RECEIPT_AMT" NUMBER(38,2) 
       )
       
      ORGANIZATION EXTERNAL (
      TYPE ORACLE_LOADER
      DEFAULT DIRECTORY LOGDATA
      ACCESS PARAMETERS (
        RECORDS DELIMITED BY NEWLINE
        BADFILE LOGDATA:'ext_comms_payments_received.bad'
        LOGFILE LOGDATA:'ext_comms_payments_received.log'
        FIELDS TERMINATED BY ','
        MISSING FIELD VALUES ARE NULL
      )
      LOCATION (LOGDATA:'comms_payments_received.dat')
    )
    PARALLEL 5
REJECT LIMIT UNLIMITED;
