  CREATE TABLE LHHCOM.INVOICE_PAYMENTS_AUDIT
   (
	  TRANSACTION_DATETIME     DATE                DEFAULT SYSDATE
	 ,TRANSACTION_DESC         VARCHAR2(550 BYTE) 
	 ,TRANSACTION_USERNAME     VARCHAR2(50 BYTE)   DEFAULT USER
   ,INVOICE_NO               NUMBER(9,0)        
   ,COMPANY_ID_NO            NUMBER(9,0)
   ,FUSION_REPORT_UID        NUMBER(9,0)        
   ,FUSION_REPORT_REFERENCE  VARCHAR2(200 BYTE)
   ,P_BUSINESS_UNIT          VARCHAR2(200 BYTE)
   ,SUPPLIER_NUMBER          VARCHAR2(30 BYTE)
   ,INVOICE_ID               VARCHAR2(30 BYTE)
   ,VENDOR_SITE_CODE         VARCHAR2(30 BYTE)
   ,INVOICE_NUM              VARCHAR2(30 BYTE)
   ,INVOICE_LINE_AMOUNT      NUMBER(22,9)
   ,LINE_NUMBER              VARCHAR2(30 BYTE)
   ,LINE_TYPE_LOOKUP_CODE    VARCHAR2(30 BYTE)
   ,INVOICE_LINE_DESCRIPTION VARCHAR2(200 BYTE)
   ,REVERSAL_FLAG            VARCHAR2(30 BYTE)
   ,EXCHANGE_RATE_TYPE       VARCHAR2(30 BYTE)
   ,EXCHANGE_RATE            VARCHAR2(30 BYTE)
   ,INVOICE_CURRENCY_CODE    VARCHAR2(30 BYTE)
   ,PAYMENT_CURRENCY_CODE    VARCHAR2(30 BYTE)
   ,DATE_ACTIONED            DATE
   ,DATE_STAMP               DATE
	 ,LAST_UPDATE_DATETIME     DATE
   );