CREATE TABLE "LHHCOM"."INVOICE" 
   ("INVOICE_NO" NUMBER(9,0) NOT NULL ENABLE, 
	"INVOICE_DATE" DATE NOT NULL ENABLE, 
	"PAYMENT_RECEIVE_DATE" DATE NOT NULL ENABLE, 
	"COUNTRY_CODE" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"COMPANY_ID_NO" NUMBER(9,0) NOT NULL ENABLE, 
	"INVOICE_TYPE_ID_NO" NUMBER(2,0) NOT NULL ENABLE,
-- Helen LS-1361 add INV_TAX_CODES 
  "INVOICE_TAX_CODES" VARCHAR2(50 BYTE),
-- Helen LS-1361  
	"RELEASE_DATE" DATE, 
	"RELEASE_HOLD_REASON" VARCHAR2(250 BYTE), 
	"PAYMENT_DATE" DATE, 
	"PAYMENT_REJECT_DATE" DATE, 
	"PAYMENT_REJECT_DESC" VARCHAR2(500 BYTE),
	"PAYMENT_AMT" NUMBER(22,9), 
	"PAYMENT_EXCH_RATE" NUMBER(15,9), 
	"CURRENCY_CODE" VARCHAR2(4 BYTE), 
  "INVOICE_TAX_CODES" VARCHAR2(50 BYTE),
	"LAST_UPDATE_DATETIME" DATE NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "INVOICE_PK" PRIMARY KEY ("INVOICE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE,
   CONSTRAINT "INVOICE_COMPANY_FK" FOREIGN KEY ("COMPANY_ID_NO")
	  REFERENCES "LHHCOM"."COMPANY" ("COMPANY_ID_NO") ENABLE,
      CONSTRAINT "INVOICE_INV_TYPE_FK" FOREIGN KEY ("INVOICE_TYPE_ID_NO")
	  REFERENCES "LHHCOM"."INVOICE_TYPE" ("INVOICE_TYPE_ID_NO") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
