CREATE TABLE INVOICE_PAYMENTS_BCK AS
(SELECT * FROM INVOICE_PAYMENTS);
/
DROP TABLE INVOICE_PAYMENTS;
/
CREATE TABLE INVOICE_PAYMENTS (
COMPANY_ID_NO	           NUMBER,		
COMPANY_NAME               VARCHAR2(1000),
BUSINESS_UNIT              VARCHAR2(500),
INVOICE_NO                 NUMBER,
INVOICE_DATE               DATE,
INVOICE_LINE_AMOUNT	       NUMBER,
LINE_NUMBER	               NUMBER,
LINE_TYPE_LOOKUP_CODE	   VARCHAR2(50),
INVOICE_LINE_DESCRIPTION   VARCHAR2(500),
CHECK_NUMBER               VARCHAR2(100),
CHECK_DATE                 DATE, 
SOURCE                     VARCHAR2(200),
PAYMENT_AMT                NUMBER,
PAYMENT_TYPE               VARCHAR2(200),
PREPAY_INVOICE_NUMBER      VARCHAR2(500),
REVERSAL_FLAG			   VARCHAR2(1),
INVOICE_CURRENCY_CODE	   VARCHAR2(10),
PAYMENT_CURRENCY_CODE	   VARCHAR2(10),
PROCESSED                  VARCHAR2(1) DEFAULT 'N',
DATE_ACTIONED	           DATE,
LAST_UPDATE_DATETIME	   DATE,
USERNAME                   VARCHAR2(200)
);
/
CREATE INDEX INVPAYIDX1 ON INVOICE_PAYMENTS(INVOICE_NO);
CREATE INDEX INVPAYIDX2 ON INVOICE_PAYMENTS(COMPANY_ID_NO);
CREATE UNIQUE INDEX INVPAYUNQ ON INVOICE_PAYMENTS(INVOICE_NO, CHECK_NUMBER,REVERSAL_FLAG,LINE_TYPE_LOOKUP_CODE,CHECK_DATE,PAYMENT_AMT);