
  CREATE TABLE "LHHCOM"."INVOICE_DETAIL" 
   ("INVOICE_NO" NUMBER(9,0) NOT NULL ENABLE, 
	"FEE_TYPE_ID_NO" NUMBER(9,0) NOT NULL ENABLE, 
	"FEE_TYPE_AMT" NUMBER(22,9) NOT NULL ENABLE, 
	"FEE_TYPE_EXCH_AMT" NUMBER(22,9) NOT NULL ENABLE,	
	"FEE_TYPE_DESC" VARCHAR2(200 BYTE), 
	"LAST_UPDATE_DATETIME" DATE NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "INVOICE_DETAIL_PK" PRIMARY KEY ("INVOICE_NO", "FEE_TYPE_ID_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE,
   CONSTRAINT "INVOICE_DETAIL_FK" FOREIGN KEY ("INVOICE_NO")
	  REFERENCES "LHHCOM"."INVOICE" ("INVOICE_NO") ENABLE
   
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
