/*  Dropping all old tables
  DROP TABLE "LHHCOM"."OHI_COMM_PERC_AUDIT" ;
  DROP TABLE "LHHCOM"."OHI_COMM_PERC" ;
  DROP TABLE "LHHCOM"."OHI_HOLD_IND_AUDIT" ;
  DROP TABLE "LHHCOM"."OHI_HOLD_IND" ;
*/

  CREATE TABLE "LHHCOM"."OHI_COMM_PERC" 
   (
    "PRODUCT_CODE"            VARCHAR2(30 BYTE) 
   ,"POEP_ID"                 NUMBER(14,0)       
   ,"INSE_CODE"               VARCHAR2(30 BYTE)  
   ,"POLICY_CODE"             VARCHAR2(30 BYTE)  
   ,"GROUP_CODE"              VARCHAR2(30 BYTE)  
   ,"BROKER_ID_NO"            NUMBER(9,0)       
   ,"COMPANY_ID_NO"           NUMBER(9,0)       
   ,"COMM_PERC"               NUMBER(4,2)        NOT NULL ENABLE
   ,"COMM_DESC"               VARCHAR2(100 BYTE)
   ,"EFFECTIVE_START_DATE"    DATE               DEFAULT '01-JAN-1900' NOT NULL ENABLE
   ,"EFFECTIVE_END_DATE"      DATE               DEFAULT '31-JAN-3100' NOT NULL ENABLE
   ,"CREATED_USERNAME"        VARCHAR2(50 BYTE)  NOT NULL ENABLE
   ,"AUTH_USERNAME"           VARCHAR2(50 BYTE)  
      ,"REJECT_USERNAME"         VARCHAR2(50 BYTE)  
   ,"LAST_UPDATE_DATETIME"    DATE               DEFAULT SYSDATE NOT NULL ENABLE
   ,"USERNAME"                VARCHAR2(20 BYTE)  DEFAULT USER NOT NULL ENABLE
/*
   ,CONSTRAINT "OHI_COMM_PERC_PROD_FK" 
      FOREIGN KEY ("PRODUCT_CODE")
      REFERENCES "LHHCOM"."OHI_PRODUCTS" ("PRODUCT_CODE")
      ENABLE
 	 ,CONSTRAINT "OHI_COMM_PERC_POEP_FK" 
      FOREIGN KEY ("POEP_ID")
      REFERENCES "LHHCOM"."OHI_ENROLLMENT_PRODUCTS" ("POEP_ID")
      ENABLE
 	 ,CONSTRAINT "OHI_COMM_PERC_INSE_FK" 
      FOREIGN KEY ("INSE_CODE")
      REFERENCES "LHHCOM"."OHI_INSURED_ENTITIES" ("INSE_CODE")
      ENABLE
 	 ,CONSTRAINT "OHI_COMM_PERC_POLI_FK" 
      FOREIGN KEY ("POLICY_CODE")
      REFERENCES "LHHCOM"."OHI_POLICIES" ("POLICY_CODE")
      ENABLE
 	 ,CONSTRAINT "OHI_COMM_PERC_GROUP_FK" 
      FOREIGN KEY ("GROUP_CODE")
      REFERENCES "LHHCOM"."OHI_GROUPS" ("GROUP_CODE")
      ENABLE
 	 ,CONSTRAINT "OHI_COMM_PERC_BROKER_FK" 
      FOREIGN KEY ("BROKER_ID_NO")
      REFERENCES "LHHCOM"."BROKER" ("BROKER_ID_NO")
      ENABLE
 	 ,CONSTRAINT "OHI_COMM_PERC_COMPANY_FK" 
      FOREIGN KEY ("COMPANY_ID_NO")
      REFERENCES "LHHCOM"."COMPANY" ("COMPANY_ID_NO")
      ENABLE
*/
   );

  CREATE TABLE "LHHCOM"."OHI_COMM_PERC_AUDIT" 
   (	
	  "TRANSACTION_DATETIME"    DATE               DEFAULT SYSDATE
	 ,"TRANSACTION_DESC"        VARCHAR2(550 BYTE) 
	 ,"TRANSACTION_USERNAME"    VARCHAR2(50 BYTE)  DEFAULT USER
   ,"PRODUCT_CODE"            VARCHAR2(30 BYTE) 
   ,"POEP_ID"                 NUMBER(14,0)       
   ,"INSE_CODE"               VARCHAR2(30 BYTE)  
   ,"POLICY_CODE"             VARCHAR2(30 BYTE)  
   ,"GROUP_CODE"              VARCHAR2(30 BYTE)  
   ,"BROKER_ID_NO"            NUMBER(9,0)       
   ,"COMPANY_ID_NO"           NUMBER(9,0)       
   ,"COMM_PERC"               NUMBER(4,2)        
   ,"COMM_DESC"               VARCHAR2(100 BYTE)
   ,"EFFECTIVE_START_DATE"    DATE               
   ,"EFFECTIVE_END_DATE"      DATE               
   ,"CREATED_USERNAME"        VARCHAR2(50 BYTE)
   ,"AUTH_USERNAME"           VARCHAR2(50 BYTE)
   ,"REJECT_USERNAME"         VARCHAR2(50 BYTE)     
   );

  CREATE TABLE "LHHCOM"."OHI_HOLD_IND" 
   (
    "PRODUCT_CODE"            VARCHAR2(30 BYTE) 
   ,"POEP_ID"                 NUMBER(14,0)       
   ,"INSE_CODE"               VARCHAR2(30 BYTE)  
   ,"POLICY_CODE"             VARCHAR2(30 BYTE)  
   ,"GROUP_CODE"              VARCHAR2(30 BYTE)  
   ,"BROKER_ID_NO"            NUMBER(9,0)       
   ,"COMPANY_ID_NO"           NUMBER(9,0)       
   ,"HOLD_IND"                VARCHAR2(1 BYTE)   NOT NULL ENABLE
   ,"HOLD_REASON"             VARCHAR2(100 BYTE)
   ,"EFFECTIVE_START_DATE"    DATE               DEFAULT '01-JAN-1900' NOT NULL ENABLE
   ,"EFFECTIVE_END_DATE"      DATE               DEFAULT '31-JAN-3100' NOT NULL ENABLE
   ,"LAST_UPDATE_DATETIME"    DATE               DEFAULT SYSDATE NOT NULL ENABLE
   ,"USERNAME"                VARCHAR2(20 BYTE)  DEFAULT USER NOT NULL ENABLE
/*
   ,CONSTRAINT "OHI_HOLD_IND_PROD_FK" 
      FOREIGN KEY ("PRODUCT_CODE")
      REFERENCES "LHHCOM"."OHI_PRODUCTS" ("PRODUCT_CODE")
      ENABLE
 	 ,CONSTRAINT "OHI_HOLD_IND_POEP_FK" 
      FOREIGN KEY ("POEP_ID")
      REFERENCES "LHHCOM"."OHI_ENROLLMENT_PRODUCTS" ("POEP_ID")
      ENABLE
 	 ,CONSTRAINT "OHI_HOLD_IND_INSE_FK" 
      FOREIGN KEY ("INSE_CODE")
      REFERENCES "LHHCOM"."OHI_INSURED_ENTITIES" ("INSE_CODE")
      ENABLE
 	 ,CONSTRAINT "OHI_HOLD_IND_POLI_FK" 
      FOREIGN KEY ("POLICY_CODE")
      REFERENCES "LHHCOM"."OHI_POLICIES" ("POLICY_CODE")
      ENABLE
 	 ,CONSTRAINT "OHI_HOLD_IND_GROUP_FK" 
      FOREIGN KEY ("GROUP_CODE")
      REFERENCES "LHHCOM"."OHI_GROUPS" ("GROUP_CODE")
      ENABLE
 	 ,CONSTRAINT "OHI_HOLD_IND_BROKER_FK" 
      FOREIGN KEY ("BROKER_ID_NO")
      REFERENCES "LHHCOM"."BROKER" ("BROKER_ID_NO")
      ENABLE
 	 ,CONSTRAINT "OHI_HOLD_IND_COMPANY_FK" 
      FOREIGN KEY ("COMPANY_ID_NO")
      REFERENCES "LHHCOM"."COMPANY" ("COMPANY_ID_NO")
      ENABLE
*/
   );

  CREATE TABLE "LHHCOM"."OHI_HOLD_IND_AUDIT" 
   (	
	  "TRANSACTION_DATETIME"    DATE               DEFAULT SYSDATE
	 ,"TRANSACTION_DESC"        VARCHAR2(550 BYTE) 
	 ,"TRANSACTION_USERNAME"    VARCHAR2(50 BYTE)  DEFAULT USER
   ,"PRODUCT_CODE"            VARCHAR2(30 BYTE) 
   ,"POEP_ID"                 NUMBER(14,0)       
   ,"INSE_CODE"               VARCHAR2(30 BYTE)  
   ,"POLICY_CODE"             VARCHAR2(30 BYTE)  
   ,"GROUP_CODE"              VARCHAR2(30 BYTE)  
   ,"BROKER_ID_NO"            NUMBER(9,0)       
   ,"COMPANY_ID_NO"           NUMBER(9,0)       
   ,"HOLD_IND"                VARCHAR2(1 BYTE)   
   ,"HOLD_REASON"             VARCHAR2(100 BYTE)
   ,"EFFECTIVE_START_DATE"    DATE               
   ,"EFFECTIVE_END_DATE"      DATE               
   );
