  CREATE TABLE "LHHCOM"."OHI_GROUPS_AUDIT" 
   (	
	  "TRANSACTION_DATETIME"    DATE 
	 ,"TRANSACTION_DESC"        VARCHAR2(550 BYTE) 
	 ,"TRANSACTION_USERNAME"    VARCHAR2(50 BYTE)
   ,"GRAC_ID"                 NUMBER(14,0)       
   ,"GROUP_CODE"              VARCHAR2(30 BYTE)  
   ,"GROUP_NAME"              VARCHAR2(100 BYTE)
   ,"EFFECTIVE_START_DATE"    DATE               
   ,"EFFECTIVE_END_DATE"      DATE               
   ,"PARENTGROUP_CODE"        VARCHAR2(30 BYTE)
   ,"GROUP_TYPE"              VARCHAR2(10 BYTE)
   ,"GROUP_CLASS"             VARCHAR2(4 BYTE)
   ,"PREFERRED_CURRENCY_CODE" VARCHAR2(4 BYTE)
   ,"COUNTRY_CODE"            VARCHAR2(4 BYTE)
   );
