  CREATE TABLE "LHHCOM"."OHI_GROUPS" 
   (
    "GRAC_ID"                 NUMBER(14,0)       NOT NULL ENABLE
   ,"GROUP_CODE"              VARCHAR2(30 BYTE)  NOT NULL ENABLE
   ,"GROUP_NAME"              VARCHAR2(100 BYTE)
   ,"EFFECTIVE_START_DATE"    DATE               DEFAULT '01-JAN-1900' NOT NULL ENABLE
   ,"EFFECTIVE_END_DATE"      DATE               DEFAULT '31-JAN-3100' NOT NULL ENABLE
   ,"PARENTGROUP_CODE"        VARCHAR2(30 BYTE)
   ,"GROUP_TYPE"              VARCHAR2(10 BYTE)
   ,"GROUP_CLASS"             VARCHAR2(4 BYTE)
   ,"PREFERRED_CURRENCY_CODE" VARCHAR2(4 BYTE)
   ,"COUNTRY_CODE"            VARCHAR2(4 BYTE)
   ,"LAST_UPDATE_DATETIME"    DATE               DEFAULT sysdate NOT NULL ENABLE
   ,"USERNAME"                VARCHAR2(20 BYTE)  DEFAULT 'USERNAME' NOT NULL ENABLE
   ,CONSTRAINT "OHI_GROUPS_PK"
      PRIMARY KEY ("GRAC_ID")
      ENABLE
   );
