  CREATE TABLE "LHHCOM"."OHI_PRODUCTS_AUDIT" 
   (	
	  "TRANSACTION_DATETIME"    DATE 
	 ,"TRANSACTION_DESC"        VARCHAR2(550 BYTE) 
	 ,"TRANSACTION_USERNAME"    VARCHAR2(50 BYTE)
   ,"ENPR_ID"                 NUMBER(14,0)      
   ,"PRODUCT_CODE"            VARCHAR2(30 BYTE)  
   ,"COUNTRY_CODE"            VARCHAR2(4 BYTE)
   ,"PRODUCT_NAME"            VARCHAR2(30 BYTE)
   ,"PRODUCT_DESCR"           VARCHAR2(200 BYTE)
   );
