  CREATE TABLE "LHHCOM"."OHI_POLICY_BROKERS" 
   (
    "POLI_ID"                 NUMBER(14,0)       NOT NULL ENABLE
   ,"POBR_ID"                 NUMBER(14,0)       NOT NULL ENABLE
   ,"BROKER_ID_NO"            NUMBER(9,0)       
   ,"COMPANY_ID_NO"           NUMBER(9,0)       
   ,"EFFECTIVE_START_DATE"    DATE               DEFAULT '01-JAN-1900' NOT NULL ENABLE
   ,"EFFECTIVE_END_DATE"      DATE               DEFAULT '31-JAN-3100' NOT NULL ENABLE
   ,"LAST_UPDATE_DATETIME"    DATE               DEFAULT sysdate NOT NULL ENABLE
   ,"USERNAME"                VARCHAR2(20 BYTE)  DEFAULT USER NOT NULL ENABLE
   ,CONSTRAINT "OHI_POLICY_BROKERS_PK"
      PRIMARY KEY ("POLI_ID", "POBR_ID")
      ENABLE
   );
   
   ALTER TABLE "LHHCOM"."OHI_POLICY_BROKERS" 
    ADD
   ( 	
 	  CONSTRAINT "OHI_POLICY_BROKERS_BROKER_FK"
      FOREIGN KEY ("BROKER_ID_NO")
      REFERENCES "LHHCOM"."BROKER" ("BROKER_ID_NO")
      ENABLE
  ,CONSTRAINT "OHI_POLICY_BROKERS_COMPANY_FK"
      FOREIGN KEY ("COMPANY_ID_NO")
      REFERENCES "LHHCOM"."COMPANY" ("COMPANY_ID_NO")
      ENABLE
 	 ,CONSTRAINT "OHI_POLICY_BROKERS_POLICIES_FK" 
      FOREIGN KEY ("POLI_ID")
      REFERENCES "LHHCOM"."OHI_POLICIES" ("POLI_ID")
      ENABLE
   );