/* --  Dropping all old tables
  DROP TABLE "LHHCOM"."OHI_ENROLLMENT_PRODUCTS_AUDIT";
  DROP TABLE "LHHCOM"."OHI_ENROLLMENT_PRODUCTS" ;
  DROP TABLE "LHHCOM"."OHI_PRODUCTS_AUDIT" ;
  DROP TABLE "LHHCOM"."OHI_PRODUCTS" ;
  DROP TABLE "LHHCOM"."OHI_POLICY_ENROLLMENTS_AUDIT" ;
  DROP TABLE "LHHCOM"."OHI_POLICY_ENROLLMENTS" ;
  DROP TABLE "LHHCOM"."OHI_INSURED_ENTITIES_AUDIT" ;
  DROP TABLE "LHHCOM"."OHI_INSURED_ENTITIES" ;
  DROP TABLE "LHHCOM"."OHI_POLICYHOLDERS_AUDIT" ;
  DROP TABLE "LHHCOM"."OHI_POLICYHOLDERS" ;
  DROP TABLE "LHHCOM"."OHI_POLICY_BROKERS_AUDIT" ;
  DROP TABLE "LHHCOM"."OHI_POLICY_BROKERS" ;
  DROP TABLE "LHHCOM"."OHI_POLICY_GROUPS_AUDIT" ;
  DROP TABLE "LHHCOM"."OHI_POLICY_GROUPS" ;
  DROP TABLE "LHHCOM"."OHI_POLICIES_AUDIT" ;
  DROP TABLE "LHHCOM"."OHI_POLICIES" ;
  DROP TABLE "LHHCOM"."OHI_GROUPS_AUDIT" ;
  DROP TABLE "LHHCOM"."OHI_GROUPS" ;
-- */

  CREATE TABLE "LHHCOM"."OHI_GROUPS" 
   (
    "GRAC_ID"                 NUMBER(14,0)       NOT NULL ENABLE
   ,"GROUP_CODE"              VARCHAR2(30 BYTE)  NOT NULL ENABLE
   ,"GROUP_NAME"              VARCHAR2(100 BYTE)
   ,"EFFECTIVE_START_DATE"    DATE               DEFAULT '01-JAN-1900' NOT NULL ENABLE
   ,"EFFECTIVE_END_DATE"      DATE               DEFAULT '31-JAN-3100' NOT NULL ENABLE
   ,"PARENTGROUP_CODE"        VARCHAR2(30 BYTE)
   ,"GROUP_TYPE"              VARCHAR2(10 BYTE)
   ,"GROUP_CLASS"             VARCHAR2(4 BYTE)
   ,"PREFERRED_CURRENCY_CODE" VARCHAR2(4 BYTE)
   ,"COUNTRY_CODE"            VARCHAR2(4 BYTE)
   ,"LAST_UPDATE_DATETIME"    DATE               DEFAULT sysdate NOT NULL ENABLE
   ,"USERNAME"                VARCHAR2(20 BYTE)  DEFAULT 'USERNAME' NOT NULL ENABLE
   ,CONSTRAINT "OHI_GROUPS_PK"
      PRIMARY KEY ("GRAC_ID")
      ENABLE
   );

  CREATE TABLE "LHHCOM"."OHI_GROUPS_AUDIT" 
   (	
	  "TRANSACTION_DATETIME"    DATE 
	 ,"TRANSACTION_DESC"        VARCHAR2(550 BYTE) 
	 ,"TRANSACTION_USERNAME"    VARCHAR2(50 BYTE)
   ,"GRAC_ID"                 NUMBER(14,0)       
   ,"GROUP_CODE"              VARCHAR2(30 BYTE)  
   ,"GROUP_NAME"              VARCHAR2(100 BYTE)
   ,"EFFECTIVE_START_DATE"    DATE               
   ,"EFFECTIVE_END_DATE"      DATE               
   ,"PARENTGROUP_CODE"        VARCHAR2(30 BYTE)
   ,"GROUP_TYPE"              VARCHAR2(10 BYTE)
   ,"GROUP_CLASS"             VARCHAR2(4 BYTE)
   ,"PREFERRED_CURRENCY_CODE" VARCHAR2(4 BYTE)
   ,"COUNTRY_CODE"            VARCHAR2(4 BYTE)
   );

  CREATE TABLE "LHHCOM"."OHI_POLICIES" 
   (
    "POLI_ID"                 NUMBER(14,0)       NOT NULL ENABLE
   ,"POLICY_CODE"             VARCHAR2(30 BYTE)  NOT NULL ENABLE
   ,"LAST_UPDATE_DATETIME"    DATE               DEFAULT sysdate NOT NULL ENABLE
   ,"USERNAME"                VARCHAR2(20 BYTE)  DEFAULT 'USERNAME' NOT NULL ENABLE
   ,CONSTRAINT "OHI_POLICIES_PK"
      PRIMARY KEY ("POLI_ID")
      ENABLE
   );
   
  CREATE TABLE "LHHCOM"."OHI_POLICIES_AUDIT" 
   (	
	  "TRANSACTION_DATETIME"    DATE  DEFAULT SYSDATE
	 ,"TRANSACTION_DESC"        VARCHAR2(550 BYTE) 
	 ,"TRANSACTION_USERNAME"    VARCHAR2(50 BYTE) DEFAULT USER
   ,"POLI_ID"                 NUMBER(14,0)       
   ,"POLICY_CODE"             VARCHAR2(30 BYTE)  
   );

  CREATE TABLE "LHHCOM"."OHI_POLICY_GROUPS" 
   (
    "POGR_ID"                 NUMBER(14,0)       NOT NULL ENABLE
   ,"POLI_ID"                 NUMBER(14,0)       
   ,"GRAC_ID"                 NUMBER(14,0)       
   ,"EFFECTIVE_START_DATE"    DATE               DEFAULT '01-JAN-1900' NOT NULL ENABLE
   ,"EFFECTIVE_END_DATE"      DATE               DEFAULT '31-JAN-3100' NOT NULL ENABLE
   ,"LAST_UPDATE_DATETIME"    DATE               DEFAULT sysdate NOT NULL ENABLE
   ,"USERNAME"                VARCHAR2(20 BYTE)  DEFAULT USER NOT NULL ENABLE
   ,CONSTRAINT "OHI_POLICY_GROUPS_PK"
      PRIMARY KEY ("POGR_ID")
      ENABLE
   );
   
  ALTER TABLE "LHHCOM"."OHI_POLICY_GROUPS" 
    ADD
   ( 	
 	  CONSTRAINT "OHI_POLICY_GROUPS_POLICIES_FK"
      FOREIGN KEY ("POLI_ID")
      REFERENCES "LHHCOM"."OHI_POLICIES" ("POLI_ID")
      ENABLE
   ,CONSTRAINT "OHI_POLICY_GROUPS_GROUPS_FK"
      FOREIGN KEY ("GRAC_ID")
      REFERENCES "LHHCOM"."OHI_GROUPS" ("GRAC_ID")
      ENABLE
   );

  CREATE TABLE "LHHCOM"."OHI_POLICY_GROUPS_AUDIT" 
   (	
	  "TRANSACTION_DATETIME"    DATE 
	 ,"TRANSACTION_DESC"        VARCHAR2(550 BYTE) 
	 ,"TRANSACTION_USERNAME"    VARCHAR2(50 BYTE)
   ,"POGR_ID"                 NUMBER(14,0)       
   ,"POLI_ID"                 NUMBER(14,0)       
   ,"GRAC_ID"                 NUMBER(14,0)       
   ,"EFFECTIVE_START_DATE"    DATE               
   ,"EFFECTIVE_END_DATE"      DATE               
   );

  CREATE TABLE "LHHCOM"."OHI_POLICY_BROKERS" 
   (
    "POLI_ID"                 NUMBER(14,0)       NOT NULL ENABLE
   ,"POBR_ID"                 NUMBER(14,0)       NOT NULL ENABLE
   ,"BROKER_ID_NO"            NUMBER(9,0)       
   ,"COMPANY_ID_NO"           NUMBER(9,0)       
   ,"EFFECTIVE_START_DATE"    DATE               DEFAULT '01-JAN-1900' NOT NULL ENABLE
   ,"EFFECTIVE_END_DATE"      DATE               DEFAULT '31-JAN-3100' NOT NULL ENABLE
   ,"LAST_UPDATE_DATETIME"    DATE               DEFAULT sysdate NOT NULL ENABLE
   ,"USERNAME"                VARCHAR2(20 BYTE)  DEFAULT USER NOT NULL ENABLE
   ,CONSTRAINT "OHI_POLICY_BROKERS_PK"
      PRIMARY KEY ("POLI_ID", "POBR_ID")
      ENABLE
   );
   
  ALTER TABLE "LHHCOM"."OHI_POLICY_BROKERS" 
    ADD
   ( 	
 	  CONSTRAINT "OHI_POLICY_BROKERS_BROKER_FK"
      FOREIGN KEY ("BROKER_ID_NO")
      REFERENCES "LHHCOM"."BROKER" ("BROKER_ID_NO")
      ENABLE
  ,CONSTRAINT "OHI_POLICY_BROKERS_COMPANY_FK"
      FOREIGN KEY ("COMPANY_ID_NO")
      REFERENCES "LHHCOM"."COMPANY" ("COMPANY_ID_NO")
      ENABLE
 	 ,CONSTRAINT "OHI_POLICY_BROKERS_POLICIES_FK" 
      FOREIGN KEY ("POLI_ID")
      REFERENCES "LHHCOM"."OHI_POLICIES" ("POLI_ID")
      ENABLE
   );

  CREATE TABLE "LHHCOM"."OHI_POLICY_BROKERS_AUDIT" 
   (	
	  "TRANSACTION_DATETIME"    DATE 
	 ,"TRANSACTION_DESC"        VARCHAR2(550 BYTE) 
	 ,"TRANSACTION_USERNAME"    VARCHAR2(50 BYTE)
   ,"POLI_ID"                 NUMBER(14,0)       
   ,"POBR_ID"                 NUMBER(14,0)       
   ,"BROKER_ID_NO"            NUMBER(9,0)       
   ,"COMPANY_ID_NO"           NUMBER(9,0)       
   ,"EFFECTIVE_START_DATE"    DATE               
   ,"EFFECTIVE_END_DATE"      DATE               
   );

  CREATE TABLE "LHHCOM"."OHI_POLICYHOLDERS" 
   (
    "POHO_ID"                 NUMBER(14,0)       NOT NULL ENABLE
   ,"POLI_ID"                 NUMBER(14,0)       NOT NULL ENABLE
   ,"RELA_ID_PERS"            NUMBER(14,0)       NOT NULL ENABLE
   ,"TITLE"                   VARCHAR2(20 BYTE)
   ,"INITIALS"                VARCHAR2(20 BYTE)
   ,"FIRST_NAME"              VARCHAR2(30 BYTE)
   ,"SURNAME"                 VARCHAR2(100 BYTE)
   ,"EFFECTIVE_START_DATE"    DATE               DEFAULT '01-JAN-1900' NOT NULL ENABLE
   ,"EFFECTIVE_END_DATE"      DATE               DEFAULT '31-JAN-3100' NOT NULL ENABLE
   ,"LAST_UPDATE_DATETIME"    DATE               DEFAULT sysdate NOT NULL ENABLE
   ,"USERNAME"                VARCHAR2(20 BYTE)  DEFAULT 'USERNAME' NOT NULL ENABLE
   ,CONSTRAINT "OHI_POLICYHOLDERS_PK"
      PRIMARY KEY ("POHO_ID")
      ENABLE
   );
   
  ALTER TABLE "LHHCOM"."OHI_POLICYHOLDERS" 
    ADD
   ( 	
 	  CONSTRAINT "OHI_POLICYHOLDERS_POLICIES_FK" 
      FOREIGN KEY ("POLI_ID")
      REFERENCES "LHHCOM"."OHI_POLICIES" ("POLI_ID")
      ENABLE
   );

  CREATE TABLE "LHHCOM"."OHI_POLICYHOLDERS_AUDIT" 
   (	
	  "TRANSACTION_DATETIME"    DATE 
	 ,"TRANSACTION_DESC"        VARCHAR2(550 BYTE) 
	 ,"TRANSACTION_USERNAME"    VARCHAR2(50 BYTE)
   ,"POHO_ID"                 NUMBER(14,0)       
   ,"POLI_ID"                 NUMBER(14,0)       
   ,"RELA_ID_PERS"            NUMBER(14,0)       
   ,"TITLE"                   VARCHAR2(20 BYTE)
   ,"INITIALS"                VARCHAR2(20 BYTE)
   ,"FIRST_NAME"              VARCHAR2(30 BYTE)
   ,"SURNAME"                 VARCHAR2(100 BYTE)
   ,"EFFECTIVE_START_DATE"    DATE               
   ,"EFFECTIVE_END_DATE"      DATE               
   );

  CREATE TABLE "LHHCOM"."OHI_INSURED_ENTITIES" 
   (
    "INSE_ID"                 NUMBER(14,0)       NOT NULL ENABLE
   ,"INSE_CODE"               VARCHAR2(30 BYTE)  NOT NULL ENABLE
   ,"RELA_ID_PERS"            NUMBER(14,0)       NOT NULL ENABLE
   ,"TITLE"                   VARCHAR2(20 BYTE)
   ,"INITIALS"                VARCHAR2(20 BYTE)
   ,"FIRST_NAME"              VARCHAR2(30 BYTE)
   ,"SURNAME"                 VARCHAR2(100 BYTE)
   ,"GENDER"                  VARCHAR2(1 BYTE)
   ,"LAST_UPDATE_DATETIME"    DATE               DEFAULT sysdate NOT NULL ENABLE
   ,"USERNAME"                VARCHAR2(20 BYTE)  DEFAULT 'USERNAME' NOT NULL ENABLE
   ,CONSTRAINT "OHI_INSURED_ENTITIES_PK"
      PRIMARY KEY ("INSE_ID")
      ENABLE
   );

  CREATE TABLE "LHHCOM"."OHI_INSURED_ENTITIES_AUDIT" 
   (	
	  "TRANSACTION_DATETIME"    DATE 
	 ,"TRANSACTION_DESC"        VARCHAR2(550 BYTE) 
	 ,"TRANSACTION_USERNAME"    VARCHAR2(50 BYTE)
   ,"INSE_ID"                 NUMBER(14,0)       
   ,"INSE_CODE"               VARCHAR2(30 BYTE)  
   ,"RELA_ID_PERS"            NUMBER(14,0)       
   ,"TITLE"                   VARCHAR2(20 BYTE)
   ,"INITIALS"                VARCHAR2(20 BYTE)
   ,"FIRST_NAME"              VARCHAR2(30 BYTE)
   ,"SURNAME"                 VARCHAR2(100 BYTE)
   ,"GENDER"                  VARCHAR2(1 BYTE)
   );

  CREATE TABLE "LHHCOM"."OHI_POLICY_ENROLLMENTS" 
   (
    "POEN_ID"                 NUMBER(14,0)       NOT NULL ENABLE
   ,"POLI_ID"                 NUMBER(14,0)       NOT NULL ENABLE
   ,"INSE_ID"                 NUMBER(14,0)       NOT NULL ENABLE
   ,"DEPENDANT_ID"            NUMBER(14,0)       NOT NULL ENABLE
   ,"LAST_UPDATE_DATETIME"    DATE               DEFAULT sysdate NOT NULL ENABLE
   ,"USERNAME"                VARCHAR2(20 BYTE)  DEFAULT 'USERNAME' NOT NULL ENABLE
   ,CONSTRAINT "OHI_POLICY_ENROLLMENTS_PK"
      PRIMARY KEY ("POEN_ID")
      ENABLE
   );
   
  ALTER TABLE "LHHCOM"."OHI_POLICY_ENROLLMENTS" 
    ADD
   ( 	
 	  CONSTRAINT "OHI_POLI_ENROLLMENTS_POLI_FK" 
      FOREIGN KEY ("POLI_ID")
      REFERENCES "LHHCOM"."OHI_POLICIES" ("POLI_ID")
      ENABLE
 	 ,CONSTRAINT "OHI_POLI_ENROLLMENTS_INSE_FK" 
      FOREIGN KEY ("INSE_ID")
      REFERENCES "LHHCOM"."OHI_INSURED_ENTITIES" ("INSE_ID")
      ENABLE
   );

  CREATE TABLE "LHHCOM"."OHI_POLICY_ENROLLMENTS_AUDIT" 
   (	
	  "TRANSACTION_DATETIME"    DATE 
	 ,"TRANSACTION_DESC"        VARCHAR2(550 BYTE) 
	 ,"TRANSACTION_USERNAME"    VARCHAR2(50 BYTE)
   ,"POEN_ID"                 NUMBER(14,0)     
   ,"POLI_ID"                 NUMBER(14,0)     
   ,"INSE_ID"                 NUMBER(14,0)     
   ,"DEPENDANT_ID"            NUMBER(14,0)     
   );

  CREATE TABLE "LHHCOM"."OHI_PRODUCTS" 
   (
    "ENPR_ID"                 NUMBER(14,0)       NOT NULL ENABLE
   ,"PRODUCT_CODE"            VARCHAR2(30 BYTE)  NOT NULL ENABLE
   ,"COUNTRY_CODE"            VARCHAR2(4 BYTE)
   ,"PRODUCT_NAME"            VARCHAR2(30 BYTE)
   ,"PRODUCT_DESCR"           VARCHAR2(200 BYTE)
   ,"LAST_UPDATE_DATETIME"    DATE               DEFAULT sysdate NOT NULL ENABLE
   ,"USERNAME"                VARCHAR2(20 BYTE)  DEFAULT 'USERNAME' NOT NULL ENABLE
   ,CONSTRAINT "OHI_PRODUCTS_PK"
      PRIMARY KEY ("ENPR_ID")
      ENABLE
   );

  CREATE TABLE "LHHCOM"."OHI_PRODUCTS_AUDIT" 
   (	

	  "TRANSACTION_DATETIME"    DATE 
	 ,"TRANSACTION_DESC"        VARCHAR2(550 BYTE) 
	 ,"TRANSACTION_USERNAME"    VARCHAR2(50 BYTE)
   ,"ENPR_ID"                 NUMBER(14,0)      
   ,"PRODUCT_CODE"            VARCHAR2(30 BYTE)  
   ,"COUNTRY_CODE"            VARCHAR2(4 BYTE)
   ,"PRODUCT_NAME"            VARCHAR2(30 BYTE)
   ,"PRODUCT_DESCR"           VARCHAR2(200 BYTE)
   );

  CREATE TABLE "LHHCOM"."OHI_ENROLLMENT_PRODUCTS" 
   (
    "POEP_ID"                 NUMBER(14,0)       NOT NULL ENABLE
   ,"POEN_ID"                 NUMBER(14,0)       NOT NULL ENABLE
   ,"ENPR_ID"                 NUMBER(14,0)       NOT NULL ENABLE
   ,"EFFECTIVE_START_DATE"    DATE               DEFAULT '01-JAN-1900' NOT NULL ENABLE
   ,"EFFECTIVE_END_DATE"      DATE               DEFAULT '31-JAN-3100' NOT NULL ENABLE
   ,"LAST_UPDATE_DATETIME"    DATE               DEFAULT sysdate NOT NULL ENABLE
   ,"USERNAME"                VARCHAR2(20 BYTE)  DEFAULT 'USERNAME' NOT NULL ENABLE
   ,CONSTRAINT "OHI_ENROLLMENT_PRODUCTS_PK"
      PRIMARY KEY ("POEP_ID")
      ENABLE
   );
   
  ALTER TABLE "LHHCOM"."OHI_ENROLLMENT_PRODUCTS" 
    ADD
   ( 	
 	  CONSTRAINT "OHI_ENRL_PROD_POLI_ENRL_FK" 
      FOREIGN KEY ("POEN_ID")
      REFERENCES "LHHCOM"."OHI_POLICY_ENROLLMENTS" ("POEN_ID")
      ENABLE
 	 ,CONSTRAINT "OHI_ENRL_PROD_PROD_FK" 
      FOREIGN KEY ("ENPR_ID")
      REFERENCES "LHHCOM"."OHI_PRODUCTS" ("ENPR_ID")
      ENABLE
   );

  CREATE TABLE "LHHCOM"."OHI_ENROLLMENT_PRODUCTS_AUDIT" 
   (	
	  "TRANSACTION_DATETIME"    DATE 
	 ,"TRANSACTION_DESC"        VARCHAR2(550 BYTE) 
	 ,"TRANSACTION_USERNAME"    VARCHAR2(50 BYTE)
   ,"POEP_ID"                 NUMBER(14,0)      
   ,"POEN_ID"                 NUMBER(14,0)      
   ,"ENPR_ID"                 NUMBER(14,0)      
   ,"EFFECTIVE_START_DATE"    DATE              
   ,"EFFECTIVE_END_DATE"      DATE              
   );
