  CREATE TABLE "LHHCOM"."OHI_POLICY_ENROLLMENTS" 
   (
    "POEN_ID"                 NUMBER(14,0)       NOT NULL ENABLE
   ,"POLI_ID"                 NUMBER(14,0)       NOT NULL ENABLE
   ,"INSE_ID"                 NUMBER(14,0)       NOT NULL ENABLE
   ,"DEPENDANT_ID"            NUMBER(14,0)       NOT NULL ENABLE
   ,"LAST_UPDATE_DATETIME"    DATE               DEFAULT sysdate NOT NULL ENABLE
   ,"USERNAME"                VARCHAR2(20 BYTE)  DEFAULT 'USERNAME' NOT NULL ENABLE
   ,CONSTRAINT "OHI_POLICY_ENROLLMENTS_PK"
      PRIMARY KEY ("POEN_ID")
      ENABLE
   );
   
  ALTER TABLE "LHHCOM"."OHI_POLICY_ENROLLMENTS" 
    ADD
   ( 	
 	  CONSTRAINT "OHI_POLI_ENROLLMENTS_POLI_FK" 
      FOREIGN KEY ("POLI_ID")
      REFERENCES "LHHCOM"."OHI_POLICIES" ("POLI_ID")
      ENABLE
 	 ,CONSTRAINT "OHI_POLI_ENROLLMENTS_INSE_FK" 
      FOREIGN KEY ("INSE_ID")
      REFERENCES "LHHCOM"."OHI_INSURED_ENTITIES" ("INSE_ID")
      ENABLE
   );
