  CREATE TABLE "LHHCOM"."OHI_ENROLLMENT_PRODUCTS" 
   (
    "POEP_ID"                 NUMBER(14,0)       NOT NULL ENABLE
   ,"POEN_ID"                 NUMBER(14,0)       NOT NULL ENABLE
   ,"ENPR_ID"                 NUMBER(14,0)       NOT NULL ENABLE
   ,"EFFECTIVE_START_DATE"    DATE               DEFAULT '01-JAN-1900' NOT NULL ENABLE
   ,"EFFECTIVE_END_DATE"      DATE               DEFAULT '31-JAN-3100' NOT NULL ENABLE
   ,"LAST_UPDATE_DATETIME"    DATE               DEFAULT sysdate NOT NULL ENABLE
   ,"USERNAME"                VARCHAR2(20 BYTE)  DEFAULT 'USERNAME' NOT NULL ENABLE
   ,CONSTRAINT "OHI_ENROLLMENT_PRODUCTS_PK"
      PRIMARY KEY ("POEP_ID")
      ENABLE
   );
   
  ALTER TABLE "LHHCOM"."OHI_ENROLLMENT_PRODUCTS" 
    ADD
   ( 	
 	  CONSTRAINT "OHI_ENRL_PROD_POLI_ENRL_FK" 
      FOREIGN KEY ("POEN_ID")
      REFERENCES "LHHCOM"."OHI_POLICY_ENROLLMENTS" ("POEN_ID")
      ENABLE
 	 ,CONSTRAINT "OHI_ENRL_PROD_PROD_FK" 
      FOREIGN KEY ("ENPR_ID")
      REFERENCES "LHHCOM"."OHI_PRODUCTS" ("ENPR_ID")
      ENABLE
   );
