  CREATE TABLE "LHHCOM"."OHI_POLICIES" 
   (
    "POLI_ID"                 NUMBER(14,0)       NOT NULL ENABLE
   ,"POLICY_CODE"             VARCHAR2(30 BYTE)  NOT NULL ENABLE
   ,"LAST_UPDATE_DATETIME"    DATE               DEFAULT sysdate NOT NULL ENABLE
   ,"USERNAME"                VARCHAR2(20 BYTE)  DEFAULT 'USERNAME' NOT NULL ENABLE
   ,CONSTRAINT "OHI_POLICIES_PK"
      PRIMARY KEY ("POLI_ID")
      ENABLE
   );
