  CREATE TABLE "LHHCOM"."UPLD_COMMS_PAYMENTS_RECEIVED" 
   ("APPLICATION_ID" NUMBER(36) NOT NULL ENABLE,
    "FINANCE_RECEIPT_NO" NUMBER(20,0) NOT NULL ENABLE, 
	"GROUP_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"COUNTRY_CODE" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"PRODUCT_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"POLICY_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PERSON_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CONTRIBUTION_DATE" DATE NOT NULL ENABLE, 
	"FINANCE_RECEIPT_DATE" DATE NOT NULL ENABLE, 
	"FINANCE_INVOICE_NO" NUMBER(20,0) NOT NULL ENABLE, 
	"FINANCE_INVOICE_DATE" DATE NOT NULL ENABLE, 
	"FINANCE_RECEIPT_AMT" NUMBER(15,2) NOT NULL ENABLE 
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
