  CREATE INDEX "LHHCOM"."ACCRED_TY_START_DATE_IDX" ON "LHHCOM"."ACCREDITATION_TYPE" ("EFFECTIVE_START_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."ACCRED_TY_UPDATEDATE_IDX" ON "LHHCOM"."ACCREDITATION_TYPE" ("LAST_UPDATE_DATETIME" DESC) ;