  CREATE INDEX "LHHCOM"."ADDRESS_TY_AUD_START_DATE_IDX" ON "LHHCOM"."ADDRESS_TYPE_AUDIT" ("EFFECTIVE_START_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."ADDRESS_TY_AUD_UPDATEDATE_IDX" ON "LHHCOM"."ADDRESS_TYPE_AUDIT" ("TRANSACTION_DATETIME" DESC) ;