  CREATE INDEX "LHHCOM"."ADDRESS_TY_START_DATE_IDX" ON "LHHCOM"."ADDRESS_TYPE" ("EFFECTIVE_START_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."ADDRESS_TY_UPDATEDATE_IDX" ON "LHHCOM"."ADDRESS_TYPE" ("LAST_UPDATE_DATETIME" DESC) ;