  CREATE INDEX "LHHCOM"."BR_TABLE_START_DATE_IDX" ON "LHHCOM"."BROKER_TABLE" ("EFFECTIVE_START_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."BR_TABLE_UPDATEDATE_IDX" ON "LHHCOM"."BROKER_TABLE" ("LAST_UPDATE_DATETIME" DESC) ;