  CREATE INDEX "LHHCOM"."BR_TAB_TY_FK_IDX" ON "LHHCOM"."BROKER_TABLE_TYPE" ("BROKER_TABLE_ID_NO") ;
  
  CREATE INDEX "LHHCOM"."BR_TAB_TY_START_DATE_IDX" ON "LHHCOM"."BROKER_TABLE_TYPE" ("EFFECTIVE_START_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."BR_TAB_TY_UPDATEDATE_IDX" ON "LHHCOM"."BROKER_TABLE_TYPE" ("LAST_UPDATE_DATETIME" DESC) ;