  CREATE INDEX "LHHCOM"."BROKER_AUDIT_IDX" ON "LHHCOM"."BROKER_AUDIT" ("BROKER_ID_NO") ;
   
  CREATE INDEX "LHHCOM"."BROK_AUD_UPDATEDATE_IDX" ON "LHHCOM"."BROKER_AUDIT" ("TRANSACTION_DATETIME" DESC) ;