  CREATE INDEX "LHHCOM"."BROKER_FUNCTION_FK_IDX" ON "LHHCOM"."BROKER_FUNCTION" ("BROKER_ID_NO") ;
  
  CREATE INDEX "LHHCOM"."BROKER_FUNC_TABLE_TY_FK_IDX" ON "LHHCOM"."BROKER_FUNCTION" ("BROKER_TABLE_TYPE_ID_NO") ;
  
  CREATE INDEX "LHHCOM"."BROKER_FUNC_START_DATE_IDX" ON "LHHCOM"."BROKER_FUNCTION" ("EFFECTIVE_START_DATE" DESC) ;
    
  CREATE INDEX "LHHCOM"."BROKER_FUNC_UPDATEDATE_IDX" ON "LHHCOM"."BROKER_FUNCTION" ("LAST_UPDATE_DATETIME" DESC) ;