  CREATE INDEX "LHHCOM"."BR_ACCRED_AUD_ACCRED_DATE_IDX" ON "LHHCOM"."BROKER_ACCREDITATION_AUDIT" ("BROKER_ACCRED_START_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."BR_ACCRED_AUD_START_DATE_IDX" ON "LHHCOM"."BROKER_ACCREDITATION_AUDIT" ("EFFECTIVE_START_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."BR_ACCRED_AUD_UPDATEDATE_IDX" ON "LHHCOM"."BROKER_ACCREDITATION_AUDIT" ("TRANSACTION_DATETIME" DESC) ;