  CREATE INDEX "LHHCOM"."BROK_TAB_TY_AUD_START_DATE_IDX" ON "LHHCOM"."BROKER_TABLE_TYPE_AUDIT" ("EFFECTIVE_START_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."BROK_TAB_TY_AUD_UPDATEDATE_IDX" ON "LHHCOM"."BROKER_TABLE_TYPE_AUDIT" ("TRANSACTION_DATETIME" DESC) ;