  CREATE INDEX "LHHCOM"."BR_FN_AUD_START_DATE_IDX" ON "LHHCOM"."BROKER_FUNCTION_AUDIT" ("EFFECTIVE_START_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."BR_FN_AUD_UPDATEDATE_IDX" ON "LHHCOM"."BROKER_FUNCTION_AUDIT" ("TRANSACTION_DATETIME" DESC) ;