  CREATE INDEX "LHHCOM"."COM_PAY_REC_CONTRIB_DATE_IDX" ON "LHHCOM"."COMMS_PAYMENTS_RECEIVED" ("CONTRIBUTION_DATE" DESC) ;
  
  CREATE INDEX "LHHCOM"."COM_PAY_REC_INV_DATE_IDX" ON "LHHCOM"."COMMS_PAYMENTS_RECEIVED" ("FINANCE_INVOICE_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."COM_PAY_REC_UPDATEDATE_IDX" on "LHHCOM"."COMMS_PAYMENTS_RECEIVED" ("LAST_UPDATE_DATETIME" desc) ;
  
  CREATE INDEX "LHHCOM"."COM_PAY_REC_SNAPSHOT_IDX" ON "LHHCOM"."COMMS_PAYMENTS_RECEIVED" ("COMMS_CALC_SNAPSHOT_NO") ;
  
  CREATE INDEX "LHHCOM"."COM_PAY_REC_CURR_CODE_IDX" ON "LHHCOM"."COMMS_PAYMENTS_RECEIVED" ("CURRENCY_CODE") ;