  CREATE INDEX "LHHCOM"."COMMS_CALC_TRACE_BASE_IDX" ON "LHHCOM"."COMMS_CALC_TRACE" (TRACE_BASE_SNAPSHOT_NO);
  
  CREATE INDEX "LHHCOM"."COMMS_CALC_TRACE_ORIGINAL_IDX" on "LHHCOM"."COMMS_CALC_TRACE" (TRACE_ORIGINAL_SNAPSHOT_NO);

