  CREATE UNIQUE INDEX "LHHCOM"."COMMS_CALC_SNAPSHOT_UK_IDX" ON "LHHCOM"."COMMS_CALC_SNAPSHOT"
    ("COUNTRY_CODE" ,"PRODUCT_CODE" ,"POEP_ID" ,"PERSON_CODE" ,"POLICY_CODE" ,"GROUP_CODE"
    ,"BROKER_ID_NO" ,"COMPANY_ID_NO" ,"CONTRIBUTION_DATE" ,"PAYMENT_RECEIVE_DATE" ,"FINANCE_RECEIPT_NO"
    ,"CALCULATION_DATETIME" ,"COMMS_CALC_TYPE_CODE" ,"PAYMENT_CURRENCY" ,"EXCHANGE_RATE_CURRENCY_CODE");    

  CREATE INDEX "LHHCOM"."COMMS_CALC_TY_FK_IDX" ON "LHHCOM"."COMMS_CALC_SNAPSHOT" ("COMMS_CALC_TYPE_CODE") ;
  
  CREATE INDEX "LHHCOM"."COMMS_CONTRIB_DATE_IDX" ON "LHHCOM"."COMMS_CALC_SNAPSHOT" ("CONTRIBUTION_DATE" DESC) ;
  
  CREATE INDEX "LHHCOM"."COMMS_CALC_PAYREC_DT_IDX" ON "LHHCOM"."COMMS_CALC_SNAPSHOT" ("PAYMENT_RECEIVE_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."COMMS_CALC_DATE_IDX" ON "LHHCOM"."COMMS_CALC_SNAPSHOT" ("CALCULATION_DATETIME" DESC) ;
  
  CREATE INDEX "LHHCOM"."COMMS_CALC_UPDATEDATE_IDX" ON "LHHCOM"."COMMS_CALC_SNAPSHOT" ("LAST_UPDATE_DATETIME" DESC) ;
  
  CREATE INDEX "LHHCOM"."COMMS_CALC_COMP_IDX" ON "LHHCOM"."COMMS_CALC_SNAPSHOT" ("COMPANY_ID_NO") ;
  
  CREATE INDEX "LHHCOM"."COMMS_CALC_FIN_REC_IDX" ON "LHHCOM"."COMMS_CALC_SNAPSHOT" ("FINANCE_RECEIPT_NO") ;
  
  CREATE INDEX "LHHCOM"."COMMS_CALC_PAY_CURR_IDX" ON "LHHCOM"."COMMS_CALC_SNAPSHOT" ("PAYMENT_CURRENCY") ;
  
  CREATE INDEX "LHHCOM"."COMMS_CALC_EXCH_CURR_IDX" ON "LHHCOM"."COMMS_CALC_SNAPSHOT" ("EXCHANGE_RATE_CURRENCY_CODE") ;
  
  CREATE INDEX "LHHCOM"."COMMS_CALC_USERNAME_IDX" ON "LHHCOM"."COMMS_CALC_SNAPSHOT" ("USERNAME") ;
