  CREATE INDEX "LHHCOM"."CO_ACCRED_AUD_ACCRED_DATE_IDX" ON "LHHCOM"."COMPANY_ACCREDITATION_AUDIT" ("COMPANY_ACCRED_START_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."CO_ACCRED_AUD_START_DATE_IDX" ON "LHHCOM"."COMPANY_ACCREDITATION_AUDIT" ("EFFECTIVE_START_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."CO_ACCRED_AUD_UPDATEDATE_IDX" ON "LHHCOM"."COMPANY_ACCREDITATION_AUDIT" ("TRANSACTION_DATETIME" DESC) ;