  CREATE INDEX "LHHCOM"."COMPANY_AUDIT_IDX" ON "LHHCOM"."COMPANY_AUDIT" ("COMPANY_ID_NO") ;

  CREATE INDEX "LHHCOM"."COMPANY_AUD_UPDATEDATE_IDX" ON "LHHCOM"."COMPANY_AUDIT" ("TRANSACTION_DATETIME" DESC) ;