  CREATE INDEX "LHHCOM"."CO_ADDR_AUD_START_DATE_IDX" ON "LHHCOM"."COMPANY_ADDRESS_AUDIT" ("EFFECTIVE_START_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."CO_ADDR_AUD_UPDATEDATE_IDX" ON "LHHCOM"."COMPANY_ADDRESS_AUDIT" ("TRANSACTION_DATETIME" DESC) ;