
  CREATE INDEX "LHHCOM"."CO_ACCRED_BROKER_IDX" ON "LHHCOM"."COMPANY_ACCREDITATION" ("COMPANY_ID_NO") ; 
   
  CREATE INDEX "LHHCOM"."CO_ACCRED_TYPE_IDX" ON "LHHCOM"."COMPANY_ACCREDITATION" ("ACCREDITATION_TYPE_ID_NO") ;  

  CREATE INDEX "LHHCOM"."CO_ACCRED_START_DATE_IDX" ON "LHHCOM"."COMPANY_ACCREDITATION" ("EFFECTIVE_START_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."CO_ACCRED_UPDATEDATE_IDX" ON "LHHCOM"."COMPANY_ACCREDITATION" ("LAST_UPDATE_DATETIME" DESC) ;
  
  CREATE INDEX "LHHCOM"."CO_ACCRED_STRT_DT_IDX" ON "LHHCOM"."COMPANY_ACCREDITATION" ("COMPANY_ACCRED_START_DATE" DESC) ;
  