  CREATE INDEX "LHHCOM"."COMPANY_COMMENTS_FK_IDX" ON "LHHCOM"."COMPANY_COMMENTS" ("COMPANY_ID_NO") ;
   
  CREATE INDEX "LHHCOM"."COMPANY_COMMENTS_DATE_IDX" ON "LHHCOM"."COMPANY_COMMENTS" ("COMMENT_DATETIME" DESC) ; 
   
  CREATE INDEX "LHHCOM"."COMP_COMM_UPDATEDATE_IDX" ON "LHHCOM"."COMPANY_COMMENTS" ("LAST_UPDATE_DATETIME" DESC) ;