  CREATE INDEX "LHHCOM"."COMPANY_COUNTRY_COMP_FK_IDX" ON "LHHCOM"."COMPANY_COUNTRY" ("COMPANY_ID_NO") ;
  
  CREATE INDEX "LHHCOM"."COMPANY_COUNTRY_START_DATE_IDX" ON "LHHCOM"."COMPANY_COUNTRY" ("EFFECTIVE_START_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."COMPANY_COUNTRY_UPDATEDATE_IDX" ON "LHHCOM"."COMPANY_COUNTRY" ("LAST_UPDATE_DATETIME" DESC) ;