  CREATE INDEX "LHHCOM"."COMP_REG_AUD_START_DATE_IDX" ON "LHHCOM"."COMPANY_REG_AUDIT" ("EFFECTIVE_START_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."COMP_REG_AUD_UPDATEDATE_IDX" ON "LHHCOM"."COMPANY_REG_AUDIT" ("TRANSACTION_DATETIME" DESC) ;