
  CREATE INDEX "LHHCOM"."COMPANY_FUNCTION_TBL_TY_FK_IDX" ON "LHHCOM"."COMPANY_FUNCTION" ("COMPANY_TABLE_ID_NO", "COMPANY_TABLE_TYPE_ID_NO") ;
  
  CREATE INDEX "LHHCOM"."COMPANY_FUNCTION_STRT_DATE_IDX" ON "LHHCOM"."COMPANY_FUNCTION" ("EFFECTIVE_START_DATE" DESC) ;
  
  CREATE INDEX "LHHCOM"."COMPANY_FUNCTION_UPDTEDATE_IDX" ON "LHHCOM"."COMPANY_FUNCTION" ("LAST_UPDATE_DATETIME" DESC) ;