  CREATE INDEX "LHHCOM"."COMP_TAB_AUD_START_DATE_IDX" ON "LHHCOM"."COMPANY_TABLE_AUDIT" ("EFFECTIVE_START_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."COMP_TAB_AUD_UPDATEDATE_IDX" ON "LHHCOM"."COMPANY_TABLE_AUDIT" ("TRANSACTION_DATETIME" DESC) ;