  CREATE INDEX "LHHCOM"."CO_COMM_PC_AUD_START_DATE_IDX" ON "LHHCOM"."COMPANY_COMM_PERC_AUDIT" ("EFFECTIVE_START_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."CO_COMM_PC_AUD_UPDATEDATE_IDX" ON "LHHCOM"."COMPANY_COMM_PERC_AUDIT" ("TRANSACTION_DATETIME" DESC) ;