  CREATE INDEX "LHHCOM"."COMPANY_START_DATE_IDX" ON "LHHCOM"."COMPANY" ("EFFECTIVE_START_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."COMPANY_UPDATEDATE_IDX" ON "LHHCOM"."COMPANY" ("LAST_UPDATE_DATETIME" DESC) ;