CREATE INDEX "LHHCOM"."COMPANY_TBL_STRT_DATE_IDX" ON "LHHCOM"."COMPANY_TABLE_TYPE" ("EFFECTIVE_START_DATE" DESC) ;

CREATE INDEX "LHHCOM"."COMPANY_TBL_UPDTEDATE_IDX" ON "LHHCOM"."COMPANY_TABLE_TYPE" ("LAST_UPDATE_DATETIME" DESC) ;