  CREATE INDEX "LHHCOM"."COMP_FEE_TY_AUD_START_DATE_IDX" ON "LHHCOM"."COMPANY_FEE_TYPE_AUDIT" ("EFFECTIVE_START_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."COMP_FEE_TY_AUD_UPDATEDATE_IDX" ON "LHHCOM"."COMPANY_FEE_TYPE_AUDIT" ("TRANSACTION_DATETIME" DESC) ;