CREATE INDEX "LHHCOM"."COMPANY_TABLE_STRT_DATE_IDX" ON "LHHCOM"."COMPANY_TABLE" ("EFFECTIVE_START_DATE" DESC) ;

CREATE INDEX "LHHCOM"."COMPANY_TABLE_UPDTEDATE_IDX" ON "LHHCOM"."COMPANY_TABLE" ("LAST_UPDATE_DATETIME" DESC) ;