
  CREATE INDEX "LHHCOM"."COMP_FN_AUD_START_DATE_IDX" ON "LHHCOM"."COMPANY_FUNCTION_AUDIT" ("EFFECTIVE_START_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."COMP_FN_AUD_UPDATEDATE_IDX" ON "LHHCOM"."COMPANY_FUNCTION_AUDIT" ("TRANSACTION_DATETIME" DESC) ;