  CREATE INDEX "LHHCOM"."CO_ADDR_COUNTRY_FK_IDX" ON "LHHCOM"."COMPANY_ADDRESS" ("COUNTRY_CODE") ;
  
  CREATE INDEX "LHHCOM"."CO_ADDR_TYPE_FK_IDX" ON "LHHCOM"."COMPANY_ADDRESS" ("ADDRESS_TYPE_CODE") ;

  CREATE INDEX "LHHCOM"."CO_ADDR_START_DATE_IDX" ON "LHHCOM"."COMPANY_ADDRESS" ("EFFECTIVE_START_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."CO_ADDR_UPDATEDATE_IDX" ON "LHHCOM"."COMPANY_ADDRESS" ("LAST_UPDATE_DATETIME" DESC) ;