  CREATE INDEX "LHHCOM"."COMPANY_FEE_COMP_FK_IDX" ON "LHHCOM"."COMPANY_FEE" ("COMPANY_ID_NO") ;
  
  CREATE INDEX "LHHCOM"."COMPANY_FEE_TYPE_FK_IDX" ON "LHHCOM"."COMPANY_FEE" ("COMPANY_FEE_TYPE_ID_NO") ;
  
  CREATE INDEX "LHHCOM"."COMPANY_FEE_START_DATE_IDX" ON "LHHCOM"."COMPANY_FEE" ("EFFECTIVE_START_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."COMPANY_FEE_UPDATEDATE_IDX" ON "LHHCOM"."COMPANY_FEE" ("LAST_UPDATE_DATETIME" DESC) ;