  CREATE INDEX "LHHCOM"."COMPANY_FEE_TY_START_DATE_IDX" ON "LHHCOM"."COMPANY_FEE_TYPE" ("EFFECTIVE_START_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."COMPANY_FEE_TY_UPDATEDATE_IDX" ON "LHHCOM"."COMPANY_FEE_TYPE" ("LAST_UPDATE_DATETIME" DESC) ;