  CREATE INDEX "LHHCOM"."COMPANY_CONTACT_COMP_FK_IDX" ON "LHHCOM"."COMPANY_CONTACT" ("COMPANY_ID_NO") ;
  
  CREATE INDEX "LHHCOM"."COMPANY_CONTACT_COUNTRY_FK_IDX" ON "LHHCOM"."COMPANY_CONTACT" ("COMPANY_CONTACT_TYPE_ID_NO") ;
    
  CREATE INDEX "LHHCOM"."COMPANY_CONTACT_TYPE_FK_IDX" ON "LHHCOM"."COMPANY_CONTACT" ("COUNTRY_CODE") ;
  
  CREATE INDEX "LHHCOM"."COMPANY_CONTACT_STRT_DATE_IDX" ON "LHHCOM"."COMPANY_CONTACT" ("EFFECTIVE_START_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."COMPANY_CONTACT_UPDATEDATE_IDX" ON "LHHCOM"."COMPANY_CONTACT" ("LAST_UPDATE_DATETIME" DESC) ;