  CREATE INDEX "LHHCOM"."CNTRY_TXS_AUD_START_DATE_IDX"   ON "LHHCOM"."COUNTRY_TAXES_AUDIT" ("EFFECTIVE_START_DATE" DESC) ;
  
  CREATE INDEX "LHHCOM"."CNTRY_TXS_AUD_UPDATEDATE_IDX"   ON "LHHCOM"."COUNTRY_TAXES_AUDIT" ("TRANSACTION_DATETIME" DESC) ;
