  CREATE INDEX "LHHCOM"."DNLD_COMP_ADD_START_DATE_IDX" ON "LHHCOM"."DNLD_COMPANY_ADDRESS" ("EFFECTIVE_START_DATE" DESC) ;
  
  CREATE INDEX "LHHCOM"."DNLD_COMP_ADD_STAMP_DATE_IDX" ON "LHHCOM"."DNLD_COMPANY_ADDRESS" ("STAMP_DATETIME" DESC) ;

  CREATE INDEX "LHHCOM"."DNLD_COMP_ADD_UPDATEDATE_IDX" ON "LHHCOM"."DNLD_COMPANY_ADDRESS" ("LAST_UPDATE_DATETIME" DESC) ;