  CREATE INDEX "LHHCOM"."DNLD_BROK_STAMP_DATE_IDX" ON "LHHCOM"."DNLD_BROKER" ("STAMP_DATETIME" DESC) ;

  CREATE INDEX "LHHCOM"."DNLD_BROK_UPDATEDATE_IDX" ON "LHHCOM"."DNLD_BROKER" ("LAST_UPDATE_DATETIME" DESC) ;