  CREATE INDEX "LHHCOM"."DNLD_COMP_INTERF_SYS_ID_IDX" ON "LHHCOM"."DNLD_COMPANY" ("INTERF_SYSTEM_ID_NO" DESC);

  CREATE INDEX "LHHCOM"."DNLD_COMP_COMP_ID_IDX" ON "LHHCOM"."DNLD_COMPANY" ("COMPANY_ID_NO" ASC);
  
  CREATE INDEX "LHHCOM"."DNLD_COMP_STAMP_DATE_IDX" ON "LHHCOM"."DNLD_COMPANY" ("STAMP_DATETIME" DESC);

  CREATE INDEX "LHHCOM"."DNLD_COMP_UPDATEDATE_IDX" ON "LHHCOM"."DNLD_COMPANY" ("LAST_UPDATE_DATETIME" DESC) ;