  CREATE INDEX "LHHCOM"."DNLD_COMP_CONT_START_DATE_IDX" ON "LHHCOM"."DNLD_COMPANY_CONTACT" ("EFFECTIVE_START_DATE" DESC) ;
  
  CREATE INDEX "LHHCOM"."DNLD_COMP_CONT_STAMP_DATE_IDX" ON "LHHCOM"."DNLD_COMPANY_CONTACT" ("STAMP_DATETIME" DESC) ;

  CREATE INDEX "LHHCOM"."DNLD_COMP_CONT_UPDATEDATE_IDX" ON "LHHCOM"."DNLD_COMPANY_CONTACT" ("LAST_UPDATE_DATETIME" DESC) ;