  CREATE INDEX "LHHCOM"."DNLD_BROK_ACC_START_DATE_IDX" ON "LHHCOM"."DNLD_BROKER_ACCRED" ("EFFECTIVE_START_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."DNLD_BROK_ACC_UPDATEDATE_IDX" ON "LHHCOM"."DNLD_BROKER_ACCRED" ("LAST_UPDATE_DATETIME" DESC) ;