  CREATE INDEX "LHHCOM"."DNLD_COMP_ACC_START_DATE_IDX" ON "LHHCOM"."DNLD_COMPANY_ACCRED" ("EFFECTIVE_START_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."DNLD_COMP_ACC_UPDATEDATE_IDX" ON "LHHCOM"."DNLD_COMPANY_ACCRED" ("LAST_UPDATE_DATETIME" DESC) ;