  CREATE INDEX "LHHCOM"."DNLD_INV_STAMP_DATE_IDX" ON "LHHCOM"."DNLD_INVOICE" ("STAMP_DATETIME" DESC) ;

  CREATE INDEX "LHHCOM"."DNLD_INV_UPDATEDATE_IDX" ON "LHHCOM"."DNLD_INVOICE" ("LAST_UPDATE_DATETIME" DESC) ;