CREATE INDEX "LHHCOM"."INVOICE_FK_IDX" ON "LHHCOM"."INVOICE" ("COMPANY_ID_NO") ;
CREATE INDEX "LHHCOM"."INVOICE_DATE_IDX" ON "LHHCOM"."INVOICE" ("INVOICE_DATE" DESC) ;
CREATE INDEX "LHHCOM"."CONTRIBUTION_DATE_IDX" ON "LHHCOM"."INVOICE" ("CONTRIBUTION_DATE" DESC) ;
CREATE INDEX "LHHCOM"."RELEASE_DATE_IDX" ON "LHHCOM"."INVOICE" ("RELEASE_DATE" DESC) ;
CREATE INDEX "LHHCOM"."PAYMENT_DATE_IDX" ON "LHHCOM"."INVOICE" ("PAYMENT_DATE" DESC) ;
-- Helen LS-1361
CREATE INDEX "LHHCOM"."TAX_CODES_IDX" ON "LHHCOM"."INVOICE" ("INVOICE_TAX_CODES" DESC) ;
-- Helen LS-1361
CREATE INDEX "LHHCOM"."INVOICE_UPDTEDATE_IDX" ON "LHHCOM"."INVOICE" ("LAST_UPDATE_DATETIME" DESC) ;