  CREATE INDEX "LHHCOM"."INV_PMNTS_AUD_BUS_UNIT_IDX"    ON "LHHCOM"."INVOICE_PAYMENTS_AUDIT" ("P_BUSINESS_UNIT"       ASC) ;
  CREATE INDEX "LHHCOM"."INV_PMNTS_AUD_SUPP_NUM_IDX"    ON "LHHCOM"."INVOICE_PAYMENTS_AUDIT" ("SUPPLIER_NUMBER"       ASC) ;
  CREATE INDEX "LHHCOM"."INV_PMNTS_AUD_INV_ID_IDX"      ON "LHHCOM"."INVOICE_PAYMENTS_AUDIT" ("INVOICE_ID"            DESC) ;
  CREATE INDEX "LHHCOM"."INV_PMNTS_AUD_VENDOR_IDX"      ON "LHHCOM"."INVOICE_PAYMENTS_AUDIT" ("VENDOR_SITE_CODE"      ASC) ;
  CREATE INDEX "LHHCOM"."INV_PMNTS_AUD_INV_NUM_IDX"     ON "LHHCOM"."INVOICE_PAYMENTS_AUDIT" ("INVOICE_NUM"           ASC) ;
  CREATE INDEX "LHHCOM"."INV_PMNTS_AUD_LINE_NUM_IDX"    ON "LHHCOM"."INVOICE_PAYMENTS_AUDIT" ("LINE_NUMBER"           ASC) ;
  CREATE INDEX "LHHCOM"."INV_PMNTS_AUD_LINE_TYPE_IDX"   ON "LHHCOM"."INVOICE_PAYMENTS_AUDIT" ("LINE_TYPE_LOOKUP_CODE" ASC) ;
  CREATE INDEX "LHHCOM"."INV_PMNTS_AUD_REV_FLAG_IDX"    ON "LHHCOM"."INVOICE_PAYMENTS_AUDIT" ("REVERSAL_FLAG"         ASC) ;
  CREATE INDEX "LHHCOM"."INV_PMNTS_AUD_RATE_TYPE_IDX"   ON "LHHCOM"."INVOICE_PAYMENTS_AUDIT" ("EXCHANGE_RATE_TYPE"    ASC) ;
  CREATE INDEX "LHHCOM"."INV_PMNTS_AUD_INV_CURR_IDX"    ON "LHHCOM"."INVOICE_PAYMENTS_AUDIT" ("INVOICE_CURRENCY_CODE" ASC) ;
  CREATE INDEX "LHHCOM"."INV_PMNTS_AUD_PAY_CURR_IDX"    ON "LHHCOM"."INVOICE_PAYMENTS_AUDIT" ("PAYMENT_CURRENCY_CODE" ASC) ;
  CREATE INDEX "LHHCOM"."INV_PMNTS_AUD_ACT_DATE_IDX"    ON "LHHCOM"."INVOICE_PAYMENTS_AUDIT" ("DATE_ACTIONED"         DESC) ;
  CREATE INDEX "LHHCOM"."INV_PMNTS_AUD_DATE_STAMP_IDX"  ON "LHHCOM"."INVOICE_PAYMENTS_AUDIT" ("DATE_STAMP"            DESC) ;
  CREATE INDEX "LHHCOM"."INV_PMNTS_AUD_UPD_DATE_IDX"    ON "LHHCOM"."INVOICE_PAYMENTS_AUDIT" ("LAST_UPDATE_DATETIME"  DESC) ;
  CREATE INDEX "LHHCOM"."INV_PMNTS_AUD_TXN_USER_IDX"    ON "LHHCOM"."INVOICE_PAYMENTS_AUDIT" ("TRANSACTION_USERNAME"  ASC) ;
  CREATE INDEX "LHHCOM"."INV_PMNTS_AUD_TXN_DATE_IDX"    ON "LHHCOM"."INVOICE_PAYMENTS_AUDIT" ("TRANSACTION_DATETIME"  DESC) ;
  
