  CREATE INDEX "LHHCOM"."HOLD_IND_ENPR_FK_IDX" ON "LHHCOM"."OHI_HOLD_IND" ("ENPR_ID") ;
  
  CREATE INDEX "LHHCOM"."HOLD_IND_GRAC_FK_IDX" ON "LHHCOM"."OHI_HOLD_IND" ("GRAC_ID") ;
  
  CREATE INDEX "LHHCOM"."HOLD_IND_POBR_FK_IDX" ON "LHHCOM"."OHI_HOLD_IND" ("POBR_ID") ;
  
  CREATE INDEX "LHHCOM"."HOLD_IND_POEN_FK_IDX" ON "LHHCOM"."OHI_HOLD_IND" ("POEN_ID") ;
  
  CREATE INDEX "LHHCOM"."HOLD_IND_POEP_FK_IDX" ON "LHHCOM"."OHI_HOLD_IND" ("POEP_ID") ;
  
  CREATE INDEX "LHHCOM"."HOLD_IND_POLI_FK_IDX" ON "LHHCOM"."OHI_HOLD_IND" ("POLI_ID") ;
  
  CREATE INDEX "LHHCOM"."OHI_HOLD_IND_START_DATE_IDX" ON "LHHCOM"."OHI_HOLD_IND" ("EFFECTIVE_START_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."OHI_HOLD_IND_UPDATEDATE_IDX" ON "LHHCOM"."OHI_HOLD_IND" ("LAST_UPDATE_DATETIME" DESC) ;