  CREATE INDEX "LHHCOM"."OHI_ENROL_PROD_ENPR_FK_IDX" ON "LHHCOM"."OHI_ENROLLMENT_PRODUCTS" ("ENPR_ID") ;
  
  CREATE INDEX "LHHCOM"."OHI_ENROL_PROD_POEN_FK_IDX" ON "LHHCOM"."OHI_ENROLLMENT_PRODUCTS" ("POEN_ID") ;
  
  CREATE INDEX "LHHCOM"."OHI_ENROL_PROD_START_DATE_IDX" ON "LHHCOM"."OHI_ENROLLMENT_PRODUCTS" ("EFFECTIVE_START_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."OHI_ENROL_PROD_UPDATEDATE_IDX" ON "LHHCOM"."OHI_ENROLLMENT_PRODUCTS" ("LAST_UPDATE_DATETIME" DESC) ;