  CREATE INDEX "LHHCOM"."OHI_HLD_IND_AUD_START_DATE_IDX" ON "LHHCOM"."OHI_HOLD_IND_AUDIT" ("EFFECTIVE_START_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."OHI_HLD_IND_AUD_UPDATEDATE_IDX" ON "LHHCOM"."OHI_HOLD_IND_AUDIT" ("TRANSACTION_DATETIME" DESC) ;