  CREATE INDEX "LHHCOM"."OHI_POLICY_ENROL_INSE_FK_IDX" ON "LHHCOM"."OHI_POLICY_ENROLLMENTS" ("INSE_ID") ;
  
  CREATE INDEX "LHHCOM"."OHI_POLICY_ENROL_POLI_FK_IDX" ON "LHHCOM"."OHI_POLICY_ENROLLMENTS" ("POLI_ID") ;
  
 -- CREATE INDEX "LHHCOM"."OHI_POL_ENROL_START_DATE_IDX" ON "LHHCOM"."OHI_POLICY_ENROLLMENTS" ("EFFECTIVE_START_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."OHI_POL_ENROL_UPDATEDATE_IDX" ON "LHHCOM"."OHI_POLICY_ENROLLMENTS" ("LAST_UPDATE_DATETIME" DESC) ;