  CREATE INDEX "LHHCOM"."OHI_ENPR_AUD_START_DATE_IDX" ON "LHHCOM"."OHI_ENROLLMENT_PRODUCTS_AUDIT" ("EFFECTIVE_START_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."OHI_ENPR_AUD_UPDATEDATE_IDX" ON "LHHCOM"."OHI_ENROLLMENT_PRODUCTS_AUDIT" ("TRANSACTION_DATETIME" DESC) ;