  CREATE INDEX "LHHCOM"."OHI_GROUPS_START_DATE_IDX" ON "LHHCOM"."OHI_GROUPS" ("EFFECTIVE_START_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."OHI_GROUPS_UPDATEDATE_IDX" ON "LHHCOM"."OHI_GROUPS" ("LAST_UPDATE_DATETIME" DESC) ;