  CREATE INDEX "LHHCOM"."OHI_POLHOLD_AUD_START_DATE_IDX" ON "LHHCOM"."OHI_POLICYHOLDERS_AUDIT" ("EFFECTIVE_START_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."OHI_POLHOLD_AUD_UPDATEDATE_IDX" ON "LHHCOM"."OHI_POLICYHOLDERS_AUDIT" ("TRANSACTION_DATETIME" DESC) ;