--  CREATE INDEX "LHHCOM"."OHI_PROD_START_DATE_IDX" ON "LHHCOM"."OHI_PRODUCTS" ("EFFECTIVE_START_DATE" DESC) ;

  CREATE INDEX "LHHCOM"."OHI_PROD_UPDATEDATE_IDX" ON "LHHCOM"."OHI_PRODUCTS" ("LAST_UPDATE_DATETIME" DESC) ;