package com.liberty.health.comms.model.broker.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 15 10:53:02 CAT 2017
// ---------------------------------------------------------------------
public interface BrokerTableTypeVO extends ViewObject {
    void setpTableIdNo(Integer value);
}

