package com.liberty.health.comms.model.broker.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 15 11:11:40 CAT 2017
// ---------------------------------------------------------------------
public interface BrokerTableVO extends ViewObject {
    void setpBrokerTableIdNo(Integer value);
}

