package com.liberty.health.comms.model.broker.vo.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 04 15:56:48 CAT 2017
// ---------------------------------------------------------------------
public interface BrokerAccreditationVO extends ViewObject {
    void setpBrokerIdNo(oracle.jbo.domain.Number value);

    void updateEffDates(Integer brokerIdNo, Date currentDate);

    String checkAccreditationExists(Integer accreditationIdNo);
}

