package com.liberty.health.comms.model.broker.vo.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 15 15:41:03 CAT 2017
// ---------------------------------------------------------------------
public interface CompanyRegVO extends ViewObject {
    void setByPrimaryKeyViewCriteria(Integer companyIdNo, String countryCode);

    void updateEffDates(Integer compIdNo, String countryCode, Date currentDate);
}

