package com.liberty.health.comms.model.payment.vo;

import com.core.model.vo.classes.CoreViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 04 09:32:51 CAT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CommissionPaymentsPerGroupRowImpl extends CoreViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        CompanyIdNo,
        CountryCode,
        ParentgroupCode,
        GroupCode,
        InvoiceNo,
        FinanceInvoiceNo,
        CurrencyCode,
        ReleaseDate,
        PaymentDate,
        TotalAmount,
        TotalPayable,
        CompanyLovView1,
        OhiGroupCodesVO1,
        OhiGroupLovView_P1,
        OhiParentGroupLovView1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int COMPANYIDNO = AttributesEnum.CompanyIdNo.index();
    public static final int COUNTRYCODE = AttributesEnum.CountryCode.index();
    public static final int PARENTGROUPCODE = AttributesEnum.ParentgroupCode.index();
    public static final int GROUPCODE = AttributesEnum.GroupCode.index();
    public static final int INVOICENO = AttributesEnum.InvoiceNo.index();
    public static final int FINANCEINVOICENO = AttributesEnum.FinanceInvoiceNo.index();
    public static final int CURRENCYCODE = AttributesEnum.CurrencyCode.index();
    public static final int RELEASEDATE = AttributesEnum.ReleaseDate.index();
    public static final int PAYMENTDATE = AttributesEnum.PaymentDate.index();
    public static final int TOTALAMOUNT = AttributesEnum.TotalAmount.index();
    public static final int TOTALPAYABLE = AttributesEnum.TotalPayable.index();
    public static final int COMPANYLOVVIEW1 = AttributesEnum.CompanyLovView1.index();
    public static final int OHIGROUPCODESVO1 = AttributesEnum.OhiGroupCodesVO1.index();
    public static final int OHIGROUPLOVVIEW_P1 = AttributesEnum.OhiGroupLovView_P1.index();
    public static final int OHIPARENTGROUPLOVVIEW1 = AttributesEnum.OhiParentGroupLovView1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CommissionPaymentsPerGroupRowImpl() {
    }
}

