package com.liberty.health.comms.model.payment.vo;

import com.core.model.vo.classes.CoreViewRowImpl;

import com.liberty.health.comms.model.eo.CompanyEOImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Dec 04 12:54:07 CAT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvoiceVORowImpl extends CoreViewRowImpl {
    public static final int ENTITY_INVOICEEO = 0;
    public static final int ENTITY_COMPANYEO = 1;
    public static final int ENTITY_INVOICETYPEEO = 2;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        InvoiceNo,
        InvoiceDate,
        ContributionDate,
        CountryCode,
        CompanyIdNo,
        PaymentDate,
        PaymentAmt,
        PaymentExchRate,
        CurrencyCode,
        LastUpdateDatetime,
        Username,
        CompanyName,
        CompanyIdNoFk,
        ReleaseHoldReason,
        ReleaseDate,
        InvoiceTypeIdNo,
        InvoiceTypeDesc,
        InvoiceTypeIdNoFK,
        PreferredCurrencyCode,
        PaymentRejectDate,
        PaymentRejectDesc,
        InvoiceTaxCodes,
        InvoiceDetail,
        CompanyLovView1,
        CountryLovView1,
        InvoiceTypeLovView1,
        ActiveLov1,
        CountryLovView_N1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int INVOICENO = AttributesEnum.InvoiceNo.index();
    public static final int INVOICEDATE = AttributesEnum.InvoiceDate.index();
    public static final int CONTRIBUTIONDATE = AttributesEnum.ContributionDate.index();
    public static final int COUNTRYCODE = AttributesEnum.CountryCode.index();
    public static final int COMPANYIDNO = AttributesEnum.CompanyIdNo.index();
    public static final int PAYMENTDATE = AttributesEnum.PaymentDate.index();
    public static final int PAYMENTAMT = AttributesEnum.PaymentAmt.index();
    public static final int PAYMENTEXCHRATE = AttributesEnum.PaymentExchRate.index();
    public static final int CURRENCYCODE = AttributesEnum.CurrencyCode.index();
    public static final int LASTUPDATEDATETIME = AttributesEnum.LastUpdateDatetime.index();
    public static final int USERNAME = AttributesEnum.Username.index();
    public static final int COMPANYNAME = AttributesEnum.CompanyName.index();
    public static final int COMPANYIDNOFK = AttributesEnum.CompanyIdNoFk.index();
    public static final int RELEASEHOLDREASON = AttributesEnum.ReleaseHoldReason.index();
    public static final int RELEASEDATE = AttributesEnum.ReleaseDate.index();
    public static final int INVOICETYPEIDNO = AttributesEnum.InvoiceTypeIdNo.index();
    public static final int INVOICETYPEDESC = AttributesEnum.InvoiceTypeDesc.index();
    public static final int INVOICETYPEIDNOFK = AttributesEnum.InvoiceTypeIdNoFK.index();
    public static final int PREFERREDCURRENCYCODE = AttributesEnum.PreferredCurrencyCode.index();
    public static final int PAYMENTREJECTDATE = AttributesEnum.PaymentRejectDate.index();
    public static final int PAYMENTREJECTDESC = AttributesEnum.PaymentRejectDesc.index();
    public static final int INVOICETAXCODES = AttributesEnum.InvoiceTaxCodes.index();
    public static final int INVOICEDETAIL = AttributesEnum.InvoiceDetail.index();
    public static final int COMPANYLOVVIEW1 = AttributesEnum.CompanyLovView1.index();
    public static final int COUNTRYLOVVIEW1 = AttributesEnum.CountryLovView1.index();
    public static final int INVOICETYPELOVVIEW1 = AttributesEnum.InvoiceTypeLovView1.index();
    public static final int ACTIVELOV1 = AttributesEnum.ActiveLov1.index();
    public static final int COUNTRYLOVVIEW_N1 = AttributesEnum.CountryLovView_N1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public InvoiceVORowImpl() {
    }

    /**
     * Gets InvoiceEO entity object.
     * @return the InvoiceEO
     */
    public EntityImpl getInvoiceEO() {
        return (EntityImpl) getEntity(ENTITY_INVOICEEO);
    }

    /**
     * Gets CompanyEO entity object.
     * @return the CompanyEO
     */
    public CompanyEOImpl getCompanyEO() {
        return (CompanyEOImpl) getEntity(ENTITY_COMPANYEO);
    }

    /**
     * Gets InvoiceTypeEO entity object.
     * @return the InvoiceTypeEO
     */
    public EntityImpl getInvoiceTypeEO() {
        return (EntityImpl) getEntity(ENTITY_INVOICETYPEEO);
    }

    /**
     * Gets the attribute value for INVOICE_NO using the alias name InvoiceNo.
     * @return the INVOICE_NO
     */
    public Number getInvoiceNo() {
        return (Number) getAttributeInternal(INVOICENO);
    }

    /**
     * Sets <code>value</code> as attribute value for INVOICE_NO using the alias name InvoiceNo.
     * @param value value to set the INVOICE_NO
     */
    public void setInvoiceNo(Number value) {
        setAttributeInternal(INVOICENO, value);
    }

    /**
     * Gets the attribute value for INVOICE_DATE using the alias name InvoiceDate.
     * @return the INVOICE_DATE
     */
    public Date getInvoiceDate() {
        return (Date) getAttributeInternal(INVOICEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for INVOICE_DATE using the alias name InvoiceDate.
     * @param value value to set the INVOICE_DATE
     */
    public void setInvoiceDate(Date value) {
        setAttributeInternal(INVOICEDATE, value);
    }

    /**
     * Gets the attribute value for PAYMENT_RECEIVE_DATE using the alias name ContributionDate.
     * @return the PAYMENT_RECEIVE_DATE
     */
    public Date getContributionDate() {
        return (Date) getAttributeInternal(CONTRIBUTIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYMENT_RECEIVE_DATE using the alias name ContributionDate.
     * @param value value to set the PAYMENT_RECEIVE_DATE
     */
    public void setContributionDate(Date value) {
        setAttributeInternal(CONTRIBUTIONDATE, value);
    }

    /**
     * Gets the attribute value for COUNTRY_CODE using the alias name CountryCode.
     * @return the COUNTRY_CODE
     */
    public String getCountryCode() {
        return (String) getAttributeInternal(COUNTRYCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for COUNTRY_CODE using the alias name CountryCode.
     * @param value value to set the COUNTRY_CODE
     */
    public void setCountryCode(String value) {
        setAttributeInternal(COUNTRYCODE, value);
    }

    /**
     * Gets the attribute value for COMPANY_ID_NO using the alias name CompanyIdNo.
     * @return the COMPANY_ID_NO
     */
    public Number getCompanyIdNo() {
        return (Number) getAttributeInternal(COMPANYIDNO);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_ID_NO using the alias name CompanyIdNo.
     * @param value value to set the COMPANY_ID_NO
     */
    public void setCompanyIdNo(Number value) {
        setAttributeInternal(COMPANYIDNO, value);
    }

    /**
     * Gets the attribute value for PAYMENT_DATE using the alias name PaymentDate.
     * @return the PAYMENT_DATE
     */
    public Date getPaymentDate() {
        return (Date) getAttributeInternal(PAYMENTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYMENT_DATE using the alias name PaymentDate.
     * @param value value to set the PAYMENT_DATE
     */
    public void setPaymentDate(Date value) {
        setAttributeInternal(PAYMENTDATE, value);
    }

    /**
     * Gets the attribute value for PAYMENT_AMT using the alias name PaymentAmt.
     * @return the PAYMENT_AMT
     */
    public Number getPaymentAmt() {
        return (Number) getAttributeInternal(PAYMENTAMT);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYMENT_AMT using the alias name PaymentAmt.
     * @param value value to set the PAYMENT_AMT
     */
    public void setPaymentAmt(Number value) {
        setAttributeInternal(PAYMENTAMT, value);
    }

    /**
     * Gets the attribute value for PAYMENT_EXCH_RATE using the alias name PaymentExchRate.
     * @return the PAYMENT_EXCH_RATE
     */
    public Number getPaymentExchRate() {
        return (Number) getAttributeInternal(PAYMENTEXCHRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYMENT_EXCH_RATE using the alias name PaymentExchRate.
     * @param value value to set the PAYMENT_EXCH_RATE
     */
    public void setPaymentExchRate(Number value) {
        setAttributeInternal(PAYMENTEXCHRATE, value);
    }

    /**
     * Gets the attribute value for CURRENCY_CODE using the alias name CurrencyCode.
     * @return the CURRENCY_CODE
     */
    public String getCurrencyCode() {
        return (String) getAttributeInternal(CURRENCYCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for CURRENCY_CODE using the alias name CurrencyCode.
     * @param value value to set the CURRENCY_CODE
     */
    public void setCurrencyCode(String value) {
        setAttributeInternal(CURRENCYCODE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATETIME using the alias name LastUpdateDatetime.
     * @return the LAST_UPDATE_DATETIME
     */
    public Date getLastUpdateDatetime() {
        return (Date) getAttributeInternal(LASTUPDATEDATETIME);
    }

    /**
     * Gets the attribute value for USERNAME using the alias name Username.
     * @return the USERNAME
     */
    public String getUsername() {
        return (String) getAttributeInternal(USERNAME);
    }

    /**
     * Gets the attribute value for COMPANY_NAME using the alias name CompanyName.
     * @return the COMPANY_NAME
     */
    public String getCompanyName() {
        return (String) getAttributeInternal(COMPANYNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_NAME using the alias name CompanyName.
     * @param value value to set the COMPANY_NAME
     */
    public void setCompanyName(String value) {
        setAttributeInternal(COMPANYNAME, value);
    }

    /**
     * Gets the attribute value for COMPANY_ID_NO using the alias name CompanyIdNoFk.
     * @return the COMPANY_ID_NO
     */
    public Integer getCompanyIdNoFk() {
        return (Integer) getAttributeInternal(COMPANYIDNOFK);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_ID_NO using the alias name CompanyIdNoFk.
     * @param value value to set the COMPANY_ID_NO
     */
    public void setCompanyIdNoFk(Integer value) {
        setAttributeInternal(COMPANYIDNOFK, value);
    }

    /**
     * Gets the attribute value for RELEASE_HOLD_REASON using the alias name ReleaseHoldReason.
     * @return the RELEASE_HOLD_REASON
     */
    public String getReleaseHoldReason() {
        return (String) getAttributeInternal(RELEASEHOLDREASON);
    }

    /**
     * Sets <code>value</code> as attribute value for RELEASE_HOLD_REASON using the alias name ReleaseHoldReason.
     * @param value value to set the RELEASE_HOLD_REASON
     */
    public void setReleaseHoldReason(String value) {
        setAttributeInternal(RELEASEHOLDREASON, value);
    }

    /**
     * Gets the attribute value for RELEASE_DATE using the alias name ReleaseDate.
     * @return the RELEASE_DATE
     */
    public Date getReleaseDate() {
        return (Date) getAttributeInternal(RELEASEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for RELEASE_DATE using the alias name ReleaseDate.
     * @param value value to set the RELEASE_DATE
     */
    public void setReleaseDate(Date value) {
        setAttributeInternal(RELEASEDATE, value);
    }

    /**
     * Gets the attribute value for INVOICE_TYPE_ID_NO using the alias name InvoiceTypeIdNo.
     * @return the INVOICE_TYPE_ID_NO
     */
    public Number getInvoiceTypeIdNo() {
        return (Number) getAttributeInternal(INVOICETYPEIDNO);
    }

    /**
     * Sets <code>value</code> as attribute value for INVOICE_TYPE_ID_NO using the alias name InvoiceTypeIdNo.
     * @param value value to set the INVOICE_TYPE_ID_NO
     */
    public void setInvoiceTypeIdNo(Number value) {
        setAttributeInternal(INVOICETYPEIDNO, value);
    }

    /**
     * Gets the attribute value for INVOICE_TYPE_DESC using the alias name InvoiceTypeDesc.
     * @return the INVOICE_TYPE_DESC
     */
    public String getInvoiceTypeDesc() {
        return (String) getAttributeInternal(INVOICETYPEDESC);
    }

    /**
     * Sets <code>value</code> as attribute value for INVOICE_TYPE_DESC using the alias name InvoiceTypeDesc.
     * @param value value to set the INVOICE_TYPE_DESC
     */
    public void setInvoiceTypeDesc(String value) {
        setAttributeInternal(INVOICETYPEDESC, value);
    }

    /**
     * Gets the attribute value for INVOICE_TYPE_ID_NO using the alias name InvoiceTypeIdNoFK.
     * @return the INVOICE_TYPE_ID_NO
     */
    public Number getInvoiceTypeIdNoFK() {
        return (Number) getAttributeInternal(INVOICETYPEIDNOFK);
    }

    /**
     * Sets <code>value</code> as attribute value for INVOICE_TYPE_ID_NO using the alias name InvoiceTypeIdNoFK.
     * @param value value to set the INVOICE_TYPE_ID_NO
     */
    public void setInvoiceTypeIdNoFK(Number value) {
        setAttributeInternal(INVOICETYPEIDNOFK, value);
    }

    /**
     * Gets the attribute value for PREFERRED_CURRENCY_CODE using the alias name PreferredCurrencyCode.
     * @return the PREFERRED_CURRENCY_CODE
     */
    public String getPreferredCurrencyCode() {
        return (String) getAttributeInternal(PREFERREDCURRENCYCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for PREFERRED_CURRENCY_CODE using the alias name PreferredCurrencyCode.
     * @param value value to set the PREFERRED_CURRENCY_CODE
     */
    public void setPreferredCurrencyCode(String value) {
        setAttributeInternal(PREFERREDCURRENCYCODE, value);
    }

    /**
     * Gets the attribute value for PAYMENT_REJECT_DATE using the alias name PaymentRejectDate.
     * @return the PAYMENT_REJECT_DATE
     */
    public Date getPaymentRejectDate() {
        return (Date) getAttributeInternal(PAYMENTREJECTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYMENT_REJECT_DATE using the alias name PaymentRejectDate.
     * @param value value to set the PAYMENT_REJECT_DATE
     */
    public void setPaymentRejectDate(Date value) {
        setAttributeInternal(PAYMENTREJECTDATE, value);
    }

    /**
     * Gets the attribute value for PAYMENT_REJECT_DESC using the alias name PaymentRejectDesc.
     * @return the PAYMENT_REJECT_DESC
     */
    public String getPaymentRejectDesc() {
        return (String) getAttributeInternal(PAYMENTREJECTDESC);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYMENT_REJECT_DESC using the alias name PaymentRejectDesc.
     * @param value value to set the PAYMENT_REJECT_DESC
     */
    public void setPaymentRejectDesc(String value) {
        setAttributeInternal(PAYMENTREJECTDESC, value);
    }

    /**
     * Gets the attribute value for INVOICE_TAX_CODES using the alias name InvoiceTaxCodes.
     * @return the INVOICE_TAX_CODES
     */
    public String getInvoiceTaxCodes() {
        return (String) getAttributeInternal(INVOICETAXCODES);
    }

    /**
     * Sets <code>value</code> as attribute value for INVOICE_TAX_CODES using the alias name InvoiceTaxCodes.
     * @param value value to set the INVOICE_TAX_CODES
     */
    public void setInvoiceTaxCodes(String value) {
        setAttributeInternal(INVOICETAXCODES, value);
    }


    /**
     * Gets the associated <code>RowIterator</code> using master-detail link InvoiceDetail.
     */
    public RowIterator getInvoiceDetail() {
        return (RowIterator) getAttributeInternal(INVOICEDETAIL);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CompanyLovView1.
     */
    public RowSet getCompanyLovView1() {
        return (RowSet) getAttributeInternal(COMPANYLOVVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CountryLovView1.
     */
    public RowSet getCountryLovView1() {
        return (RowSet) getAttributeInternal(COUNTRYLOVVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> InvoiceTypeLovView1.
     */
    public RowSet getInvoiceTypeLovView1() {
        return (RowSet) getAttributeInternal(INVOICETYPELOVVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ActiveLov1.
     */
    public RowSet getActiveLov1() {
        return (RowSet) getAttributeInternal(ACTIVELOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CountryLovView_N1.
     */
    public RowSet getCountryLovView_N1() {
        return (RowSet) getAttributeInternal(COUNTRYLOVVIEW_N1);
    }
}

