package com.liberty.health.comms.model.payment.vo;

import com.core.model.vo.classes.CoreViewRowImpl;

import com.liberty.health.comms.model.payment.vo.common.InvoicesPaidWhtVORow;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 09 08:28:04 CAT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvoicesPaidWhtVORowImpl extends CoreViewRowImpl implements InvoicesPaidWhtVORow {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        InvoiceNo,
        CompanyIdNo,
        CompanyName,
        BusinessUnit,
        CountryCode,
        InvoiceType,
        InvoiceTypeId,
        ReleaseDate,
        PaymentDate,
        ReleaseToPayment,
        InvoiceCurrencyCode,
        PaymentCurrencyCode,
        CommPercentage,
        CommissionTotal,
        TotalTax,
        TotalPaid,
        Voided;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int INVOICENO = AttributesEnum.InvoiceNo.index();
    public static final int COMPANYIDNO = AttributesEnum.CompanyIdNo.index();
    public static final int COMPANYNAME = AttributesEnum.CompanyName.index();
    public static final int BUSINESSUNIT = AttributesEnum.BusinessUnit.index();
    public static final int COUNTRYCODE = AttributesEnum.CountryCode.index();
    public static final int INVOICETYPE = AttributesEnum.InvoiceType.index();
    public static final int INVOICETYPEID = AttributesEnum.InvoiceTypeId.index();
    public static final int RELEASEDATE = AttributesEnum.ReleaseDate.index();
    public static final int PAYMENTDATE = AttributesEnum.PaymentDate.index();
    public static final int RELEASETOPAYMENT = AttributesEnum.ReleaseToPayment.index();
    public static final int INVOICECURRENCYCODE = AttributesEnum.InvoiceCurrencyCode.index();
    public static final int PAYMENTCURRENCYCODE = AttributesEnum.PaymentCurrencyCode.index();
    public static final int COMMPERCENTAGE = AttributesEnum.CommPercentage.index();
    public static final int COMMISSIONTOTAL = AttributesEnum.CommissionTotal.index();
    public static final int TOTALTAX = AttributesEnum.TotalTax.index();
    public static final int TOTALPAID = AttributesEnum.TotalPaid.index();
    public static final int VOIDED = AttributesEnum.Voided.index();

    /**
     * This is the default constructor (do not remove).
     */
    public InvoicesPaidWhtVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute InvoiceNo.
     * @return the InvoiceNo
     */
    public String getInvoiceNo() {
        return (String) getAttributeInternal(INVOICENO);
    }

    /**
     * Gets the attribute value for the calculated attribute CompanyIdNo.
     * @return the CompanyIdNo
     */
    public String getCompanyIdNo() {
        return (String) getAttributeInternal(COMPANYIDNO);
    }

    /**
     * Gets the attribute value for the calculated attribute CompanyName.
     * @return the CompanyName
     */
    public String getCompanyName() {
        return (String) getAttributeInternal(COMPANYNAME);
    }

    /**
     * Gets the attribute value for the calculated attribute BusinessUnit.
     * @return the BusinessUnit
     */
    public String getBusinessUnit() {
        return (String) getAttributeInternal(BUSINESSUNIT);
    }

    /**
     * Gets the attribute value for the calculated attribute CountryCode.
     * @return the CountryCode
     */
    public String getCountryCode() {
        return (String) getAttributeInternal(COUNTRYCODE);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoiceType.
     * @return the InvoiceType
     */
    public String getInvoiceType() {
        return (String) getAttributeInternal(INVOICETYPE);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoiceTypeId.
     * @return the InvoiceTypeId
     */
    public Number getInvoiceTypeId() {
        return (Number) getAttributeInternal(INVOICETYPEID);
    }

    /**
     * Gets the attribute value for the calculated attribute ReleaseDate.
     * @return the ReleaseDate
     */
    public Date getReleaseDate() {
        return (Date) getAttributeInternal(RELEASEDATE);
    }

    /**
     * Gets the attribute value for the calculated attribute PaymentDate.
     * @return the PaymentDate
     */
    public Date getPaymentDate() {
        return (Date) getAttributeInternal(PAYMENTDATE);
    }

    /**
     * Gets the attribute value for the calculated attribute ReleaseToPayment.
     * @return the ReleaseToPayment
     */
    public Number getReleaseToPayment() {
        return (Number) getAttributeInternal(RELEASETOPAYMENT);
    }


    /**
     * Gets the attribute value for the calculated attribute InvoiceCurrencyCode.
     * @return the InvoiceCurrencyCode
     */
    public String getInvoiceCurrencyCode() {
        return (String) getAttributeInternal(INVOICECURRENCYCODE);
    }

    /**
     * Gets the attribute value for the calculated attribute PaymentCurrencyCode.
     * @return the PaymentCurrencyCode
     */
    public String getPaymentCurrencyCode() {
        return (String) getAttributeInternal(PAYMENTCURRENCYCODE);
    }

    /**
     * Gets the attribute value for the calculated attribute CommPercentage.
     * @return the CommPercentage
     */
    public String getCommPercentage() {
        return (String) getAttributeInternal(COMMPERCENTAGE);
    }

    /**
     * Gets the attribute value for the calculated attribute CommissionTotal.
     * @return the CommissionTotal
     */
    public Double getCommissionTotal() {
        return (Double) getAttributeInternal(COMMISSIONTOTAL);
    }

    /**
     * Gets the attribute value for the calculated attribute TotalTax.
     * @return the TotalTax
     */
    public Double getTotalTax() {
        return (Double) getAttributeInternal(TOTALTAX);
    }

    /**
     * Gets the attribute value for the calculated attribute TotalPaid.
     * @return the TotalPaid
     */
    public Double getTotalPaid() {
        return (Double) getAttributeInternal(TOTALPAID);
    }

    /**
     * Gets the attribute value for the calculated attribute Voided.
     * @return the Voided
     */
    public String getVoided() {
        return (String) getAttributeInternal(VOIDED);
    }
}

