package com.liberty.health.comms.model.payment.vo;

import com.core.model.vo.classes.CoreViewObjectImpl;


import com.liberty.health.comms.model.payment.vo.common.InvoiceVO;

import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 26 15:08:58 CAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvoiceVOImpl extends CoreViewObjectImpl implements InvoiceVO {
    /**
     * This is the default constructor (do not remove).
     */
    public InvoiceVOImpl() {
    }


    /**
     * Returns the variable value for pInvoiceNo.
     * @return variable value for pInvoiceNo
     */
    public Number getpInvoiceNo() {
        return (Number) ensureVariableManager().getVariableValue("pInvoiceNo");
    }

    /**
     * Sets <code>value</code> for variable pInvoiceNo.
     * @param value value to bind as pInvoiceNo
     */
    public void setpInvoiceNo(Number value) {
       
        ensureVariableManager().setVariableValue("pInvoiceNo", value);
        
    }

    /**
     * Returns the variable value for pCompanyIdNo.
     * @return variable value for pCompanyIdNo
     */
    public Number getpCompanyIdNo() {
        return (Number) ensureVariableManager().getVariableValue("pCompanyIdNo");
    }

    /**
     * Sets <code>value</code> for variable pCompanyIdNo.
     * @param value value to bind as pCompanyIdNo
     */
    public void setpCompanyIdNo(Number value) {
        ensureVariableManager().setVariableValue("pCompanyIdNo", value);
    }


    /**
     * Returns the bind variable value for pCountryList.
     * @return bind variable value for pCountryList
     */
    public String getpCountryList() {
        return (String) getNamedWhereClauseParam("pCountryList");
    }

    /**
     * Sets <code>value</code> for bind variable pCountryList.
     * @param value value to bind as pCountryList
     */
    public void setpCountryList(String value) {
        setNamedWhereClauseParam("pCountryList", value);
    }
}

