package com.liberty.health.comms.model.payment.vo;

import com.core.model.vo.classes.CoreViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 14 13:06:41 CAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SearchPaymentRoViewImpl extends CoreViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SearchPaymentRoViewImpl() {
    }
}

