package com.liberty.health.comms.model.watchlist.vo;

import com.core.model.vo.classes.CoreViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 13 19:26:03 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GroupCommPercOutstandingApprovalRoViewImpl extends CoreViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public GroupCommPercOutstandingApprovalRoViewImpl() {
    }

    /**
     * Returns the bind variable value for pcountrylist.
     * @return bind variable value for pcountrylist
     */
    public String getpcountrylist() {
        return (String) getNamedWhereClauseParam("pcountrylist");
    }

    /**
     * Sets <code>value</code> for bind variable pcountrylist.
     * @param value value to bind as pcountrylist
     */
    public void setpcountrylist(String value) {
        setNamedWhereClauseParam("pcountrylist", value);
    }

    /**
     * Returns the variable value for pParentgroupCode.
     * @return variable value for pParentgroupCode
     */
    public String getpParentgroupCode() {
        return (String) ensureVariableManager().getVariableValue("pParentgroupCode");
    }

    /**
     * Sets <code>value</code> for variable pParentgroupCode.
     * @param value value to bind as pParentgroupCode
     */
    public void setpParentgroupCode(String value) {
        ensureVariableManager().setVariableValue("pParentgroupCode", value);
    }
}

