package com.core.model.vo;

import com.core.model.vo.classes.CoreViewObjectImpl;
import com.core.model.vo.common.WebApplObjectLangMenuView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 05 12:06:06 CAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WebApplObjectLangMenuViewImpl extends CoreViewObjectImpl implements WebApplObjectLangMenuView {
    /**
     * This is the default constructor (do not remove).
     */
    public WebApplObjectLangMenuViewImpl() {
    }

    /**
     * Returns the variable value for webApplObjetNoVar.
     * @return variable value for webApplObjetNoVar
     */
    public Integer getwebApplObjetNoVar() {
        return (Integer) ensureVariableManager().getVariableValue("webApplObjetNoVar");
    }

    /**
     * Sets <code>value</code> for variable webApplObjetNoVar.
     * @param value value to bind as webApplObjetNoVar
     */
    public void setwebApplObjetNoVar(Integer value) {
        ensureVariableManager().setVariableValue("webApplObjetNoVar", value);
    }

    /**
     * Returns the variable value for localCodeVar.
     * @return variable value for localCodeVar
     */
    public String getlocalCodeVar() {
        return (String) ensureVariableManager().getVariableValue("localCodeVar");
    }

    /**
     * Sets <code>value</code> for variable localCodeVar.
     * @param value value to bind as localCodeVar
     */
    public void setlocalCodeVar(String value) {
        ensureVariableManager().setVariableValue("localCodeVar", value);
    }

    /**
     * Method sets all required bind variables for UpdateMenuItemViewCriteria view criteria and executes query
     * @param localCode
     * @param webApplObjNo
     */
    public void setUpdateMenuItemViewCriteria(String localCode, Integer webApplObjNo) {
        this.setlocalCodeVar(localCode);
        this.setwebApplObjetNoVar(webApplObjNo);
        this.executeQuery();
    }
}

