package com.liberty.health.comms.model.brokerage.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 31 15:33:31 CAT 2019
// ---------------------------------------------------------------------
public interface CommsPartialReceiptVO extends ViewObject {
    void setCreatedBy(String username);
}

