package com.liberty.health.comms.model.brokerage.vo.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 31 09:54:46 CAT 2019
// ---------------------------------------------------------------------
public interface CommsPartialReceiptApproveVORow extends Row {
    void setActiveYn(String value);

    void setApprovedBy(String value);
}

