package com.liberty.health.comms.model.brokerage.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 31 10:26:16 CAT 2019
// ---------------------------------------------------------------------
public interface CommsPartialReceiptApproveVO extends ViewObject {
    String setAuthUsername(String username);
}

