package com.liberty.health.comms.model.brokerage.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 28 15:48:09 CAT 2017
// ---------------------------------------------------------------------
public interface CompanyCountryVO extends ViewObject {
    void setpCompanyIdNo(Integer value);
}

