package com.liberty.health.comms.model.brokerage.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 06 13:05:38 CAT 2017
// ---------------------------------------------------------------------
public interface CompanyTableTypeVO extends ViewObject {
    void setpTableIdNo(Integer value);
}

