package com.liberty.health.comms.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 26 10:54:57 CAT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CommHubJobsLovViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CommHubJobsLovViewImpl() {
    }
}

