package com.liberty.health.comms.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Mar 26 09:21:38 CAT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OhiCompanyGroupCountryLovImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public OhiCompanyGroupCountryLovImpl() {
    }
}

