package com.liberty.health.comms.lov;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 12 08:30:23 CAT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PayInvoicesLovViewRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        CompanyIdNo,
        InvoiceNo,
        PayCommsInvoiceNo1,
        CompanyLovView1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int COMPANYIDNO = AttributesEnum.CompanyIdNo.index();
    public static final int INVOICENO = AttributesEnum.InvoiceNo.index();
    public static final int PAYCOMMSINVOICENO1 = AttributesEnum.PayCommsInvoiceNo1.index();
    public static final int COMPANYLOVVIEW1 = AttributesEnum.CompanyLovView1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PayInvoicesLovViewRowImpl() {
    }
}

