package com.liberty.health.comms.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 12 08:30:24 CAT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PayInvoicesLovViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PayInvoicesLovViewImpl() {
    }
}

