package com.liberty.health.comms.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 18 09:52:49 CAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PaymentsProcessedStatusLovViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PaymentsProcessedStatusLovViewImpl() {
    }
}

