package com.liberty.health.comms.model.ohi.services.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 29 11:19:55 CAT 2017
// ---------------------------------------------------------------------
public interface OhiStructureAM extends ApplicationModule {
    String fixBackDatedChanges(oracle.jbo.domain.Number polId, String userame);
}

