select * from ALL_TAB_COLS;
select OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_DEFAULT from ALL_TAB_COLS where COLUMN_NAME in ('USERNAME', 'TRANSACTION_USERNAME');
update ALL_TAB_COLS on COLUMN_NAME = 'TRANSACTION_USERNAME' and TABLE_NAME = 'OHI_PRODUCT' set cols.DATA_DEFAULT = user;

select OWNER, TABLE_NAME, DATA_DEFAULT, 'alter table ' || TABLE_NAME || ' modify (' || COLUMN_NAME || ' DEFAULT USER);' from ALL_TAB_COLS where COLUMN_NAME in ('USERNAME', 'TRANSACTION_USERNAME') and TABLE_NAME like '%OHI%';
select OWNER, TABLE_NAME, DATA_DEFAULT, 'alter table ' || TABLE_NAME || ' modify (' || COLUMN_NAME || ' DEFAULT USER);' from ALL_TAB_COLS where COLUMN_NAME in ('USERNAME', 'TRANSACTION_USERNAME') and TABLE_NAME like '%AUD%';

select OWNER, TABLE_NAME, DATA_DEFAULT, 'alter table ' || TABLE_NAME || ' modify (' || COLUMN_NAME || ' DEFAULT SYSDATE);' from ALL_TAB_COLS where COLUMN_NAME in ('TRANSACTION_DATETIME') and TABLE_NAME like '%OHI%';
select OWNER, TABLE_NAME, DATA_DEFAULT, 'alter table ' || TABLE_NAME || ' modify (' || COLUMN_NAME || ' DEFAULT SYSDATE);' from ALL_TAB_COLS where COLUMN_NAME in ('TRANSACTION_DATETIME') and TABLE_NAME like '%AUD%';
