DECLARE
  l_percentage  ohi_comm_perc.comm_perc%type;
  l_description ohi_comm_perc.comm_desc%type;
  l_return_msg  VARCHAR2(500);
BEGIN
-- /*
  dbms_output.put_line('NULL Parameters');
  commissions_pkg.get_percentage(p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
-- * * * * * * * * * * * * * * * * * * * *
  dbms_output.put_line('POEP Test');
--  dbms_output.put_line('POEP 3288 - 1 Oct 16');
  commissions_pkg.get_percentage(p_date => '01-OCT-16', p_poep => 3288, p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('POEP 3288');
  commissions_pkg.get_percentage(p_poep => 3288, p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('POEP 3288 - 1 Dec 17');
  commissions_pkg.get_percentage(p_date => '01-DEC-17', p_poep => 3288, p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('POEP 3288 - 1 Jan 18 - Company doesn''t have a Percentage');
  commissions_pkg.get_percentage(p_date => '01-JAN-18', p_poep => 3288, p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('POEP 3304');
  commissions_pkg.get_percentage(p_poep => 3304, p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('POEP 3304 - 1 Dec 17');
  commissions_pkg.get_percentage(p_date => '01-DEC-17', p_poep => 3304, p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('POEP 3304 - 1 Jan 18');
  commissions_pkg.get_percentage(p_date => '01-JAN-18', p_poep => 3304, p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('POEP 3304 - 1 Mar 18');
  commissions_pkg.get_percentage(p_date => '01-MAR-18', p_poep => 3304, p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('POEP 3304 - 1 May 18');
  commissions_pkg.get_percentage(p_date => '01-MAY-18', p_poep => 3304, p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('POEP 3304 - 1 Jun 18');
  commissions_pkg.get_percentage(p_date => '01-JUN-18', p_poep => 3304, p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
-- * * * * * * * * * * * * * * * * * * * *
  dbms_output.put_line('Person Test');
--  dbms_output.put_line('Person 6890989-00 - 1 Oct 16');
  commissions_pkg.get_percentage(p_date => '01-OCT-16', p_person => '6890989-00', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Person 6890989-00');
  commissions_pkg.get_percentage(p_person => '6890989-00', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Person 6890989-00 - 1 Dec 17');
  commissions_pkg.get_percentage(p_date => '01-DEC-17', p_person => '6890989-00', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Person 6890989-00 - 1 Jan 18 - Company doesn''t have a Percentage');
  commissions_pkg.get_percentage(p_date => '01-JAN-18', p_person => '6890989-00', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Person 5539242-00');
  commissions_pkg.get_percentage(p_person => '5539242-00', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Person 5539242-00 - 1 Dec 17');
  commissions_pkg.get_percentage(p_date => '01-DEC-17', p_person => '5539242-00', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Person 5539242-00 - 1 Jan 18');
  commissions_pkg.get_percentage(p_date => '01-JAN-18', p_person => '5539242-00', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Person 5539242-00 - 1 Jan 18');
  commissions_pkg.get_percentage(p_date => '01-JAN-18', p_person => '5539242-00', p_product => 'LSES', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Person 5539242-00 - 1 Mar 18');
  commissions_pkg.get_percentage(p_date => '01-MAR-18', p_person => '5539242-00', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Person 5539242-00 - 1 May 18');
  commissions_pkg.get_percentage(p_date => '01-MAY-18', p_person => '5539242-00', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Person 5539242-00 - 1 Jun 18');
  commissions_pkg.get_percentage(p_date => '01-JUN-18', p_person => '5539242-00', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
-- * * * * * * * * * * * * * * * * * * * *
  dbms_output.put_line('Policy Test');
--  dbms_output.put_line('Policy 6890989 - 1 Oct 16');
  commissions_pkg.get_percentage(p_date => '01-OCT-16', p_policy => '6890989', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Policy 6890989');
  commissions_pkg.get_percentage(p_policy => '6890989', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Policy 6890989 - 1 Dec 17');
  commissions_pkg.get_percentage(p_date => '01-DEC-17', p_policy => '6890989', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Policy 6890989 - 1 Jan 18 - Company doesn''t have a Percentage');
  commissions_pkg.get_percentage(p_date => '01-JAN-18', p_policy => '6890989', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Policy 5539242');
  commissions_pkg.get_percentage(p_policy => '5539242', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Policy 5539242 - 1 Dec 17');
  commissions_pkg.get_percentage(p_date => '01-DEC-17', p_policy => '5539242', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Policy 5539242 - 1 Jan 18');
  commissions_pkg.get_percentage(p_date => '01-JAN-18', p_policy => '5539242', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Policy 5539242 - 1 Jan 18');
  commissions_pkg.get_percentage(p_date => '01-JAN-18', p_policy => '5539242', p_product => 'LSES', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Policy 5539242 - 1 Mar 18');
  commissions_pkg.get_percentage(p_date => '01-MAR-18', p_policy => '5539242', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Policy 5539242 - 1 May 18');
  commissions_pkg.get_percentage(p_date => '01-MAY-18', p_policy => '5539242', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Policy 5539242 - 1 Jun 18');
  commissions_pkg.get_percentage(p_date => '01-JUN-18', p_policy => '5539242', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
-- * * * * * * * * * * * * * * * * * * * *
  dbms_output.put_line('Group Product Test');
--  dbms_output.put_line('Group LIQMINDEVEL, Product LSES - 1 Oct 16');
  commissions_pkg.get_percentage(p_date => '01-OCT-16', p_product => 'LSES', p_group => 'LIQMINDEVEL', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Group LIQMINDEVEL, Product LSES');
  commissions_pkg.get_percentage(p_product => 'LSES', p_group => 'LIQMINDEVEL', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Group LIQMINDEVEL, Product LSES - 1 Dec 17');
  commissions_pkg.get_percentage(p_date => '01-DEC-17', p_product => 'LSES', p_group => 'LIQMINDEVEL', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Group LIQMINDEVEL, Product LSES - 1 Jan 18 - Company doesn''t have a Percentage');
  commissions_pkg.get_percentage(p_date => '01-JAN-18', p_product => 'LSES', p_group => 'LIQMINDEVEL', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Group BAYLORLESOTH, Product LSES');
  commissions_pkg.get_percentage(p_product => 'LSES', p_group => 'BAYLORLESOTH', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Group BAYLORLESOTH, Product LSES - 1 Dec 17');
  commissions_pkg.get_percentage(p_date => '01-DEC-17', p_product => 'LSES', p_group => 'BAYLORLESOTH', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Group BAYLORLESOTH, Product LSES - 1 Jan 18');
  commissions_pkg.get_percentage(p_date => '01-JAN-18', p_product => 'LSES', p_group => 'BAYLORLESOTH', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Group BAYLORLESOTH, Product LSES - 1 Jan 18');
  commissions_pkg.get_percentage(p_date => '01-JAN-18', p_product => 'LSES', p_group => 'BAYLORLESOTH', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Group BAYLORLESOTH, Product LSES - 1 Mar 18');
  commissions_pkg.get_percentage(p_date => '01-MAR-18', p_product => 'LSES', p_group => 'BAYLORLESOTH', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Group BAYLORLESOTH, Product LSES - 1 May 18');
  commissions_pkg.get_percentage(p_date => '01-MAY-18', p_product => 'LSES', p_group => 'BAYLORLESOTH', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Group BAYLORLESOTH, Product LSES - 1 Jun 18');
  commissions_pkg.get_percentage(p_date => '01-JUN-18', p_product => 'LSES', p_group => 'BAYLORLESOTH', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
-- * * * * * * * * * * * * * * * * * * * *
  dbms_output.put_line('Group Test');
--  dbms_output.put_line('Group LIQMINDEVEL - 1 Oct 16');
  commissions_pkg.get_percentage(p_date => '01-OCT-16', p_group => 'LIQMINDEVEL', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Group LIQMINDEVEL');
  commissions_pkg.get_percentage(p_group => 'LIQMINDEVEL', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Group LIQMINDEVEL - 1 Dec 17');
  commissions_pkg.get_percentage(p_date => '01-DEC-17', p_group => 'LIQMINDEVEL', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Group LIQMINDEVEL - 1 Jan 18 - Company doesn''t have a Percentage');
  commissions_pkg.get_percentage(p_date => '01-JAN-18', p_group => 'LIQMINDEVEL', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Group BAYLORLESOTH');
  commissions_pkg.get_percentage(p_group => 'BAYLORLESOTH', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Group BAYLORLESOTH - 1 Dec 17');
  commissions_pkg.get_percentage(p_date => '01-DEC-17', p_group => 'BAYLORLESOTH', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Group BAYLORLESOTH - 1 Jan 18');
  commissions_pkg.get_percentage(p_date => '01-JAN-18', p_group => 'BAYLORLESOTH', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Group BAYLORLESOTH - 1 Jan 18');
  commissions_pkg.get_percentage(p_date => '01-JAN-18', p_group => 'BAYLORLESOTH', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Group BAYLORLESOTH - 1 Mar 18');
  commissions_pkg.get_percentage(p_date => '01-MAR-18', p_group => 'BAYLORLESOTH', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Group BAYLORLESOTH - 1 May 18');
  commissions_pkg.get_percentage(p_date => '01-MAY-18', p_group => 'BAYLORLESOTH', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Group BAYLORLESOTH - 1 Jun 18');
  commissions_pkg.get_percentage(p_date => '01-JUN-18', p_group => 'BAYLORLESOTH', p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
-- * * * * * * * * * * * * * * * * * * * *
  dbms_output.put_line('Broker Test');
--  dbms_output.put_line('Broker 635 - 1 Oct 16');
  commissions_pkg.get_percentage(p_date => '01-OCT-16', p_broker => 635, p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Broker 635');
  commissions_pkg.get_percentage(p_broker => 635, p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Broker 635 - 1 Dec 17');
  commissions_pkg.get_percentage(p_date => '01-DEC-17', p_broker => 635, p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Broker 635 - 1 Jan 18 - Company doesn''t have a Percentage');
  commissions_pkg.get_percentage(p_date => '01-JAN-18', p_broker => 635, p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Broker 636 - 1 Oct 16');
  commissions_pkg.get_percentage(p_date => '01-OCT-16', p_broker => 636, p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Broker 636');
  commissions_pkg.get_percentage(p_broker => 636, p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Broker 636 - 1 Dec 17');
  commissions_pkg.get_percentage(p_date => '01-DEC-17', p_broker => 636, p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Broker 636 - 1 Jan 18 - Company doesn''t have a Percentage');
  commissions_pkg.get_percentage(p_date => '01-JAN-18', p_broker => 636, p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Broker 787 - 1 Oct 16');
  commissions_pkg.get_percentage(p_date => '01-OCT-16', p_broker => 787, p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Broker 787');
  commissions_pkg.get_percentage(p_broker => 787, p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Broker 787 - 1 Dec 17');
  commissions_pkg.get_percentage(p_date => '01-DEC-17', p_broker => 787, p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Broker 787 - 1 Jan 18 - Company doesn''t have a Percentage');
  commissions_pkg.get_percentage(p_date => '01-JAN-18', p_broker => 787, p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Broker 10000061 - 1 Oct 16');
  commissions_pkg.get_percentage(p_date => '01-OCT-16', p_broker => 10000061, p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Broker 10000061');
  commissions_pkg.get_percentage(p_broker => 10000061, p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Broker 10000061 - 1 Dec 17');
  commissions_pkg.get_percentage(p_date => '01-DEC-17', p_broker => 10000061, p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Broker 10000061 - 1 Jan 18 - Company doesn''t have a Percentage');
  commissions_pkg.get_percentage(p_date => '01-JAN-18', p_broker => 10000061, p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
-- * * * * * * * * * * * * * * * * * * * *
  dbms_output.put_line('Company Test');
--  dbms_output.put_line('Company 10000061 - 1 Oct 16');
  commissions_pkg.get_percentage(p_date => '01-OCT-16', p_company => 10000061, p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Company 10000061');
  commissions_pkg.get_percentage(p_company => 10000061, p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Company 10000061 - 1 Dec 17');
  commissions_pkg.get_percentage(p_date => '01-DEC-17', p_company => 10000061, p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Company 10000061 - 1 Jan 18 - Company doesn''t have a Percentage');
  commissions_pkg.get_percentage(p_date => '01-JAN-18', p_company => 10000061, p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Company 161 - 1 Oct 16');
  commissions_pkg.get_percentage(p_date => '01-OCT-16', p_company => 161, p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Company 161');
  commissions_pkg.get_percentage(p_company => 161, p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Company 770000000 - 1 Oct 16');
  commissions_pkg.get_percentage(p_date => '01-OCT-16', p_company => 770000000, p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
--  dbms_output.put_line('Company 770000000');
  commissions_pkg.get_percentage(p_company => 770000000, p_percentage => l_percentage, p_description => l_description, p_return_msg => l_return_msg);
  dbms_output.put_line('  Message    : ' ||  l_return_msg);
END;