package com.liberty.health.comm.vc.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 14 09:21:58 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CommsPaymentsReceivedVO_NImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CommsPaymentsReceivedVO_NImpl() {
    }
}

