package com.liberty.health.comms.model.lookup.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 05 10:52:54 CAT 2017
// ---------------------------------------------------------------------
public interface AccreditationTypeVO extends ViewObject {
    void setpAccreditationTypeIdNo(Integer value);
}

