package com.liberty.health.comms.model.lookup.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 12 10:50:31 CAT 2017
// ---------------------------------------------------------------------
public interface AddressTypeVO extends ViewObject {
    void setpAddressTypeCode(String value);
}

