package com.liberty.health.comms.model.lookup.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 03 10:23:51 CAT 2017
// ---------------------------------------------------------------------
public interface CompanyContactTypeVO extends ViewObject {
    void setpCompanyContactTypeIdNo(Integer value);
}

