package com.liberty.health.comms.model.comms.views.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 13 06:40:33 CAT 2018
// ---------------------------------------------------------------------
public interface CommsCalcCompareAllDetailVO extends ViewObject {
    void returnAllCommsDetail(String countryCode, String groupCode, String productCode, String companyIdNo, String parentgroupCode);
}

