package com.liberty.health.comms.model.comms.views.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 12 12:16:59 CAT 2018
// ---------------------------------------------------------------------
public interface CommsCalcCompareSummaryVO extends ViewObject {
    void searchCommsRunResults(String countryCode, String groupCode, String productCode, String companyIdNo, String parentgroupCode);
}

