package com.liberty.health.comms.model.brokerage.vo;

import com.core.model.vo.classes.CoreViewRowImpl;

import com.liberty.health.comms.model.eo.CommsPartialReceiptEOImpl;

import oracle.jbo.RowSet;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 15 11:48:08 CAT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CommsPartialReceiptVORowImpl extends CoreViewRowImpl {


    public static final int ENTITY_COMMSPARTIALRECEIPTEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ActiveYn,
        ApprovedBy,
        Bu,
        CommsPartialPk,
        CommsPercentage,
        CompanyIdNo,
        CountryCode,
        CreatedBy,
        CreationDate,
        EffectiveEndDate,
        EffectiveStartDate,
        GroupCode,
        InterfaceToComms,
        LastUpdateDate,
        LastUpdatedBy,
        CompanyLovView1,
        CountryLovView1,
        FusionActiveBuVO1,
        CommonYN1,
        OhiGroupLovView1,
        CountryLovView_N1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ACTIVEYN = AttributesEnum.ActiveYn.index();
    public static final int APPROVEDBY = AttributesEnum.ApprovedBy.index();
    public static final int BU = AttributesEnum.Bu.index();
    public static final int COMMSPARTIALPK = AttributesEnum.CommsPartialPk.index();
    public static final int COMMSPERCENTAGE = AttributesEnum.CommsPercentage.index();
    public static final int COMPANYIDNO = AttributesEnum.CompanyIdNo.index();
    public static final int COUNTRYCODE = AttributesEnum.CountryCode.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int EFFECTIVEENDDATE = AttributesEnum.EffectiveEndDate.index();
    public static final int EFFECTIVESTARTDATE = AttributesEnum.EffectiveStartDate.index();
    public static final int GROUPCODE = AttributesEnum.GroupCode.index();
    public static final int INTERFACETOCOMMS = AttributesEnum.InterfaceToComms.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int COMPANYLOVVIEW1 = AttributesEnum.CompanyLovView1.index();
    public static final int COUNTRYLOVVIEW1 = AttributesEnum.CountryLovView1.index();
    public static final int FUSIONACTIVEBUVO1 = AttributesEnum.FusionActiveBuVO1.index();
    public static final int COMMONYN1 = AttributesEnum.CommonYN1.index();
    public static final int OHIGROUPLOVVIEW1 = AttributesEnum.OhiGroupLovView1.index();
    public static final int COUNTRYLOVVIEW_N1 = AttributesEnum.CountryLovView_N1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CommsPartialReceiptVORowImpl() {
    }


    /**
     * Gets CommsPartialReceiptEO entity object.
     * @return the CommsPartialReceiptEO
     */
    public CommsPartialReceiptEOImpl getCommsPartialReceiptEO() {
        return (CommsPartialReceiptEOImpl) getEntity(ENTITY_COMMSPARTIALRECEIPTEO);
    }

    /**
     * Gets the attribute value for ACTIVE_YN using the alias name ActiveYn.
     * @return the ACTIVE_YN
     */
    public String getActiveYn() {
        return (String) getAttributeInternal(ACTIVEYN);
    }

    /**
     * Sets <code>value</code> as attribute value for ACTIVE_YN using the alias name ActiveYn.
     * @param value value to set the ACTIVE_YN
     */
    public void setActiveYn(String value) {
        setAttributeInternal(ACTIVEYN, value);
    }

    /**
     * Gets the attribute value for APPROVED_BY using the alias name ApprovedBy.
     * @return the APPROVED_BY
     */
    public String getApprovedBy() {
        return (String) getAttributeInternal(APPROVEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for APPROVED_BY using the alias name ApprovedBy.
     * @param value value to set the APPROVED_BY
     */
    public void setApprovedBy(String value) {
        setAttributeInternal(APPROVEDBY, value);
    }

    /**
     * Gets the attribute value for BU using the alias name Bu.
     * @return the BU
     */
    public String getBu() {
        return (String) getAttributeInternal(BU);
    }

    /**
     * Sets <code>value</code> as attribute value for BU using the alias name Bu.
     * @param value value to set the BU
     */
    public void setBu(String value) {
        setAttributeInternal(BU, value);
    }

    /**
     * Gets the attribute value for COMMS_PARTIAL_PK using the alias name CommsPartialPk.
     * @return the COMMS_PARTIAL_PK
     */
    public Integer getCommsPartialPk() {
        return (Integer) getAttributeInternal(COMMSPARTIALPK);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMS_PARTIAL_PK using the alias name CommsPartialPk.
     * @param value value to set the COMMS_PARTIAL_PK
     */
    public void setCommsPartialPk(Integer value) {
        setAttributeInternal(COMMSPARTIALPK, value);
    }

    /**
     * Gets the attribute value for COMMS_PERCENTAGE using the alias name CommsPercentage.
     * @return the COMMS_PERCENTAGE
     */
    public Number getCommsPercentage() {
        return (Number) getAttributeInternal(COMMSPERCENTAGE);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMS_PERCENTAGE using the alias name CommsPercentage.
     * @param value value to set the COMMS_PERCENTAGE
     */
    public void setCommsPercentage(Number value) {
        setAttributeInternal(COMMSPERCENTAGE, value);
    }

    /**
     * Gets the attribute value for COMPANY_ID_NO using the alias name CompanyIdNo.
     * @return the COMPANY_ID_NO
     */
    public String getCompanyIdNo() {
        return (String) getAttributeInternal(COMPANYIDNO);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_ID_NO using the alias name CompanyIdNo.
     * @param value value to set the COMPANY_ID_NO
     */
    public void setCompanyIdNo(String value) {
        setAttributeInternal(COMPANYIDNO, value);
    }

    /**
     * Gets the attribute value for COUNTRY_CODE using the alias name CountryCode.
     * @return the COUNTRY_CODE
     */
    public String getCountryCode() {
        return (String) getAttributeInternal(COUNTRYCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for COUNTRY_CODE using the alias name CountryCode.
     * @param value value to set the COUNTRY_CODE
     */
    public void setCountryCode(String value) {
        setAttributeInternal(COUNTRYCODE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for EFFECTIVE_END_DATE using the alias name EffectiveEndDate.
     * @return the EFFECTIVE_END_DATE
     */
    public Date getEffectiveEndDate() {
        return (Date) getAttributeInternal(EFFECTIVEENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EFFECTIVE_END_DATE using the alias name EffectiveEndDate.
     * @param value value to set the EFFECTIVE_END_DATE
     */
    public void setEffectiveEndDate(Date value) {
        setAttributeInternal(EFFECTIVEENDDATE, value);
    }

    /**
     * Gets the attribute value for EFFECTIVE_START_DATE using the alias name EffectiveStartDate.
     * @return the EFFECTIVE_START_DATE
     */
    public Date getEffectiveStartDate() {
        return (Date) getAttributeInternal(EFFECTIVESTARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EFFECTIVE_START_DATE using the alias name EffectiveStartDate.
     * @param value value to set the EFFECTIVE_START_DATE
     */
    public void setEffectiveStartDate(Date value) {
        setAttributeInternal(EFFECTIVESTARTDATE, value);
    }

    /**
     * Gets the attribute value for GROUP_CODE using the alias name GroupCode.
     * @return the GROUP_CODE
     */
    public String getGroupCode() {
        return (String) getAttributeInternal(GROUPCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for GROUP_CODE using the alias name GroupCode.
     * @param value value to set the GROUP_CODE
     */
    public void setGroupCode(String value) {
        setAttributeInternal(GROUPCODE, value);
    }

    /**
     * Gets the attribute value for INTERFACE_TO_COMMS using the alias name InterfaceToComms.
     * @return the INTERFACE_TO_COMMS
     */
    public String getInterfaceToComms() {
        return (String) getAttributeInternal(INTERFACETOCOMMS);
    }

    /**
     * Sets <code>value</code> as attribute value for INTERFACE_TO_COMMS using the alias name InterfaceToComms.
     * @param value value to set the INTERFACE_TO_COMMS
     */
    public void setInterfaceToComms(String value) {
        setAttributeInternal(INTERFACETOCOMMS, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CompanyLovView1.
     */
    public RowSet getCompanyLovView1() {
        return (RowSet) getAttributeInternal(COMPANYLOVVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CountryLovView1.
     */
    public RowSet getCountryLovView1() {
        return (RowSet) getAttributeInternal(COUNTRYLOVVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> FusionActiveBuVO1.
     */
    public RowSet getFusionActiveBuVO1() {
        return (RowSet) getAttributeInternal(FUSIONACTIVEBUVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CommonYN1.
     */
    public RowSet getCommonYN1() {
        return (RowSet) getAttributeInternal(COMMONYN1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> OhiGroupLovView1.
     */
    public RowSet getOhiGroupLovView1() {
        return (RowSet) getAttributeInternal(OHIGROUPLOVVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CountryLovView_N1.
     */
    public RowSet getCountryLovView_N1() {
        return (RowSet) getAttributeInternal(COUNTRYLOVVIEW_N1);
    }


}

