package com.liberty.health.comms.model.brokerage.vo;

import com.core.model.vo.classes.CoreViewObjectImpl;

import com.liberty.health.comms.model.brokerage.vo.common.CommsPartialReceiptVO;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 15 11:48:32 CAT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CommsPartialReceiptVOImpl extends CoreViewObjectImpl implements CommsPartialReceiptVO {
    /**
     * This is the default constructor (do not remove).
     */
    public CommsPartialReceiptVOImpl() {
    }
    
    public void setCreatedBy(String username) {
       
        System.out.println("in the setcreated by ");
        CommsPartialReceiptVOImpl vo = (CommsPartialReceiptVOImpl) this.getViewObject();
        CommsPartialReceiptVORowImpl row = (CommsPartialReceiptVORowImpl) vo.getCurrentRow();
        
        System.out.println("after fetching the current row ");
        row.setCreatedBy(username);
       
            this.getDBTransaction().commit();
            this.executeQuery();
            
        }

    /**
     * Returns the bind variable value for pCountryList.
     * @return bind variable value for pCountryList
     */
    public String getpCountryList() {
        return (String) getNamedWhereClauseParam("pCountryList");
    }

    /**
     * Sets <code>value</code> for bind variable pCountryList.
     * @param value value to bind as pCountryList
     */
    public void setpCountryList(String value) {
        setNamedWhereClauseParam("pCountryList", value);
    }
}


