package com.liberty.health.comms.model.brokerage.vo;

import com.core.model.vo.classes.CoreViewObjectImpl;

import com.liberty.health.comms.model.brokerage.vo.common.CompanyTableVO;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 06 13:03:23 CAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CompanyTableVOImpl extends CoreViewObjectImpl implements CompanyTableVO {
    /**
     * This is the default constructor (do not remove).
     */
    public CompanyTableVOImpl() {
    }

    /**
     * Returns the variable value for pCompanyTableIdNo.
     * @return variable value for pCompanyTableIdNo
     */
    public Integer getpCompanyTableIdNo() {
        return (Integer) ensureVariableManager().getVariableValue("pCompanyTableIdNo");
    }

    /**
     * Sets <code>value</code> for variable pCompanyTableIdNo.
     * @param value value to bind as pCompanyTableIdNo
     */
    public void setpCompanyTableIdNo(Integer value) {
        System.out.println("setting the company table id No "+value);
        ensureVariableManager().setVariableValue("pCompanyTableIdNo", value);
        this.executeQuery();
    }
}

