package com.liberty.health.comms.model.brokerage.vo;

import com.core.model.vo.classes.CoreViewRowImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 25 13:15:39 CAT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CompanyCorrMultinatVORowImpl extends CoreViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        CompanyIdNo,
        CompanyName,
        CompanyStartDate,
        CompanyEndDate,
        Countries,
        Colour,
        Multinational,
        CorrespondenceTemplate,
        TemplColour,
        CompanyTableTypeIdNo,
        CompanyCorrExceptionReport;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int COMPANYIDNO = AttributesEnum.CompanyIdNo.index();
    public static final int COMPANYNAME = AttributesEnum.CompanyName.index();
    public static final int COMPANYSTARTDATE = AttributesEnum.CompanyStartDate.index();
    public static final int COMPANYENDDATE = AttributesEnum.CompanyEndDate.index();
    public static final int COUNTRIES = AttributesEnum.Countries.index();
    public static final int COLOUR = AttributesEnum.Colour.index();
    public static final int MULTINATIONAL = AttributesEnum.Multinational.index();
    public static final int CORRESPONDENCETEMPLATE = AttributesEnum.CorrespondenceTemplate.index();
    public static final int TEMPLCOLOUR = AttributesEnum.TemplColour.index();
    public static final int COMPANYTABLETYPEIDNO = AttributesEnum.CompanyTableTypeIdNo.index();
    public static final int COMPANYCORREXCEPTIONREPORT = AttributesEnum.CompanyCorrExceptionReport.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CompanyCorrMultinatVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute CompanyIdNo.
     * @return the CompanyIdNo
     */
    public Number getCompanyIdNo() {
        return (Number) getAttributeInternal(COMPANYIDNO);
    }

    /**
     * Gets the attribute value for the calculated attribute CompanyName.
     * @return the CompanyName
     */
    public String getCompanyName() {
        return (String) getAttributeInternal(COMPANYNAME);
    }

    /**
     * Gets the attribute value for the calculated attribute CompanyStartDate.
     * @return the CompanyStartDate
     */
    public Date getCompanyStartDate() {
        return (Date) getAttributeInternal(COMPANYSTARTDATE);
    }

    /**
     * Gets the attribute value for the calculated attribute CompanyEndDate.
     * @return the CompanyEndDate
     */
    public Date getCompanyEndDate() {
        return (Date) getAttributeInternal(COMPANYENDDATE);
    }


    /**
     * Gets the attribute value for the calculated attribute Countries.
     * @return the Countries
     */
    public String getCountries() {
        return (String) getAttributeInternal(COUNTRIES);
    }

    /**
     * Gets the attribute value for the calculated attribute Colour.
     * @return the Colour
     */
    public String getColour() {
        return (String) getAttributeInternal(COLOUR);
    }

    /**
     * Gets the attribute value for the calculated attribute Multinational.
     * @return the Multinational
     */
    public String getMultinational() {
        return (String) getAttributeInternal(MULTINATIONAL);
    }

    /**
     * Gets the attribute value for the calculated attribute CorrespondenceTemplate.
     * @return the CorrespondenceTemplate
     */
    public String getCorrespondenceTemplate() {
        return (String) getAttributeInternal(CORRESPONDENCETEMPLATE);
    }

    /**
     * Gets the attribute value for the calculated attribute TemplColour.
     * @return the TemplColour
     */
    public String getTemplColour() {
        return (String) getAttributeInternal(TEMPLCOLOUR);
    }

    /**
     * Gets the attribute value for the calculated attribute CompanyTableTypeIdNo.
     * @return the CompanyTableTypeIdNo
     */
    public Number getCompanyTableTypeIdNo() {
        return (Number) getAttributeInternal(COMPANYTABLETYPEIDNO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link CompanyCorrExceptionReport.
     */
    public RowIterator getCompanyCorrExceptionReport() {
        return (RowIterator) getAttributeInternal(COMPANYCORREXCEPTIONREPORT);
    }
}

