package com.liberty.health.comms.model.brokerage.vo;

import com.core.model.vo.classes.CoreViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 28 11:54:22 CAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CompanyMultinationalRoViewImpl extends CoreViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CompanyMultinationalRoViewImpl() {
    }
}

