package com.liberty.health.comms.model.brokerage.vo;

import com.core.model.vo.classes.CoreViewObjectImpl;

import com.liberty.health.comms.model.brokerage.vo.common.CompanyCheckBrokerageNameVO;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 06 11:25:12 CAT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CompanyCheckBrokerageNameVOImpl extends CoreViewObjectImpl implements CompanyCheckBrokerageNameVO {
    /**
     * This is the default constructor (do not remove).
     */
    public CompanyCheckBrokerageNameVOImpl() {
    }

    /**
     * Returns the bind variable value for pCompName.
     * @return bind variable value for pCompName
     */
    public String getpCompName() {
        return (String) getNamedWhereClauseParam("pCompName");
    }

    /**
     * Sets <code>value</code> for bind variable pCompName.
     * @param value value to bind as pCompName
     */
    public void setpCompName(String value) {
        setNamedWhereClauseParam("pCompName", value);
    }
}

