CREATE OR REPLACE TRIGGER LHHCOM.COMMS_CALC_REV_ADJ_BEFORE_TRG
BEFORE 
INSERT OR UPDATE ON LHHCOM.COMMS_CALC_REV_ADJ
FOR EACH ROW
  BEGIN
  IF INSERTING THEN
   SELECT LHHCOM.COMMS_CALC_REV_ADJ_SEQ.NEXTVAL
    INTO :NEW.COMMS_CALC_REV_ADJ_NO
    FROM DUAL;
  ELSIF UPDATING THEN
   IF :OLD.COMMS_CALC_REV_ADJ_NO != :NEW.COMMS_CALC_REV_ADJ_NO THEN
      :NEW.COMMS_CALC_REV_ADJ_NO := :OLD.COMMS_CALC_REV_ADJ_NO;
   END IF;
  END IF;
  :new.DATE_STAMP := sysdate;
END;