package com.liberty.health.comms.model.watchlist.vo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jun 02 09:31:26 CAT 2017
// ---------------------------------------------------------------------
public interface CommissionsWatchListRoView extends ViewObject {
    void setpLocalCode(String value);
}

