package com.liberty.health.comms.model.ohi.vo.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 13 11:06:55 CAT 2017
// ---------------------------------------------------------------------
public interface NewOhiCommPercVO extends ViewObject {
    void setNewOhiCommPercVOCriteria(String productCode, oracle.jbo.domain.Number brokerIdNo,
                                     oracle.jbo.domain.Number companyIdNo, String groupCode, String inseCode,
                                     String policyCode);

    void setCompanyVc(oracle.jbo.domain.Number companyIdNo);

    void setGroupVc(String groupCode);

    void setPersonVc(String personCode);

    void setPolicyVc(String policyCode);

    void setProductVc(String groupCode, String productCode);

    String setAuthUsername(String username);

    void setpCompanyIdNo(oracle.jbo.domain.Number value);


    void setBrokerVc(oracle.jbo.domain.Number brokerIdNo);

    void setUpdateBrokerVc(oracle.jbo.domain.Number brokerIdNo, Date startDate);

    void setUpdateCompanyVc(oracle.jbo.domain.Number companyIdNo, Date startDate);

    void setUpdateGroupVc(String groupCode, Date startDate);

    void setUpdatePersonVc(String personCode, Date startDate);

    void setUpdatePolicyVc(String policyCode, Date startDate);

    void setUpdateProductVc(String groupCode, String productCode, Date startDate);

    String removeUserRecord();

    String setRejectUsername(String username, String comment);

    String resubmitForApproval();

    void setUpdateRejectBrokerVc(oracle.jbo.domain.Number brokerIdNo, Date startDate);

    void setUpdateRejectCompanyVc(oracle.jbo.domain.Number companyIdNo, Date startDate);

    void setUpdateRejectGroupVc(String groupCode, Date startDate);

    void setUpdateRejectPersonVc(String personCode, Date startDate);

    void setUpdateRejectPolicyVc(String policyCode, Date startDate);

    void setUpdateRejectProductVc(String groupCode, String productCode, Date startDate);

    void updateEffDates(Integer compIdNo, Integer brokerIdNo, String groupCode, String productCode, String policyCode,
                        String memberCode);
}

