package com.liberty.health.comms.model.ohi.vo.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 24 09:38:48 CAT 2017
// ---------------------------------------------------------------------
public interface NewOhiCommPercVORow extends Row {
    void setAuthUsername(String value);
}

