package com.liberty.health.comms.model.ohi.vo;

import com.core.model.vo.classes.CoreViewObjectImpl;

import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 05 14:29:00 CAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OhiPolicyBrokerRoViewImpl extends CoreViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public OhiPolicyBrokerRoViewImpl() {
    }
}

