package com.liberty.health.comms.model.ohi.vo;

import com.core.model.vo.classes.CoreViewRowImpl;

import oracle.jbo.RowSet;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 24 11:42:50 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OhiParentGroupLovViewRowImpl extends CoreViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ParentgroupCode,
        CountryCode,
        GroupCode,
        CountryLovView_N1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PARENTGROUPCODE = AttributesEnum.ParentgroupCode.index();
    public static final int COUNTRYCODE = AttributesEnum.CountryCode.index();
    public static final int GROUPCODE = AttributesEnum.GroupCode.index();
    public static final int COUNTRYLOVVIEW_N1 = AttributesEnum.CountryLovView_N1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public OhiParentGroupLovViewRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute ParentgroupCode.
     * @return the ParentgroupCode
     */
    public String getParentgroupCode() {
        return (String) getAttributeInternal(PARENTGROUPCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ParentgroupCode.
     * @param value value to set the  ParentgroupCode
     */
    public void setParentgroupCode(String value) {
        setAttributeInternal(PARENTGROUPCODE, value);
    }


    /**
     * Gets the attribute value for the calculated attribute CountryCode.
     * @return the CountryCode
     */
    public String getCountryCode() {
        return (String) getAttributeInternal(COUNTRYCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CountryCode.
     * @param value value to set the  CountryCode
     */
    public void setCountryCode(String value) {
        setAttributeInternal(COUNTRYCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute GroupCode.
     * @return the GroupCode
     */
    public String getGroupCode() {
        return (String) getAttributeInternal(GROUPCODE);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CountryLovView_N1.
     */
    public RowSet getCountryLovView_N1() {
        return (RowSet) getAttributeInternal(COUNTRYLOVVIEW_N1);
    }
}

