package com.liberty.health.comms.model.dashboard.vo;

import com.core.model.vo.classes.CoreViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 07 15:11:15 CAT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CommPercProductCodeRoViewImpl extends CoreViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CommPercProductCodeRoViewImpl() {
    }
}

