package com.liberty.health.comms.model.dashboard.vo;

import com.core.model.vo.classes.CoreViewRowImpl;

import oracle.jbo.RowSet;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 27 10:53:08 CAT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FusionActiveBuVORowImpl extends CoreViewRowImpl {


    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        BuName,
        Country,
        FusionActiveBuVO1,
        CountryLovView_N1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BUNAME = AttributesEnum.BuName.index();
    public static final int COUNTRY = AttributesEnum.Country.index();
    public static final int FUSIONACTIVEBUVO1 = AttributesEnum.FusionActiveBuVO1.index();
    public static final int COUNTRYLOVVIEW_N1 = AttributesEnum.CountryLovView_N1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public FusionActiveBuVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute BuName.
     * @return the BuName
     */
    public String getBuName() {
        return (String) getAttributeInternal(BUNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BuName.
     * @param value value to set the  BuName
     */
    public void setBuName(String value) {
        setAttributeInternal(BUNAME, value);
    }


    /**
     * Gets the attribute value for the calculated attribute Country.
     * @return the Country
     */
    public String getCountry() {
        return (String) getAttributeInternal(COUNTRY);
    }

    /**
     * Gets the view accessor <code>RowSet</code> FusionActiveBuVO1.
     */
    public RowSet getFusionActiveBuVO1() {
        return (RowSet) getAttributeInternal(FUSIONACTIVEBUVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CountryLovView_N1.
     */
    public RowSet getCountryLovView_N1() {
        return (RowSet) getAttributeInternal(COUNTRYLOVVIEW_N1);
    }

}

