package com.liberty.health.comms.model.dashboard.vo;

import com.core.model.vo.classes.CoreViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 24 13:51:23 CAT 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FusionGroupPremiumsReconVOImpl extends CoreViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FusionGroupPremiumsReconVOImpl() {
    }
}

